### ISSUE TITLE
Error "Rake aborted no RakeFile found" when trying to enter production mode

### ISSUE THREAD

**Issue by MasterX28** [pentestgeek/phishing-frenzy#106]
Hello!,

I am trying to configure production mode, however, when I enter the first line of code: RAILS_ENV=production rake assets:precompile

I get the following error -

![capture](https://cloud.githubusercontent.com/assets/9418833/4793403/b90d7ce0-5ded-11e4-86b3-a583669de841.JPG)

Here is the command with the --trace option:
root@Phish:~# RAILS_ENV=production rake assets:precompile --trace
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/local/rvm/gems/ruby-2.1.3/gems/rake-10.2.2/lib/rake/application.rb:672:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.1.3/gems/rake-10.2.2/lib/rake/application.rb:94:in`block in load_rakefile'
/usr/local/rvm/gems/ruby-2.1.3/gems/rake-10.2.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.1.3/gems/rake-10.2.2/lib/rake/application.rb:93:in`load_rakefile'
/usr/local/rvm/gems/ruby-2.1.3/gems/rake-10.2.2/lib/rake/application.rb:77:in `block in run'
/usr/local/rvm/gems/ruby-2.1.3/gems/rake-10.2.2/lib/rake/application.rb:176:in`standard_exception_handling'
/usr/local/rvm/gems/ruby-2.1.3/gems/rake-10.2.2/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.1.3/gems/rake-10.2.2/bin/rake:33:in`<top (required)>'
/usr/local/rvm/gems/ruby-2.1.3/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.1.3/bin/rake:23:in`<main>'
/usr/local/rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in`<main>'
root@Phish:~#

Thank you for your help!

**Comment by jeeveshmishra** [comment]
Whats the complete path for phishing-frenzy directory as am getting following error:

Error:[rake --tasks] rake aborted!
cannot load such file -- iconv
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/activesupport-2.3.15/lib/active_support/inflector.rb:3:in `require'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/activesupport-2.3.15/lib/active_support/inflector.rb:3:in `<top (required)>'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/activesupport-2.3.15/lib/active_support/core_ext/integer/inflections.rb:1:in `require'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/activesupport-2.3.15/lib/active_support/core_ext/integer/inflections.rb:1:in `<top (required)>'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/activesupport-2.3.15/lib/active_support/core_ext/integer.rb:2:in `require'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/activesupport-2.3.15/lib/active_support/core_ext/integer.rb:2:in `<top (required)>'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/activesupport-2.3.15/lib/active_support/core_ext.rb:8:in `require'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/activesupport-2.3.15/lib/active_support/core_ext.rb:8:in `block in <top (required)>'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/activesupport-2.3.15/lib/active_support/core_ext.rb:8:in `each'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/activesupport-2.3.15/lib/active_support/core_ext.rb:8:in `<top (required)>'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/activesupport-2.3.15/lib/active_support.rb:56:in `require'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/activesupport-2.3.15/lib/active_support.rb:56:in `<top (required)>'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rails-2.3.15/lib/tasks/misc.rake:18:in `require'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rails-2.3.15/lib/tasks/misc.rake:18:in `<top (required)>'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rails-2.3.15/lib/tasks/rails.rb:4:in `load'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rails-2.3.15/lib/tasks/rails.rb:4:in `block in <top (required)>'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rails-2.3.15/lib/tasks/rails.rb:4:in `each'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rails-2.3.15/lib/tasks/rails.rb:4:in `<top (required)>'
/Users/jeeveshmishra/Development/bi-console/bi-console/Rakefile:12:in `require'
/Users/jeeveshmishra/Development/bi-console/bi-console/Rakefile:12:in `<top (required)>'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rake-10.1.1/lib/rake/rake_module.rb:25:in `load'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rake-10.1.1/lib/rake/rake_module.rb:25:in `load_rakefile'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rake-10.1.1/lib/rake/application.rb:637:in `raw_load_rakefile'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rake-10.1.1/lib/rake/application.rb:94:in `block in load_rakefile'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rake-10.1.1/lib/rake/application.rb:93:in `load_rakefile'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rake-10.1.1/lib/rake/application.rb:77:in `block in run'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/bin/rake:23:in `load'
/Users/jeeveshmishra/.rvm/gems/ruby-2.2.3/bin/rake:23:in `<main>'

**Comment by zeknox** [comment]
@jeeveshmishra the full path to the default PF install location is /var/www/phishing-frenzy

Based on your error message it appears that the iconv gem has not been installed. Ensure that `bundle install` has completed successfully. If that has, try to install the gem manually `gem install iconv`
