### ISSUE TITLE
Ruby Style Syntax

### ISSUE THREAD

**Issue by cmluciano** [pentestgeek/phishing-frenzy#117]
While hacking on a few things, I noticed that phishing-frenzy does not follow any style conventions. I was wondering if you would be interested in a PR that adjusted style according to the [ruby community style guide] (https://github.com/bbatsov/ruby-style-guide).

One caveat is that this will touch a lot of code. However it would probably be best to enforce a style sooner since 73% of commits currently come from @zeknox. Because of this commit messages and code is already well-known to the author.

Let me know what you think!

**Comment by zeknox** [comment]
Closing for now since there has been no updates, re-open when you are ready to tackle.
