### ISSUE TITLE
SMTP Sending Delay

### ISSUE THREAD

**Issue by kane2103** [pentestgeek/phishing-frenzy#119]
Hi. I've been using Phishing Frenzy quite a lot recently and think it's a great tool. One issue I have encountered though is when enabling a sending delay under 'Phishing Options' an error occurs which terminates all background scripts. So in this case the email script terminates part way through the phishing mailing list.

I looked at the Apache error log as this was the error page I was presented with and discovered the below passenger errors:

<pre>
[Mon Nov 24 20:41:12 2014] [notice] Apache/2.2.22 (Debian) PHP/5.4.35-0+deb7u2 Phusion_Passenger/4.0.53 configured -- resuming normal operations
[ 2014-11-24 20:41:42.1437 30110/7fc6898d2720 agents/Watchdog/Main.cpp:386 ]: Some Phusion Passenger agent processes did not exit in time, forcefully shutting down all.
[Mon Nov 24 20:41:42 2014] [error] [client 127.0.0.1] Premature end of script headers: email, 
referer: http://phishingfrenzy.local/campaigns/2
</pre>

The current setup I'm using is a postfix server to relay mail and running the Phishing Frenzy application in production mode. When the delay is set to zero I can send around 100 emails no problem (not tested higher). Once the delay is set I can only get around 6 emails out to the relay server before the phishing frenzy application forcefully closes the email script.

I hope the above paints a good enough picture of the issue in the first instance. Any help would be greatly appreciated. 

Kane2103 (zdkano - we briefly spoke on Twitter a few days ago)

**Comment by zeknox** [comment]
Closing, but referencing this ticket which is mean to address the smtp delay functionality with sidekiq:
https://github.com/pentestgeek/phishing-frenzy/issues/318
