### ISSUE TITLE
Kali Linux - Error while updating, can't get in Admin page

### ISSUE THREAD

**Issue by hernandezjj** [pentestgeek/phishing-frenzy#128]
I am getting this error while updating PF.

******************************************
root@kali:/var/www/phishing-frenzy# git pull origin master
From https://github.com/pentestgeek/phishing-frenzy
 * branch            master     -> FETCH_HEAD
Updating 3a1d984..e0eb4f4
error: Your local changes to the following files would be overwritten by merge:
	config/application.rb
Please, commit your changes or stash them before you can merge.
Aborting
****************
Is this normal? I continued the installation and now I can't get in the admin site to manage the campaign. If I use "127.0.0.1" or "127.0.1.1" or "localhost" or "phishingfrenzy.local" I get to the "Phishing-frenzy/public" directory. If I keep the 1.conf file in the "Sites-enabled" then I get the intel phishing campaign which was the one I had setup before this happened. 

 this is my pf.conf
***************
  <IfModule mod_passenger.c>
    PassengerRoot %ROOT
    PassengerRuby %RUBY
  </IfModule>

  <VirtualHost *:80>
    ServerName phishingfrenzy.local
    # !!! Be sure to point DocumentRoot to 'public'!
    DocumentRoot /var/www/phishing-frenzy/public
    RailsEnv production
    <Directory /var/www/phishing-frenzy/public>
      # This relaxes Apache security settings.
      AllowOverride all
      # MultiViews must be turned off.
      Options -MultiViews
    </Directory>
  </VirtualHost>
******************

I have it under production mode and not using a domain name (althought that is my goal, but until I get it to work locally), I have it installed in Kali Linux. My Hosts file is the following:
127.0.0.1	localhost
127.0.1.1	kali

The httpd.conf file is blank no FQDN, again the goal is to use my domain name, but dont know how to accomplish that.

by the way it was working fine before I tried to update PF. It was working fine under Production mode and the next step was to figure out how to use the domain name.

thank you,

**Comment by zeknox** [comment]
Yeah this is odd behavior. Could you run a `git pull origin master` to ensure all the code is fully up to date?

**Comment by zeknox** [comment]
Is this ticket still needed or did you end up reinstalling?

**Comment by hernandezjj** [comment]
I ended up reinstalling Kali Linux and in the process of reinstalling
Phishiing frenzy.

**Comment by zeknox** [comment]
Closing ticket for no, please re-open if needed.
