### ISSUE TITLE
Removing/Reinstalling phishing frenzy

### ISSUE THREAD

**Issue by hernandezjj** [pentestgeek/phishing-frenzy#129]
How do I remove phishing frenzy? I tried to do it all again and I am still having the same issue.  I would like to start fresh with the latest phishing frenzy

thank you,

**Comment by zeknox** [comment]
Remove the directory located at /var/www/phishing-frenzy.

You could remove any databases that you have created in mysql before continuing, but then follow one of the install guides of phishingfrenzy.com.  Also take a look at the docker install script which automates the process.

**Comment by zeknox** [comment]
Did you end up getting everything reinstalled properly?

**Comment by hernandezjj** [comment]
will do that this weekend, I do have a domain name so that would be my next
question how and where do I configure this.

thanks

**Comment by hernandezjj** [comment]
I reinstalled Kali Linux and tried the docker install script, but I get to
the last step and nothing happens, I looked for the phishing-frenzy
folders, the local URL, phishingfrenzy.local and nothing. I verified the
image download and docker install.

Here is what I get when I attempt to run the last step of the docker
install:

root@Kali-LX03IC:~# docker run -d -p 80:80 b00stfr3ak/ubuntu-phishingfrenzy
17142d1e4ed3c75bb0deabbc42dadb996650d375462acd945c2160acec76633b

root@Kali-LX03IC:~# docker run -d -p 80:80 b00stfr3ak/ubuntu-phishingfrenzy
216d0750d21e8b0048e4df7d73be41d897405aa8b122632db1fcb020fb569a0a
FATA[0000] Error response from daemon: Cannot start container
216d0750d21e8b0048e4df7d73be41d897405aa8b122632db1fcb020fb569a0a: Bind for
0.0.0.0:80 failed: port is already allocated

I am not sure where to go from here so I want to see if you can help me out
before I do it manually.

thanks,

J

**Comment by zeknox** [comment]
You already have a service bound to port 80 on the system you are trying to install PF onto.

Find out what service is bound to port 80 with:
<pre>$ sudo netstat -antp</pre>

**Comment by hernandezjj** [comment]
Here is what I found


root@Kali-LX03IC:~# netstat -antp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address
State       PID/Program name
tcp        0      0 127.0.0.1:3306                     0.0.0.0:*
LISTEN      8626/mysqld
tcp        0      0 172.16.101.151:46346    173.194.123.53:443
ESTABLISHED 3709/iceweasel
tcp6       0      0 :::80                   :::*
              LISTEN      7229/docker-proxy

looks like it's docker-proxy,

**Comment by hernandezjj** [comment]
so i rebooted and now I am building an image from GitHub. I'll try again
using this method and will report.

by the way where oes the image gets stored locally?

thanks,

**Comment by hernandezjj** [comment]
so I tried the second option and it installed many items successfully I got
this error:

Successfully installed erubis-2.7.0
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session
ticket A (https://bb-m.rubygems.org/gems/builder-3.2.2.gem)
INFO[1616] The command [/bin/sh -c gem install --no-rdoc --no-ri rails]
returned a non-zero code: 1
root@Kali-LX03IC:~#

by the way here is what I get after running docker images:

root@Kali-LX03IC:~# docker images
REPOSITORY                         TAG                 IMAGE ID
CREATED             VIRTUAL SIZE
<none>                             <none>              1e01dfe4be49
54 minutes ago      637.8 MB
ubuntu                             latest              b39b81afc8ca
2 days ago          188.3 MB
b00stfr3ak/ubuntu-phishingfrenzy   latest              1e7c3ae22472
4 days ago          1.245 GB


so it looks like I have 1 full image, but I can't seem to install it.

let me know what you think so I can do it manually.

thanks,

**Comment by zeknox** [comment]
Your in no mans land, not sure how to help you bro.

**Comment by hernandezjj** [comment]
Ok I'll do it manually. thanks though

**Comment by zeknox** [comment]
Going to close this ticket for now, please re-open if needed.
