### ISSUE TITLE
Unable to load PF main page in KALI

### ISSUE THREAD

**Issue by janspaugh** [pentestgeek/phishing-frenzy#140]
I have installed PF on my KALI box per the installation guide listed on the PF website while also following along with the youtube video. Everything installed correctly but once I start the Apache2 website and navigate to phishingfrenzy.local all I recieve is the default Apache Webpage.

it works

I have configured PF to run through the local loopback 127.0.0.1 and have modified the "hosts" file shown below.
hosts

I have also configured the pf.conf, httpd.conf, and application.rb files to reflect this
pf conf

httpd

application rb

I have also included the apache2.conf file for review.

apache2 conf

In addition to this I also tried disableing Apache's default webpage with no joy. Any information that you could provide would be greatly appreciated.

Thanks,
J

**Comment by zeknox** [comment]
What is the results of `apachectl -S`. This will display your configured virtual hosts.

**Comment by janspaugh** [comment]
![apachectl-s](https://cloud.githubusercontent.com/assets/10607511/5811626/c86addfa-a027-11e4-9c0d-9d62543c431e.png)

**Comment by zeknox** [comment]
Restart your apache service and browse to phishingfrenzy.local should work if you have properly configured your /etc/hosts file.

**Comment by janspaugh** [comment]
That worked. I didn't make configuration changes, and I had restarted the apache service in the past with no luck...At any rate it's working now which is all that matters. Thanks.

J

**Comment by zeknox** [comment]
Sweet, happy phishing!
