### ISSUE TITLE
Apache won't serve up Phishing Website

### ISSUE THREAD

**Issue by janspaugh** [pentestgeek/phishing-frenzy#141]
So I have gone through the campaign configurations several time, the email sends successfully with the link embedded in it, but when I click on the link to conduct a test it can't find the website which I am assuming is because Apache is not serving that website up when the campaign is launched. I have ensured that I have all of the information for the campaign entered into the fields and saved before make the campaign active and launch as well as restarting the Apache service. Any ideas on what I am missing?

**Comment by zeknox** [comment]
Could you please show me the result of `apachectl -S`. Also you can ensure that the campaign files are being saved out properly to `/etc/apache2/sites-enabled/:id.conf` when a campaign is active.

The next item I would look into is ensuring that you have modified the sudoers file to allow the www-data account to restart apache properly.

**Comment by zeknox** [comment]
Bump, any update here?

**Comment by janspaugh** [comment]
I think this was more of an infrastructure issue that I am working with
my IT department to fix. I appreciate all of the help and I will let you
know if we can't get it up and running.

Thanks,

Jeremy
On 1/29/2015 12:55 PM, Brandon McCann wrote:
>
> Bump, any update here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pentestgeek/phishing-frenzy/issues/141#issuecomment-72071599>.
>

-- 
Jeremy Anspaugh
Lead Forensics Engineer
Disruptive Solutions LLC
571-206-0983 x505

**Comment by zeknox** [comment]
Bump, any updates here?

**Comment by janspaugh** [comment]
Sorry for the delay on this, the issues that I was running into were related to internal IT configurations which have been resolved. I am up and running with PF now and everything seems to be on track. Thanks for all of your help.

**Comment by zeknox** [comment]
Thanks for the update!
