### ISSUE TITLE
Inconstant Error Thrown in Template Restore Function

### ISSUE THREAD

**Issue by infosecrepo** [pentestgeek/phishing-frenzy#143]
When importing/restoring templates I'm thrown the following (This error does not occur 100% of the time, I was able in import/restore a few templates):

ArgumentError in TemplatesController#upload

undefined class/module Template

The error highlights line 116: template = YAML.load(template_yml.get_input_stream.read)

app/controllers/templates_controller.rb:116:in `upload'

Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"eS9euVXrVPOTix7a1DQzI58Pxh/GAZx4f3A2Y/i5WAg=",
 "restore_template"=>#<ActionDispatch::Http::UploadedFile:0x00000008159e30 @tempfile=#<Tempfile:/tmp/RackMultipart20150129-1515-vpiynk>,
 @original_filename="linkedin.zip",
 @content_type="application/zip",
 @headers="Content-Disposition: form-data; name=\"restore_template\"; filename=\"linkedin.zip\"\r\nContent-Type: application/zip\r\n">,
 "commit"=>"Restore Template"}

Let me know if there's anything needed to troubleshoot further.

**Comment by johnk3r** [comment]
Hi @jrshap

Already checked the permissions this ok? I had this same problem and it was for lack of permission in a specific directory.

**Comment by zeknox** [comment]
This sounds like a permissions issues on the uploads folder. Take a look at this link here and update us if it addresses your issue:

https://github.com/pentestgeek/phishing-frenzy/issues/138

**Comment by zeknox** [comment]
@johnk3r do you recall exactly which folder it was that had the permissions issue?  We probably should code this upload functionality to handle the error more gracefully and state which folder has the permission issue.

**Comment by johnk3r** [comment]
Hi @zeknox 
The directory is what you had mentioned: "chmod -R 755 / var / www / phishing-frenzy / public / uploads /". Not noticed this detail in the documentation. This permission information was displayed when it was the export of Template.

**Comment by zeknox** [comment]
@johnk3r thanks for the update.  It looks like we do have this step included in the install directions here:

http://www.phishingfrenzy.com/resources/install_kali_linux

**Comment by jrshap** [comment]
Ran chmod -R 755 /var/www/phishing-frenzy/public/uploads/ and it appears to have resolved the issue.

Thanks @johnk3r and @zeknox!

**Comment by zeknox** [comment]
Great stuff! Thanks for the quick update. I think I'm going to leave this ticket open as a reminder for me to write the code to handle this exception properly.
