### ISSUE TITLE
Allowing custom fields in campaigns

### ISSUE THREAD

**Issue by DeathsPirate** [pentestgeek/phishing-frenzy#144]
I'd like to add a field in the import of addresses to allow a city to be specified, I am not a ruby guru by any stretch and would like to know how easy this would be to implement?  The city would pull through to the email template and be saved in the db against that user.

**Comment by zeknox** [comment]
This will take a little bit of work. The first piece would be adding in the additional database column for the Victims table using a migration. Once the database was configured properly you would need to also write some parsing logic in the campaigns.rb model to parse out this added City field and store it into the database properly.

Once that is setup you should be able to use the City variable within the template.

The other approach is if you are not currently using the firstname, and lastnmae field you could use these as placeholder. Simply add in your city to the firstname field, and then use the firstname variable in your template.

Hope this helps.

**Comment by DeathsPirate** [comment]
Ah good shout on using the lastname field, I hadn't considered that.  Will have a go at doing it properly and then use that as a fallback option. 

Many thanks.
