### ISSUE TITLE
Invalid API key when using email enumeration

### ISSUE THREAD

**Issue by NVolcz** [pentestgeek/phishing-frenzy#145]
I'm getting a "Invalid API key" error message when trying to use the Email enumeration functionality.
I've signed up for a bing search API and copy-pasted the API key.

**Comment by zeknox** [comment]
Did the BING API key ever work for you?  If so it might be that your out of free transactions for the month?

**Comment by NVolcz** [comment]
Nope. Never worked. Is there any way to enable more logging?

**Comment by zeknox** [comment]
To get more details on the error in this case you will want to modify this line:

https://github.com/pentestgeek/phishing-frenzy/blob/master/app/controllers/tools_controller.rb#L67

Change the notify string to the following:

<pre>
redirect_to tools_emails_path, notice: "Invalid Bing API Key: #{e}"
</pre>

**Comment by zeknox** [comment]
Any update here on the additional errors when modifying the code above?

**Comment by NVolcz** [comment]
Sorry. Haven't gotten around to test it yet. Well most likely spend some
time on it tomorrow.

**Comment by zeknox** [comment]
Bump. any updates here?

**Comment by NVolcz** [comment]
Magically works now. Maybe there is a delay before the API key can be used after creation...

**Comment by zeknox** [comment]
Its magic!

**Comment by RatedRR** [comment]
Hi, it always shows "Invalid Bing API Key" is there any solution for that please ? (not with magic of course lol)

**Comment by zeknox** [comment]
I thought I heard that Bing no longer offers a free API key, I would guess that may be part of the issue here?

**Comment by RatedRR** [comment]
Hi zeknox, sorry for the late response. They still offering API keys a,d I have already one and I entered it in the required field in PF (Bing API Key) but when searching it always shows "Invalid Bing API Key".
There is a notice in the http://datamarket.azure.com/dataset/bing/search
"DataMarket and Data Services are being retired and will stop accepting new orders after 12/31/2016. Existing subscriptions will be retired and cancelled starting 3/31/2017. Please reach out to your service provider for options if you want to continue service."
I don't know if it has a relation with this issue ...
