### ISSUE TITLE
Ruby 2.2 errors

### ISSUE THREAD

**Issue by efensive** [pentestgeek/phishing-frenzy#147]
Having an issue with the latest git repo. Had thought this was fixed:

xo@prometheus:/var/www/phishing-frenzy# rake db:migrate
/var/www/phishing-frenzy/vendor/bundle/ruby/2.2.0/gems/htmlentities-4.3.2/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
warning: you are loading parser/ruby22 from /var/www/phishing-frenzy/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'.
warning: Ruby 2.2 is not released yet and parser support may be incomplete.

xo@prometheus:/var/www/phishing-frenzy# ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]

**Comment by zeknox** [comment]
Good to know! thanks for the feedback.  It looks like there are some bugs with ruby 2.2 as you've already called out.

Here is how you can get ruby 2.1 up and running if you've installed ruby using rvm.

Install 2.1
<pre>
$ rvm install 2.1.1
</pre>

Use 2.1
<pre>
$ rvm use 2.1.1
</pre>

Set 2.1 as default
<pre>
$ rvm use --default 2.1.1
</pre>

**Comment by zeknox** [comment]
any update here if this resolved your issues?

**Comment by zeknox** [comment]
Updated install docs to install the specific version of ruby 2.1 using rvm
* http://www.phishingfrenzy.com/resources/install_kali_linux
* http://www.phishingfrenzy.com/resources/install_ubuntu_linux
