### ISSUE TITLE
Allow email testing using popular attachment types

### ISSUE THREAD

**Issue by daijizai** [pentestgeek/phishing-frenzy#149]
Modern adversarial phishing campaigns, such as the one leading to the RSA breach a few years back, have a tendency to use attachment based delivery mechanisms in addition to link based. Incorporating support for popular business attachment types (DOC, DOCX, XLS, XLSX, PDF, PPT, PPTX) would provide immeasurable benefit.

**Comment by ad0nis** [comment]
Gotta put a big +1 on this. I am absolutely floored that PF doesn't support basic malicious attachment functionality - As far as I can tell, if I attempt to attach a malicious xls file, it doesn't even get sent.

**Comment by curi0usJack** [comment]
I have to agree with this, especially considering what the documentation says about attachments:

"Attachments are typically images you want to embed within the email, but they are not limited to that alone. You can attach files to your phishing emails as well using attachments."

PF is a great tool and we've been using it quite extensively in our testing. Would absolutely love to see attachment support for at least the typical Office file types.

**Comment by zeknox** [comment]
I have been testing this functionality in the development branch FYI and working well for me. Would be open to any feedback you have testing this branch.

**Comment by daijizai** [comment]
Excellent. I'll have to find the time to pull and check this out. Is the tracking able to be done on attachment open? It might be after DC23 before I am able to really look. Has anyone else tested this?

**Comment by zeknox** [comment]
Just to clarify this does not include any tracking capabilities with the attachments added to the email. This simply allows files to be uploaded to a template, which in turn get attached to the email sent for that template.

I have tested this a few times in my production environment and working well for attaching common filetypes

**Comment by daijizai** [comment]
Are there designs on incorporating functionality to tracking "attachment opened" actions with a defined set of common attachments (XLS, DOC, PDF)? This is pretty much the riskiest action a user could take.

**Comment by zeknox** [comment]
No there is no designs or examples for tracking attachments. This topic has been covered multiple times here:
* https://github.com/pentestgeek/phishing-frenzy/issues/175
* https://github.com/pentestgeek/phishing-frenzy/issues/108
