### ISSUE TITLE
Cant install PF in Kali-Linux-1.1.0-vm-amd64 

### ISSUE THREAD

**Issue by mhdezgt** [pentestgeek/phishing-frenzy#151]
followed carefully  the tutorial @ http://n0where.net/phishing-frenzy/ follow the guide you guys have 
everything looks like is ok ... but then i start getting errors specially with this:

<pre>
root@kali:/var/www/phishing-frenzy# bundle exec sidekiq -C config/sidekiq.yml
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.2-compliant syntax, but you are running 2.1.1.
</pre>

<pre>
root@kali:/var/www/phishing-frenzy# www-data ALL=(ALL) NOPASSWD: /etc/init.d/apache2 reload
bash: syntax error near unexpected token `('
</pre>

<pre>
root@kali:/var/www/phishing-frenzy# rake templates:load
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.2-compliant syntax, but you are running 2.1.1.
</pre>

so not sure what going on... any thoughts?

**Comment by zeknox** [comment]
Those warnings are fine.

`www-data ALL=(ALL) NOPASSWD: /etc/init.d/apache2 reload` this however is not a command. Its a line item that needs to be added to `/etc/sudoers` file to allow the application to reload apache.

**Comment by mhdezgt** [comment]
thanks man today I will try again... what version of ruby would you recommend me using? 
cheers

**Comment by zeknox** [comment]
Ruby 2.1 should work fine.

**Comment by mhdezgt** [comment]
thx another question and sorry im being such a big pain, however i do want to understand better the process not only go through the instructions, on the video on n0wher.net you add to the apache.conf 
Include pf.conf and httpd.conf however on the kali install guide http://www.phishingfrenzy.com/resources/install_ubuntu_linux there is no httpd.conf file adress... why? what impact should this have on my installation?

**Comment by zeknox** [comment]
Those are older instructions where the httpd.conf file was used with PF. This is no longer the case. PF use to rewrite the httpd.conf to configure virtualhosts that would act as the phishing sites. Now PF will drop an individual file in /etc/apache2/sites-enabled/:id.conf for each configure phishing site so the httpd.conf is no longer needed.

The pf.conf file is used to ensure the web interface for PF is always running and available.  The include PF line inside of the apache.conf file is what enables the PF web interface to always be running when Apache is running.

Hope this helps.

**Comment by mhdezgt** [comment]
it does thank you a lot, so i will rely mainly on the guide and not on the video, also i noted that on the video you change the URL to phishingfrenzy.local is this a good thing to do?

**Comment by zeknox** [comment]
The URL is totally preference. If you already own a public domain that you would like to hook up with PF, feel free to configure the URL to anything you would like. phishingfrenzy.local is simply an example.

If you don't have DNS or anything pointing your domain to the ip address where PF is running, ensure you edit your /etc/hosts/ file to point your FQDN to the ip address.

**Comment by mhdezgt** [comment]
what if do not own a domain? can i hook PF to something else?

**Comment by zeknox** [comment]
If you do not own a domain you will want to edit your /etc/hosts file locally on your system to point the FQDN of your choosing to the ip address where PF is running.

If you want others to visit your PF web ui you will most likely need a domain of some sort, or be in control of DNS where you can point a domain to the ip address.

**Comment by mhdezgt** [comment]
sweet finally got everything installed correctly no weird errors or missing gems .... still and im really sorry to be a noob in this arena my veteran arena is forensics and IR .... 

this is what i have on my pf.conf
ServerName http://portal.phishingfrenzy.com
    # !!! Be sure to point DocumentRoot to 'public'!
    DocumentRoot /var/www/phishing-frenzy/public

and this is the url on application.rb
module PhishingFramework
  # Default website for reports stuff, must change to callback.
  SITE_URL = "http://phishingfrenzy.local"

however when i start apache and connect in iceweasel to http://portal.phishingfrenzy.com i just get a Loading... and nothing else...

**Comment by zeknox** [comment]
Show me the result of `apachectl -S`

This will take a look at all of Apaches VirtualHosts and tell us how they are configured.

**Comment by mhdezgt** [comment]
root@kali:/var/www/phishing-frenzy/config# apachectl -S
apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1 for ServerName
VirtualHost configuration:
wildcard NameVirtualHosts and _default_ servers:
*:80                   is a NameVirtualHost
         default server 127.0.1.1 (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost 127.0.1.1 (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost portal.phishingfrenzy.com (/etc/apache2/pf.conf:1)
Syntax OK

**Comment by zeknox** [comment]
Alright, so it looks like `portal.phishingfrenzy.com` is configured properly as we can see it in the list.  My guess is you need a simple restart of the apache service and then it should work.

**Comment by mhdezgt** [comment]
root@kali:/var/www/phishing-frenzy/config# sudo service apache2 restart
[....] Restarting web server: apache2apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1 for ServerName
 ... waiting apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1 for ServerName


but still just showing me the Loading screen

**Comment by zeknox** [comment]
Alright, do this. What's happening is its loading the first virtualHost in the list. So lets remove the file located at `/etc/apache2/sites-enabled` and just move the 000-default file into `/etc/apache2/sites-available`

Then restart the apache service and the pf.conf should be the only website configured.

**Comment by mhdezgt** [comment]
root@kali:/etc/apache2/sites-available# ls
000-default  default  default-ssl
root@kali:/etc/apache2/sites-available# cd /var/www/phishing-frenzy/
root@kali:/var/www/phishing-frenzy# sudo service apache2 restart
[....] Restarting web server: apache2apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1 for ServerName
 ... waiting apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1 for ServerName
. ok 

No Luck :(

**Comment by zeknox** [comment]
Show me the result of `apachectl -S` now

**Comment by mhdezgt** [comment]
root@kali:/var/www/phishing-frenzy# apachectl -S
apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1 for ServerName
VirtualHost configuration:
wildcard NameVirtualHosts and _default_ servers:
*:80                   is a NameVirtualHost
         default server portal.phishingfrenzy.com (/etc/apache2/pf.conf:1)
         port 80 namevhost portal.phishingfrenzy.com (/etc/apache2/pf.conf:1)
Syntax OK

**Comment by zeknox** [comment]
This looks proper. The only website apache should be serving up on port 80 is whatever you have configured in `/etc/apache2/pf.conf` which seams to have a fqdn of `portal.phishingfrenzy.com`.

What happens if you try and browse just the ip address of the PF interface.

**Comment by mhdezgt** [comment]
it works!!! :)

**Comment by zeknox** [comment]
its sounds like something is misconfigured with your hosts file or DNS where `portal.phishingfrenzy.com` does not point to the ip address of your PF instance.

**Comment by mhdezgt** [comment]
thanks a lot man!! cheers

**Comment by zeknox** [comment]
enjoy!
