### ISSUE TITLE
Web app painfully slow

### ISSUE THREAD

**Issue by tcstool** [pentestgeek/phishing-frenzy#152]
Followed everything through the great guide installing on Ubuntu 12.04 LTS.  The page loads in the app are dreadfully slow (30-45 seconds per page).  I have changed the value of config.assets.debug in /confi/environments/development.rb to false, which has worked well for me in previous rails app slowness troubleshooting but didn't help in this instance.

**Comment by zeknox** [comment]
Run the application in production mode.

**Comment by tcstool** [comment]
Can you provide guidance on migrating to production? I did what I usually
by setting the RAILS_ENV variable and adding the line to environment.rb but
that broke the application.  I'm sure I missed a step.

**Comment by zeknox** [comment]
http://www.phishingfrenzy.com/resources/rails_production_mode

Let me know if anything here doesn't work for ya.

**Comment by tcstool** [comment]
Everything worked great but unfortunately the app is still painfully slow.
I do get this warning:

warning: parser/current is loading parser/ruby21, which recognizes

warning: 2.1.2-compliant syntax, but you are running 2.1.1.


Could this be a contributor?

**Comment by zeknox** [comment]
Are you sure that you modified the line inside `/etc/apache2/pf.conf` file and change development to production and restarted the apache service?

If you are running in production mode and still have performance issues I would start to look at some performance tools such as top, free, and others to find out where the bottleneck is coming from.

**Comment by tcstool** [comment]
Yeah I'm certain it took because the errors and stack traces have stopped
showing up in the app.  I don't see any excess system usage.  I'm building
a second system locally (the first was built on Microsoft Azure) to see if
I can replicate.

**Comment by zeknox** [comment]
Ok good feedback. It doesn't require too much for hardware requirements. I've typically been running about 512mb ram with a single CPU with no issues.

**Comment by tcstool** [comment]
All fixed up.  This issue was tied to problems with the Ubuntu VM template
on Azure and Ruby.  In our data center, this worked great.  Thanks for the
help!

**Comment by zeknox** [comment]
Appreciate the feedback and posting what the issue was. Have fun!

**Comment by Meatballs1** [comment]
@tcstool Any clue what the configuration issue was? I also seem to be hitting slowness in production.

**Comment by tcstool** [comment]
I had originally tried to build the platform on Microsoft Azure.  Azure and
Ruby....Well to say they don't get along well is an understatement! When I
rebuilt in the exact same fashion using a local server it was fine.

**Comment by Meatballs1** [comment]
Hmm, I basically get a 10s consistant delay on every request. 

Was quicker to run it via webbrick... :D

**Comment by Meatballs1** [comment]
I think it may be a DNS timeout issue... Somewhere....

**Comment by Meatballs1** [comment]
This appears to be consistant, note 10s completion time :(

```
Started GET "/reports/list" for 10.10.0.14 at 2015-07-17 18:12:42 +0100
Processing by ReportsController#list as HTML
  Admin Load (0.2ms)  SELECT  `admins`.* FROM `admins`  WHERE `admins`.`id` = 1  ORDER BY `admins`.`id` ASC LIMIT 1
  GlobalSettings Load (0.2ms)  SELECT  `global_settings`.* FROM `global_settings`   ORDER BY `global_settings`.`id` ASC LIMIT 1
  CACHE (0.1ms)  SELECT  `global_settings`.* FROM `global_settings`   ORDER BY `global_settings`.`id` ASC LIMIT 1
No such process

*** The wait time appears here***

   (0.2ms)  SELECT COUNT(*) FROM `campaigns`  WHERE `campaigns`.`email_sent` = 1
  Campaign Load (0.2ms)  SELECT `campaigns`.* FROM `campaigns`  WHERE `campaigns`.`email_sent` = 1  ORDER BY `campaigns`.`created_at` DESC
  Rendered reports/list.html.erb within layouts/application (9.4ms)
  Rendered layouts/_system_status.html.erb (1.0ms)
  Rendered layouts/_navigation.html.erb (5.1ms)
Completed 200 OK in 10270ms (Views: 57.6ms | ActiveRecord: 2.5ms)
```

**Comment by zeknox** [comment]
Does this happen on the same controller action, or multiple different pages?

**Comment by Meatballs1** [comment]
Have got to the bottom of it! I hadn't set an iptables rule for localhost, which was preventing sidekiq from connecting to redis.

**Comment by zeknox** [comment]
*golf clap*

**Comment by Meatballs1** [comment]
:)
