### ISSUE TITLE
SSL Campaign Error

### ISSUE THREAD

**Issue by nerbix** [pentestgeek/phishing-frenzy#153]
Upon launching an SSL enabled campaign, the phishing-frenzy interface page (https://phishingfrenzy.local) no longer works and instead re-directs to the launched SSL campaign page.

**Comment by zeknox** [comment]
What is the results of apachectl -S

**Comment by nerbix** [comment]
root@kali:~# apachectl -S
VirtualHost configuration:
wildcard NameVirtualHosts and _default_ servers:
*:443                  phishingfrenzy.local (/etc/apache2/pf.conf:6)
*:80                   is a NameVirtualHost
         default server kali.kali.xxx.lab (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost kali.kali.xxx.lab (/etc/apache2/sites-enabled/000-default:1)
Syntax OK

This is after rolling back to a snapshot prior to launching the campaign and breaking things :)

**Comment by zeknox** [comment]
There are no virtualHosts configured within that output. Could you make a Campaign active with SSL and then show the result of `apachectl -S`

**Comment by nerbix** [comment]
root@kali:~# apachectl -S
[Thu Mar 12 06:10:15 2015] [warn] _default_ VirtualHost overlap on port 443, the first has precedence
VirtualHost configuration:
wildcard NameVirtualHosts and _default_ servers:
*:443                  client.sslenabled.org (/etc/apache2/sites-enabled/3.conf:8)
*:443                  phishingfrenzy.local (/etc/apache2/pf.conf:6)
*:80                   is a NameVirtualHost
         default server kali.kali.xxx.lab (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost kali.kali.xxx.lab (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost client.sslenabled.org (/etc/apache2/sites-enabled/3.conf:1)
Syntax OK

**Comment by zeknox** [comment]
Ok, this looks proper and `phishingfrenzy.local` should serve up the PF interface. Try it now, if it does not load the PF interface, restart Apache manually.

**Comment by nerbix** [comment]
restarted and it still loads the SSL enabled phishing site.  

I do get warnings of the conflict on 443 -- which sounds like it is prioritizing the phishing site over PF.
root@kali:~# service apache2 restart
[....] Restarting web server: apache2[Thu Mar 12 06:14:24 2015] [warn] _default_ VirtualHost overlap on port 443, the first has precedence
 ... waiting [Thu Mar 12 06:14:25 2015] [warn] _default_ VirtualHost overlap on port 443, the first has precedence

**Comment by zeknox** [comment]
Uncomment out the line `# NameVirtualHost *:443` inside of `/etc/apache2/ports.conf` and restart apache.

**Comment by nerbix** [comment]
Contents of my ports.conf 

root@kali:~# cat /etc/apache2/ports.conf 
# If you just change the port or add more ports here, you will likely also
# have to change the VirtualHost statement in
# /etc/apache2/sites-enabled/000-default
# This is also true if you have upgraded from before 2.2.9-3 (i.e. from
# Debian etch). See /usr/share/doc/apache2.2-common/NEWS.Debian.gz and
# README.Debian.gz

NameVirtualHost *:80
Listen 80

<IfModule mod_ssl.c>
    # If you add NameVirtualHost *:443 here, you will also have to change
    # the VirtualHost statement in /etc/apache2/sites-available/default-ssl
    # to <VirtualHost *:443>
    # Server Name Indication for SSL named virtual hosts is currently not
    # supported by MSIE on Windows XP.
    Listen 443
</IfModule>

<IfModule mod_gnutls.c>
    Listen 443
</IfModule>

**Comment by zeknox** [comment]
Add this line `NameVirtualHost *:443` next to Listen 443 and restart apache.

**Comment by nerbix** [comment]
Looks like that was the issue.  Thanks.
+1 beer.

**Comment by zeknox** [comment]
Alright, good to hear. Lets leave this ticket open as a reminder for me to post some of these details on the website in the SSL section. That way the next person wont run into this road block.

**Comment by zeknox** [comment]
Updated the install guides to include this fix.
