### ISSUE TITLE
Permissions issue? 

### ISSUE THREAD

**Issue by efensive** [pentestgeek/phishing-frenzy#155]
Been working to install this, have it semi down to the point where it appears to start loading however, throws up the following error:

EOFError in Devise::Sessions#new

Showing /var/www/phishing-frenzy/app/views/layouts/application.html.erb where line #16 raised:

end of file reached

Extracted source (around line #16):
end of file reached
Extracted source (around line #16):

13     <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
14     <![endif]-->
15   
16     <%= stylesheet_link_tag "application", controller_name %>
17     <%= javascript_include_tag "application", controller_name %>
18   
19     

Rails.root: /var/www/phishing-frenzy

![pfrenzy](https://cloud.githubusercontent.com/assets/10518706/6671898/e72f4ed2-cbde-11e4-98fb-9a3f03e24b1e.jpg)

**Comment by zeknox** [comment]
Try to refresh the permissions with a:
<pre>
$ sudo chmod -R www-data:www-data /var/www/phishing-frenzy
</pre>

Then restart the apache service and see what happens:
<pre>
$ sudo apachectl restart
</pre>

**Comment by efensive** [comment]
-R what perm 755 766 777?

**Comment by zeknox** [comment]
My bad, I meant
<pre>
$ sudo chown -R www-data:www-data /var/www/phishing-frenzy
</pre>

**Comment by efensive** [comment]
It's cool, I had chown'd already. Error still there. Entire /var/www/* is www-data:www-data that specific file is:

ls -ltha app/views/layouts/application.html.erb 
-rwxrwxrwx 1 www-data www-data 2.6K Mar 16 10:58 app/views/layouts/application.html.erb

I figured it out so will comment here in the event someone else stumbles on it. Initially there was a ownership issue on the install. The following was created:

/var/www/phishing-frenzy/tmp/cache

But no folders from there on so I created them individually:

mkdir /var/www/phishing-frenzy/tmp/cache/assets
mkdir /var/www/phishing-frenzy/tmp/cache/assets/development
mkdir /var/www/phishing-frenzy/tmp/cache/assets/development/sprockets

PF then tried to make a file via gui but errored out as well:

/var/www/phishing-frenzy/tmp/cache/assets/development/sprockets/7be9086c960bb4384c9d23a52e489f29

So I did a touch: 

touch /var/www/phishing-frenzy/tmp/cache/assets/development/sprockets/7be9086c960bb4384c9d23a52e489f29
chmod 777 /var/www/phishing-frenzy/tmp/cache/assets/development/sprockets/7be9086c960bb4384c9d23a52e489f29

Then a chown -R www-data:www-data /var/www/phishing-frenzy

I began to get those errors. I went back, deleted 7be9086c960bb4384c9d23a52e489f29 and it's working now. Sorry to bug you guys

**Comment by zeknox** [comment]
Nah, thanks for the feedback. I think I have run into this issue before as well.

**Comment by efensive** [comment]
I think on the read me I followed (http://www.phishingfrenzy.com/resources/install_ubuntu_linux) perhaps the permissions and ownerships (chown/chmod) should be re-added towards the end after all rvm stuff. I ended up having to go back at that stage, right after the: rake templates:load section

**Comment by zeknox** [comment]
Yes, I believe that is a good call out!

**Comment by efensive** [comment]
Putting this here so it's understood where I had hiccup in the event someone else goes through similar with comments after # Take note, I had to gem install rspec based on an error I got. 

cd /var/www/phishing-frenzy/
bundle install
chown -R www-data:www-data /var/www/phishing-frenzy/
chown -R www-data:www-data /etc/apache2/sites-enabled/
chmod 755 /etc/apache2/sites-enabled/
wget http://download.redis.io/releases/redis-stable.tar.gz
tar -zxvf redis-stable.tar.gz 
cd redis-stable
make
make install
cd utils/
./install_server.sh
cd ../../ 									# sidekiq gave errors since there was no log directory
mkdir log									# made log directory
bundle exec sidekiq -C config/sidekiq.yml	# ran in /var/www/phishing-frenzy/ more errors
mkdir tmp									# made missing directories
mkdir tmp/pids								# made missing directories
bundle exec sidekiq -C config/sidekiq.yml &
nano /etc/sudoers							# added statement to sudoers 
rake db:migrate
rake db:seed
rake templates:load
gem install rspec
/etc/init.d/apache2 restart
nano config/database.yml 
nano config/application.rb 
nano config/application.rb 
/etc/init.d/apache2 restart
rake db:create
nano  config/database.yml 					# fixed database issue user/pass on my end
rake db:create
nano config/routes.rb 
mv public/index_default.html .				# moved index_default.html to /var/www/
apachectl -S
nano /etc/apache2/sites-enabled/000-default # edited to add vhost
/etc/init.d/apache2 restart
nano config/application.rb 
nano config/routes.rb 
nano /etc/apache2/sites-enabled/000-default 
/etc/init.d/apache2 restart
ls /var/www/phishing-frenzy/tmp/cache			# directory did not exist had to make it
mkdir /var/www/phishing-frenzy/tmp/cache		# directory did not exist had to make it
mkdir /var/www/phishing-frenzy/tmp/cache/assets # directory did not exist had to make it
mkdir /var/www/phishing-frenzy/tmp/cache/assets/developments # directory did not exist had to make it
mkdir /var/www/phishing-frenzy/tmp/cache/assets/development # directory did not exist had to make it
mkdir /var/www/phishing-frenzy/tmp/cache/assets/development/sprockets # directory did not exist had to make it
chmod 777 /var/www/phishing-frenzy/tmp/cache
clown -R www-data:www-data /var/www/phishing-frenzy
/etc/init.d/apache2 restart
