### ISSUE TITLE
Template site was not created

### ISSUE THREAD

**Issue by RaiKarnage** [pentestgeek/phishing-frenzy#158]
Been trying to get this to work. From the documentation of PF, it was mentioned that  PF will automatically upload the attachments to its respective campaigns. However not for my case.

After launching the campaign, the site used in the phishing mail was accessible but no attachments ( index.php ) etc was not not found in the campaign folder. Could you help me on this ?

Thanks!
RaiKan

Fixed: This issue is linked to "Campaign activation error #154".

**Comment by zeknox** [comment]
Are you also receiving the message `Incomplete response received from application`?

**Comment by RaiKarnage** [comment]
Yes I was. It was fixed after I used "sudo apache2ctl graceful" instead of "apache2 reload". However, I still need to do "service apache2 reload" before being able to navigate/access the URL.

**Comment by zeknox** [comment]
You should try `sudo apache2ctl -k graceful` that one command seems to fix it from what I've seen.

**Comment by RaiKarnage** [comment]
I'll give this a try and revert back. Thanks!

**Comment by ad0nis** [comment]
Experienced this same issue on Kali linux yesterday. The 'sudo apachectl -k graceful' fix did it for me. (As a note to future readers too lazy to read the above comments, this command must be added to your PF interface as the "Apache Restart Command" under Admin > Global Settings. You must also change the command which your www-data user is allowed to execute in your /etc/sudoers file.)
