### ISSUE TITLE
Active Record Timeout

### ISSUE THREAD

**Issue by efensive** [pentestgeek/phishing-frenzy#159]
Having another issue with Active Record:

![phish](https://cloud.githubusercontent.com/assets/10518706/6715329/38b2524a-cd74-11e4-91d4-2146c3c28f18.png)

This was/is my process perhaps I am doing something wrong:

1) Click Campaign - select "New Campaign" Create a campaign
2) Fill in all options...

Whenever I click test or launch I get the following:

Incomplete response received from application

If I hit enter in the URL bar, it takes a few seconds, but goes right into the campaign I created:

http://xxx.xxx.xxx.228/campaigns/6

Logged into MySQL to double check campaign was there:

![sqlstatement](https://cloud.githubusercontent.com/assets/10518706/6715489/3142be68-cd75-11e4-8ed9-5e5faeb144ee.png)

Campaign was created in DB. I can see it after I reload (hit enter in address bar again) but whenever I create a new account, hit test, or launch a campaign, I am getting the error in the first image. Unsure if this is a timing issue, permissions issue. Sometimes the campaign will work, sometimes it won't sometimes I have to refresh the browser, etc.

**Comment by zeknox** [comment]
I've never seen this issue to be honest. I'd start with the google machine to see if this rails error yields any interesting results.

**Comment by zeknox** [comment]
Take a look at this ticket here, might assist as well. https://github.com/pentestgeek/phishing-frenzy/issues/154

**Comment by zeknox** [comment]
Any update here on the issue?

**Comment by zeknox** [comment]
Any updates here?
