### ISSUE TITLE
Emails going out but template not active

### ISSUE THREAD

**Issue by crybabycarlos** [pentestgeek/phishing-frenzy#160]
When I launch a campaign and click on the url in the email it seems to take me to the main login page instead of the template. For the phishing url and fqdn I am using the internal IP address. It is the same address I have configured in pf.conf and config/application.rb. I did notice that after adding "www-data ALL=(ALL) NOPASSWD: apachectl -k graceful" to my sudoers file I get "/etc/sudoers: syntax error near line 22" when I try to sudo. I have commented out the line for now, I'm sure I just have the syntax wrong.

**Comment by zeknox** [comment]
Show me the result of `apachectl -S`

**Comment by zeknox** [comment]
`www-data ALL=(ALL) NOPASSWD: apachectl -k graceful` should be proper syntax. If its still throwing a syntax issue maybe you can remove the `-k graceful` and allow access to `apachectl`

**Comment by crybabycarlos** [comment]
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server X.X.X.X (/etc/apache2/pf.conf:1)
         port 80 namevhost X.X.X.X (/etc/apache2/pf.conf:1)
         port 80 namevhost test-server (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost X.X.X.X (/etc/apache2/sites-enabled/4.conf:2)
                 alias X.X.X.X
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex default: dir="/var/lock/apache2" mechanism=fcntl
Mutex mpm-accept: using_defaults
Mutex watchdog-callback: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33 not_used
Group: name="www-data" id=33 not_used

**Comment by crybabycarlos** [comment]
Both options still throw up the same error when I add them to the sudoers file.

**Comment by zeknox** [comment]
Interesting... Maybe you need to find the absolute path of apachectl.  You can use `which apachectl` to find out where it is located and use the full path like `/sbin/apachectl` or wherever its located, and of course you can RTM:

http://www.sudo.ws/sudoers.man.html

**Comment by crybabycarlos** [comment]
It looks like using which to find the location worked in resolving the sudoers error, let my try to recreate the campaign.

**Comment by crybabycarlos** [comment]
Now when I try to browse to the main login page I get "Incomplete response received from application", if I comment out "www-data ALL=(ALL) NOPASSWD: /usr/sbin/apachectl -k graceful" or "www-data ALL=(ALL) NOPASSWD: /usr/sbin/apachectl" I can login again.

**Comment by zeknox** [comment]
Restart apache... The sudoers file should have no impact on getting to the login screen.

**Comment by crybabycarlos** [comment]
I restarted Apache after the change, still didn't work, when I comment out that line it seems to work fine. The only issue is I am unable to browse to my template, it's like it ignores the UID and kicks me straight to the login page.

**Comment by zeknox** [comment]
Based on the results you showed earlier, the phishing campaign 4 template should be active once you restart apache:
<pre>
port 80 namevhost X.X.X.X (/etc/apache2/sites-enabled/4.conf:2)
</pre>

It should be loaded-able on whatever is x.x.x.x

**Comment by crybabycarlos** [comment]
Well I found one problem, it looks like I copied the "sudo apachectl -k graceful" in the global settings next to "Apache Status Command" instead of the "Apache Restart Command". I have modified the "Apache Status Command" to "/etc/init.d/httpd status". Please let me know if that is incorrect. Would it matter if the x.x.x.x is the same site and port as the login page? Would I need to make the login page another port and leave 80 reserved for the template?

**Comment by zeknox** [comment]
Yes you need a separate unique FQDN from what you have PF running on.  If the campaign FQDN is the same as PF it'll never load the template and always load PF since it's defined first in the apache.conf

**Comment by crybabycarlos** [comment]
So for instance, lets say my servername in the pf.conf is "phishing.mydomain.com" and in the site url for the application.rb I put "portal.phishing.mydomain.com" in order to access the portal. When I create the campaign, would I simply need to put "test.phishing.mydomain.com" in the url and the same for the fqdn?

**Comment by crybabycarlos** [comment]
I also tried making my servername in the pf.conf "portal.phishing.mydomain.com" as well as the site url in the application.rb. That takes me to the portal just fine and I can see an index page when I go to "phishing.mydomain.com". So I attempted to create a campaign using "phishing.mydomain.com" as the url and fqdn and I still pull up the index page, I'm sure I am getting something totally wrong here.

**Comment by zeknox** [comment]
Whatever you have defined within PF.conf, for example `phishing.mydomain.com` should also be identical to what you set in the `application.rb` for SITE_URL.  This is used on the phishing sites to track clicks and other analytics.

Then on any campaign you configure the domain must be different than `phishing.mydomain.com` and you should be in good shape.

**Comment by crybabycarlos** [comment]
I had to switch the Apache restart command back to /etc/init.d/apache2 reload in the global settings because it kept giving me the incomplete error when I would make the campaign active. The template came up and tracking/reporting works, thanks so much for all your help!

**Comment by crybabycarlos** [comment]
I still run into issues when creating new campaigns, I get the main login page when I click the links. But if I reboot the server, then click the same link, it works. It's like Apache isn't truly being reloaded, have you seen this before?

**Comment by zeknox** [comment]
Did you update your sudoers file to give permissions to the new command of `/etc/init.d/apache reload` ?

**Comment by crybabycarlos** [comment]
You're the man, that was the problem. Thanks!

**Comment by zeknox** [comment]
Have fun!
