### ISSUE TITLE
Issue with new campaigns

### ISSUE THREAD

**Issue by guysmyley** [pentestgeek/phishing-frenzy#164]
Hi,
I am able to create and activate a new campaign, and send emails, but when the client clicks the URL I get page cannot be displayed.  I can browse to signature.mydomain.corp page and get the 'it works' message, but I can't get to index.php.

root@signature:/# apachectl -S
VirtualHost configuration:
wildcard NameVirtualHosts and _default_ servers:
*:80                   is a NameVirtualHost
         default server signature.mydomain.corp (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost signature.mydomain.corp (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost signature.mydomain.corp (/etc/apache2/sites-enabled/3.conf:2)
         port 80 namevhost phishingfrenzy.local (/etc/apache2/pf.conf:6)

thanks

**Comment by zeknox** [comment]
That is because you have signature.mydomain.corp configured for multiple VirtualHosts so its hitting the first config file in the list serving up whatever is defined in /etc/apache2/sites-enabled/000-default.

**Comment by guysmyley** [comment]
Thanks for the quick response. Is the fix that I use something different in the campaign?  Would I put phish.mydomain.corp in the email settings of the campaign and then create a new DNS entry? Any other changes required.

**Comment by zeknox** [comment]
Yup, that would be a sufficient workaround. Otherwise if you don't need the 000-default website you could move that file out of /etc/apache2/sites-enabled and it would then hit 3.conf and serve up your phishing site.

**Comment by guysmyley** [comment]
Works now :)  Thanks for your help.

**Comment by zeknox** [comment]
Enjoy!
