### ISSUE TITLE
Sidekiq 3.3.3 does not support Ruby 1.9, still not working

### ISSUE THREAD

**Issue by yodadada** [pentestgeek/phishing-frenzy#165]
I tried this from a closed issue:
$ \curl -sSL https://get.rvm.io | bash -s stable --ruby

But I continue to get the sale message:
Rake Aborted!
Sidekiq 3.3.3 does not support Ruby 1.9
/var/lib/gems/1.9.1/gems/sidekiq-3.3.3/lib/sidekiq.rb:3:in '<top (required)>'
/var/www/phishing-frenzy/config/applicaiton.rb:5:in '<top (required)>'
/var/www/phishing-frenzy/Rakefile:5:in '<top (required)>'

I do see this for $ rvm list
=* ruby-2.2.1 [ x86_64 ]
# => - current
# => - current && default
# => - default

What else should I do to get this installed on Kali

**Comment by b00stfr3ak** [comment]
Looks like it's still trying to pull from the 1.9.1 gems.

Did you install rvm and then download all the gems including executing bundle install

**Comment by yodadada** [comment]
I did install rvm, downloaded gems and executed bundle install again. Keep getting the same thing. Anything else I should try. BTW I used the Kali install guide because I didn't see the wiki mentioned in the video.

**Comment by zeknox** [comment]
If you run `rvm list` I would assume you only have ruby 1.9.x installed.  Install a new version of ruby with:

<pre>
$ rvm install 2.1.1
</pre>

Then if you want to use that version of ruby do:

<pre>
$ rvm use 2.1.1
</pre>

**Comment by yodadada** [comment]
I did what you show below but still get the error. Here is the whole thing using --trace


$ rake db:migrate --trace

rake aborted!

Sidekiq 3.3.3 does not support Ruby 1.9

/var/lib/gems/1.9.1/gems/sidekiq-3.3.3/lib/sidekiq.rb:3:in ‘<top (required)>’

/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:68:in ‘require’

/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:68:in ‘block (2 levels) in require’

/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:66:in ‘each’

/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:66:in ‘block in require’

/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:65:in ‘each

/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:65:in ‘require’

/usr/lib/ruby/vendor_ruby/bundler.rb:119:in ‘require’

/var/www/phishing-frenzy/config/application.rb:5:in ‘<top (required)>’

/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in ‘require’


/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in ‘require’

/var/www/phishing-frenzy/Rakefile:5:in ‘<top (required)>

/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in ‘load’

/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in ‘load_rakefile’

/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:689:in ‘raw_load_rakefile’

/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:94:in ‘block in load_rakefile’

/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in ‘standard_exception_handling’

/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:77:in ‘block in run’

/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in ‘standard_exception_hakdling’

/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in ‘run’

/var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in ‘<top (required)>’

/usr/local/bin/rake:23:in ‘load’

/usr/local/bin/rake:23:in ‘<main>’











Sent from Windows Mail





From: Brandon McCann
Sent: ‎Monday‎, ‎April‎ ‎27‎, ‎2015 ‎8‎:‎45‎ ‎AM
To: pentestgeek/phishing-frenzy
Cc: jb77n@yahoo.com





If you run rvm list I would assume you only have ruby 1.9.x installed. Install a new version of ruby with:
$ rvm install 2.1.1


Then if you want to use that version of ruby do:
$ rvm use 2.1.1

**Comment by DeathsPirate** [comment]
Have you run the source command? I needed to use something like 
`source ~/.rvm/scripts/rvm`

**Comment by zeknox** [comment]
Please show us the result of:
<pre>$ rvm list</pre>

**Comment by zeknox** [comment]
Show us the command you are running to start sidekiq please.

**Comment by zeknox** [comment]
Bump. Show us the command you are running to start sidekiq please.

**Comment by yodadada** [comment]
Was out of touch for a bit but back at it. Was using rake db:migrate when I got that. But today I reinstalled kali and tried phishing frenzy set up again. Using the install for Kali but not able to even get rvm installed. 


I am totally willing to follow a guide or procedure that can get me going. Is there another site or method I should try.


Thank you for your help,






Sent from Windows Mail





From: Brandon McCann
Sent: ‎Friday‎, ‎May‎ ‎1‎, ‎2015 ‎2‎:‎11‎ ‎PM
To: pentestgeek/phishing-frenzy
Cc: jb77n@yahoo.com





Bump. Show us the command you are running to start sidekiq please.

**Comment by zeknox** [comment]
Take a look at rvm's documentation on getting it installed. They have pretty decent docs, let me know if you have issues:

https://rvm.io/rvm/install

**Comment by Meatballs1** [comment]
Probably want a `.ruby-version` containing something like `2.1.5` in the base dir. RVM will use this to choose a specific ruby install when browsing to the dir. Just hit this myself with:

```
[1.9.3-p484] (reply_to) ben@ben-dev:~/git/phishing-frenzy$ rails generate migration add_replyto_to_email_settings
/home/ben/.rvm/gems/ruby-1.9.3-p484/gems/sidekiq-3.3.3/lib/sidekiq.rb:3:in `<top (required)>': Sidekiq 3.3.3 does not support Ruby 1.9. (RuntimeError)
	from /home/ben/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler/runtime.rb:76:in `require'
	from /home/ben/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /home/ben/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler/runtime.rb:72:in `each'
	from /home/ben/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler/runtime.rb:72:in `block in require'
	from /home/ben/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler/runtime.rb:61:in `each'
	from /home/ben/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler/runtime.rb:61:in `require'
	from /home/ben/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler.rb:131:in `require'
	from /home/ben/git/phishing-frenzy/config/application.rb:5:in `<top (required)>'
	from /home/ben/.rvm/gems/ruby-1.9.3-p484/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:146:in `require'
	from /home/ben/.rvm/gems/ruby-1.9.3-p484/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:146:in `require_application_and_environment!'
	from /home/ben/.rvm/gems/ruby-1.9.3-p484/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:133:in `generate_or_destroy'
	from /home/ben/.rvm/gems/ruby-1.9.3-p484/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:51:in `generate'
	from /home/ben/.rvm/gems/ruby-1.9.3-p484/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/ben/.rvm/gems/ruby-1.9.3-p484/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
[1.9.3-p484] (reply_to) ben@ben-dev:~/git/phishing-frenzy$ cd ..
[1.9.3-p484] (master) ben@ben-dev:~/git$ cd phishing-frenzy/
[1.9.3-p484] (reply_to) ben@ben-dev:~/git/phishing-frenzy$ ls
app     config.ru  doc      Gemfile.lock  lib      public    README.md    script  test
config  db         Gemfile  Guardfile     LICENSE  Rakefile  README.rdoc  spec    vendor
[1.9.3-p484] (reply_to) ben@ben-dev:~/git/phishing-frenzy$ cp /home/ben/git/metasploit-framework/.ruby-
.ruby-gemset   .ruby-version  
[1.9.3-p484] (reply_to) ben@ben-dev:~/git/phishing-frenzy$ cp /home/ben/git/metasploit-framework/.ruby-version .
[1.9.3-p484] (reply_to) ben@ben-dev:~/git/phishing-frenzy$ cd ..
[1.9.3-p484] (master) ben@ben-dev:~/git$ cd phishing-frenzy/
[2.1.6] (reply_to) ben@ben-dev:~/git/phishing-frenzy$ rails generate migration add_replyto_to_email_settings
```

**Comment by zeknox** [comment]
Added ruby-version file as requested @Meatballs1
