### ISSUE TITLE
Bundle Install Permission Denied

### ISSUE THREAD

**Issue by RedLee3** [pentestgeek/phishing-frenzy#166]
Going through the upgrade process, pulled files as necessary, then tried to run `bundle install`. It failed, as did `bundle install --deployment`. 

It failed on `git clone 'git://github.com/seyhunak/twitter-bootstrap-rails.git'
"/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/cache/bundler/git/twitter-bootstrap-rails-6259dce4168c7878cbf2edf620aa1d219f790c05"
--bare --no-hardlinks --quiet` with a "Permission denied" error. 

Running `sudo bundle install` shows `bundle` as an unrecognized command for sudo.

**Comment by zeknox** [comment]
Try
<pre>$ rvmsudo bundle install</pre>

**Comment by RedLee3** [comment]
That command worked and the `bundle install` ran successfully.
