### ISSUE TITLE
I am installing Phishing Frenzy in Ubuntu. Can you please help me?

### ISSUE THREAD

**Issue by puertos** [pentestgeek/phishing-frenzy#167]
I run:
apachectl -S

Results:

[Wed Apr 29 16:10:04.103877 2015] [so:warn] [pid 32245] AH01574: module passenger_module is already loaded, skipping
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server ip-172-31-35-234.ec2.internal (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost ip-172-31-35-234.ec2.internal (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost local.phishingfrenzy.com (/etc/apache2/pf.conf:2)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex watchdog-callback: using_defaults
Mutex ssl-stapling: using_defaults
Mutex ssl-cache: using_defaults
Mutex default: dir="/var/lock/apache2" mechanism=fcntl
Mutex mpm-accept: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33
Group: name="www-data" id=33

The page is Loading....

Help me, please!!!

**Comment by zeknox** [comment]
I need more info here.  You haven't told me what the specific issues are just that your installing the software...

**Comment by puertos** [comment]
The problem is that I haven't be able to set it up. I have followed all the steps from the guide through without any success.

**Comment by zeknox** [comment]
That isn't enough. Talk to me and tell me specifics of where you are at and what specifically is not working.  Is the Web UI accessible on port 80?

**Comment by puertos** [comment]
The page http://local.phishingfrenzy.com is Loading...
Sorry no speak English,
I speak Spanish.

**Comment by zeknox** [comment]
If the page is loading, login with the default credentials...

**Comment by puertos** [comment]
![captura](https://cloud.githubusercontent.com/assets/12159093/7395989/9881ca4e-ee52-11e4-8437-50b5675d4de9.JPG)

**Comment by puertos** [comment]
The server is AWS amazon.

**Comment by zeknox** [comment]
That is loading up your default apache vhost that you have configured in `/etc/apache2/sites-enabled/000-default.conf`.   You can likely disable this VHOST and then restart apache and it should load the PF web UI.

**Comment by puertos** [comment]
ServerAdmin local.phishingfrenzy.com

ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>


#SSLEngine on
 #   SSLCertificateFile /etc/apache2/ssl/pf.crt
  #  SSLCertificateKeyFile /etc/apache2/ssl/pf.key

    # !!! Be sure to point DocumentRoot to 'public'!
   # DocumentRoot /var/www/phishing-frenzy/public
    #RailsEnv development
    #<Directory /var/www/phishing-frenzy/public>
      # This relaxes Apache security settings.
     # AllowOverride all
      # MultiViews must be turned off.
      #Options -MultiViews
    #</Directory>
  #</VirtualHost>

**Comment by puertos** [comment]
Contain the 000-default.conf

**Comment by zeknox** [comment]
Move that file out of sites-enabled and restart Apache. The only config file you should care about at this time is `/etc/apache2/pf.conf`

**Comment by puertos** [comment]
I rename file. No run

**Comment by puertos** [comment]
![captura 2](https://cloud.githubusercontent.com/assets/12159093/7396247/848a32d6-ee54-11e4-9e32-aec2bedc2357.JPG)

**Comment by puertos** [comment]
My contain the pf.conf

 <VirtualHost *:80>
    ServerName http://local.phishingfrenzy.com
    # !!! Be sure to point DocumentRoot to 'public'!
    DocumentRoot /var/www/phishing-frenzy/public
    RailsEnv development
    <Directory /var/www/phishing-frenzy/public>
      # This relaxes Apache security settings.
      AllowOverride all
      # MultiViews must be turned off.
      Options -MultiViews
    </Directory>
  </VirtualHost>

**Comment by puertos** [comment]
The lines add apache2.conf

Include pf.conf



   LoadModule passenger_module /home/ubuntu/.rvm/gems/ruby-2.1.1/gems/passenger-5.0.6/buildout/apache2/mod_passenger.$
   <IfModule mod_passenger.c>
     PassengerRoot /home/ubuntu/.rvm/gems/ruby-2.1.1/gems/passenger-5.0.6
     PassengerDefaultRuby /home/ubuntu/.rvm/gems/ruby-2.1.1/wrappers/ruby
   </IfModule>

**Comment by zeknox** [comment]
Show me the result of `apachectl -S` now that you have removed the default file.  What is loading now?

**Comment by puertos** [comment]
[Wed Apr 29 16:57:13.597210 2015] [so:warn] [pid 32516] AH01574: module passenger_module is already loaded, skipping
VirtualHost configuration:
*:80                   local.phishingfrenzy.com (/etc/apache2/pf.conf:2)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex ssl-stapling: using_defaults
Mutex ssl-cache: using_defaults
Mutex default: dir="/var/lock/apache2" mechanism=fcntl
Mutex mpm-accept: using_defaults
Mutex watchdog-callback: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33 not_used
Group: name="www-data" id=33 not_used

**Comment by puertos** [comment]
Now status: Loading...

**Comment by zeknox** [comment]
Your apache configuration looks proper, it should be serving up your Phishing Frenzy Web UI when navigating to local.phishingfrenzy.com if your hosts file or DNS is configured properly.

**Comment by puertos** [comment]
My file etc/hosts:

127.0.0.1  localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

**Comment by zeknox** [comment]
Add in a line in your hosts file for PF, something like

<pre>127.0.0.1     local.phishingfrenzy.com</pre>

Replace 127.0.0.1 with the real ip address if its on a different system.

**Comment by puertos** [comment]
:dancer:

**Comment by puertos** [comment]
![captura4](https://cloud.githubusercontent.com/assets/12159093/7396647/b1876b84-ee57-11e4-8973-4a48fdb5bb63.JPG)

**Comment by zeknox** [comment]
Cool, progress here.  You have issues with your database migrations or the `config/database.yml` credentials are not proper.

**Comment by puertos** [comment]
I need run again?:

Login and create tables and permissions for phishing frenzy development mode

# mysql -u root -p
mysql> create database pf_dev;
mysql> grant all privileges on pf_dev.* to 'pf_dev'@'localhost' identified by 'password';
# cd /var/www/phishing-frenzy/
$ bundle install
If your web application fails to run because it states your missing a gem, you may need to run

# bundle install --deployment
$ rake db:migrate
$ rake db:seed
Change ownership of phishing-frenzy directory

# chown -R www-data:www-data /var/www/phishing-frenzy/
Change permissions on the upload directory

# chmod -R 755 /var/www/phishing-frenzy/public/uploads/
Change ownership of sites-enabled directory to allow Phishing Frenzy to manage virtual hosts with Apache

# chown -R www-data:www-data /etc/apache2/sites-enabled/
# chmod 755 /etc/apache2/sites-enabled/

**Comment by zeknox** [comment]
Don't know what you need to do, you've got a problem with the pf_dev account not able to login to mysql based on the errors. Do some troubleshooting, your close...

**Comment by puertos** [comment]
Thanks your service is excellent.
