### ISSUE TITLE
Unable to upload due to permission error

### ISSUE THREAD

**Issue by RedLee3** [pentestgeek/phishing-frenzy#168]
I am creating a new template and attempted to update one file. I selected it for upload, clicked "update template" and had the "We're sorry, something went wrong" message. I doubled check permissions and all is owned or has permissions like it should. 

The tail command of production.log has this: 
Errno::EACCES (Permission denied @ dir_s_mkdir - /var/www/phishing-frenzy/public/uploads/tmp/1430505322-57895-1031):
  app/controllers/templates_controller.rb:38:in `update'

**Comment by zeknox** [comment]
<pre>
# chmod -R 755 /var/www/phishing-frenzy/public/uploads/
# chown -R www-data:www-data /var/www/phishing-frenzy/
</pre>

**Comment by RedLee3** [comment]
I mistyped a command and did not give permission to the www-data user when assigning the 755 permissions. 

The order of those two commands is very important.
