### ISSUE TITLE
Cant seem to get users stored in DB

### ISSUE THREAD

**Issue by hingalatu** [pentestgeek/phishing-frenzy#171]
Hello

I have recently setup fishing frenzy and after hitting som bumps, its up, however i saw in your videos that you need to have a green status on the apache server; in my instalation the icon for apache is grey,  can yo assist me with this? and im thinking this is why i cant seem to store any users and passwords after i launch a  campaign.

Thanks

**Comment by zeknox** [comment]
Don't wory about your apache status light, its obviously working if the Web application is running.  You can modify this however in the Global Settings menu.

In terms of the credentials not storing in the database, please take a look at this tutorial here:
http://phishingfrenzy.com/resources/credential_harvesting

**Comment by hingalatu** [comment]
thanks will try this.

**Comment by hingalatu** [comment]
Followed the instructions from the lin below you provided, still not getting the info, i reduced it to the basic form snd still nothing; meaning i launch the campaign, send the email, when i click on the link from the email i get to the password form and it does what is supposed to, but when i check the report to see if i have harvested anything it still does not capture anything
Email sent?
Yes
Email Opened?
No	
Email Clicked?
No	
Password Seen?
No	
Time Visited
N/A

mysql is running, apache is running, apache ctl is working 
Please advise/

**Comment by zeknox** [comment]
http://phishingfrenzy.com/resources/troubleshooting

**Comment by hingalatu** [comment]
followed instructions and still issue persists, however when i do a manual test 
http://52.6.202.158/reports/results/?uid=ZJAHZYPB  it does register in the report 
Please advise

**Comment by zeknox** [comment]
If the stats work when you manually browse to the URL then you have an issue with the tags which are being placed on your phishing sites. Check your SITE_URL within `appplication/config.rb` and ensure it is accurate. Restart Apache if you make any changes to this file. Then make each campaign inactive, and re-active to ensure the tracking tags are updated on your phishing website.

**Comment by zeknox** [comment]
bump
