### ISSUE TITLE
Link clicked not working with https

### ISSUE THREAD

**Issue by sri-sankl** [pentestgeek/phishing-frenzy#172]
Hi,
 I have configured my server to run on https. My PF app is listening to open action and inclresing the `Opened` count. But it is not at all listening for click actions. I reffred this [SITE_URL on arbitrary port causes Link Clicked and Password Seen To Not Work]( https://github.com/pentestgeek/phishing-frenzy/issues/89), but I couldnt solve the issue.  
And when click on the link inside the intel template in my mail, It is redirecting me to the login page of my PF app.
As @zeknox mentioned [here] ( https://github.com/pentestgeek/phishing-frenzy/issues/89) ` PHP not liking your SITE_URL`. What does it mean? How to configure the PHP to listen to my app?
My SITE_URL  in `config/application.rb` is `SITE_URL = "https://my_phishing_frenzy_app.io"`

**Comment by sri-sankl** [comment]
I have removed https and tried running using http at port 80. 
All went fine until I create a first campaign.
I have created a campaing using `intel password checker` template. When make it as active and saved. My app not showing phishing frenzy login page any more. Its showing me the intel play your password game page. Whats wrong here, passanger suddenly responding eith template's index,php.
Can any one help to solve this?

**Comment by zeknox** [comment]
Show the result of `apachectl -S`

**Comment by sri-sankl** [comment]
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server ip-172-31-42-115.us-west-2.compute.internal (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost ip-172-31-42-115.us-west-2.compute.internal (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost campaign.infosecure.io (/etc/apache2/sites-enabled/1.conf:2)
                 alias campaign.infosecure.io
         port 80 namevhost campaign.infosecure.io (/etc/apache2/pf.conf:1)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex default: dir="/var/lock/apache2" mechanism=fcntl 
Mutex mpm-accept: using_defaults
Mutex watchdog-callback: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33 not_used
Group: name="www-data" id=33 not_used

**Comment by zeknox** [comment]
Well gee, of course you have a problem, you configured your phishing site on the same exact FQDN as the PF interface.

**Comment by sri-sankl** [comment]
Can you help me out on this please..
How should my FQDN and PF interface look like?

**Comment by zeknox** [comment]
You are using the name `campaign.infosecure.io` for both the PF interface and your phishing site. Change one of them. So for example make your Phishing site something like `campaign1.infosecure.io`

**Comment by sri-sankl** [comment]
Perfect...Its working now :)
I have configured my PF interface HTTPS also.
Thank you very much @zeknox .
