### ISSUE TITLE
boundle installation issue

### ISSUE THREAD

**Issue by Bressie** [pentestgeek/phishing-frenzy#174]
I try to install phisning frenzy on Ubuntu 14.04.2 but I stuck on "$ bundle install" command
below is en error... connection timed out.. Is It my firewall?

blaz@ubuntu:/var/www/phishing-frenzy$ bundle install
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Fetching git://github.com/seyhunak/twitter-bootstrap-rails.git
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection timed out

Retrying git clone 'git://github.com/seyhunak/twitter-bootstrap-rails.git' "/home/blaz/.rvm/gems/ruby-2.1.1/cache/bundler/git/twitter-bootstrap-rails-6259dce4168c7878cbf2edf620aa1d219f790c05" --bare --no-hardlinks --quiet due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/seyhunak/twitter-bootstrap-rails.git' "/home/blaz/.rvm/gems/ruby-2.1.1/cache/bundler/git/twitter-bootstrap-rails-6259dce4168c7878cbf2edf620aa1d219f790c05" --bare --no-hardlinks --quiet` in directory /var/www/phishing-frenzy has failed.
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=Connection timed out

**Comment by zeknox** [comment]
Your system doesn't have access to the Internet or the ruby gems website was down.

Brandon

**Comment by Bressie** [comment]
I do have access to the Internet. Today I am still getting the same error and I still can't ping 192.30.252.131, however I can access www.rubygems.org 

Any thoughts?

**Comment by Bressie** [comment]
sorted, port 9418 open on firewall.

**Comment by u007** [comment]
@Bressie +1
