### ISSUE TITLE
Post Docker TIps Needed

### ISSUE THREAD

**Issue by richardontheinternet** [pentestgeek/phishing-frenzy#178]
Hi sorry to raisie an issue, i've googled this up for a while now and really stuck.

I have created a Ubuntu/Docker VPS and have pulled down the docker image to the server. This is comfirmed with:
 $ root@PhishingPortal:/# docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
b00stfr3ak/ubuntu-phishingfrenzy   latest              3863078923b4        9 weeks ago         1.24 GB

I have kicked the docker build off with:
$ sudo docker run -d -p 80:80 b00stfr3ak/ubuntu-phishingfrenzy

Don't forget I am SSH'd onto this. So when I hit up my VPS by it's external IP address from an other machine I get the ubuntu/Apache Default 'It Works' landing page on Port 80. I can't seem to find the app.

I have ran:
$ sudo netstat -antp 

Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      992/sshd        
tcp        0    384 XXX.XX.122.117:22       XX.XX.248.245:57737     ESTABLISHED 1126/0          
tcp6       0      0 :::22                   :::*                    LISTEN      992/sshd        
tcp6       0      0 :::80                   :::*                    LISTEN      1280/docker-proxy
tcp6       0      0 :::81                   :::*                    LISTEN      1961/docker-proxy
(IP redacted)

Can you please tell me the few steps I will need to be able to access the GUI/APP EXTERNALLY. 

Thanks in advance and I am sorry again just really want to try this out.

**Comment by b00stfr3ak** [comment]
Hello,

If it's the default docker image you'll need to add phishingfrenzy.local to
your hosts file.

**Comment by zeknox** [comment]
Bump, any updates here?

**Comment by richardontheinternet** [comment]
Sorry guys, this didn't work. 
I'm on a digitalocean VPS running Ubuntu 14.04 and docker. When I navigate to the hosts file there is the notice that this file isn't going to be saved due to something about a template (I'm afk) it suggests editing another file, that isn't present on my box.

I know Apache is up due to the default landing page but no 'service Apache2' on it at all? 

I think I have two issues here, I'm going to build this again from and resolve my own webserver issues (like not having a /var/www folder ??? ) and then edit the hosts file as previously suggested.

Can I confirm, from a standard docker image I am simply adding the line:

127.0.0.1 phishingfrenzy.local 

To my existing /etc/hosts file? What do I do with the current local host entry already there?

**Comment by zeknox** [comment]
Yes, the docker install should setup the application and deploy it all properly. The /etc/hosts file is simply to map the FQDN to an ip address. The proper solution would be to use DNS to map the english address to the numeric address.

Take a look at `apachectl -S` and this will tell you how the virtualhosts are configured within apache and what FQDN they are listening on.

**Comment by zeknox** [comment]
bump

**Comment by zeknox** [comment]
bump

**Comment by richardontheinternet** [comment]
This just isn't happening for me. I have tried several ways. Started from scratch several times. Hosts file reverts back every time. The Kali method also flunks out.

Not that I'm being a cry baby because I lack the knowledge to do this but when you launch that docker image it should just be there? Any further modification defeats the point of a docker install. Whether on an VPS or local build why wouldn't you want the web interface to be on 127.0.0.1?

**Comment by zeknox** [comment]
So using the /etc/hosts file is quite janky. The more elegant solution is to run DNS and properly route the IP address to the IP of the PF box.  This way you don't need to make any modifications to the PF docker image.

PF should be configured with a public IP address, so using a public DNS service you can add A records to route your FQDN to the public IP address of PF, and you should be able to login to the admin interface and ready to start creating phishing campaigns.

**Comment by Meatballs1** [comment]
I have been playing around with this. 

I have moved pf to an available site and used a2ensite and a2dissite to disable the default site.

When you connect to the default IP you should hit phishing frenzy, rather than have to force a virtual host. 

https://github.com/Meatballs1/ubuntu-phishingfrenzy

**Comment by zeknox** [comment]
@Meatballs1 that is a really good callout. Thanks for the addition and comments here. We should really look to get this functionality moved into the standard docker install.

**Comment by Meatballs1** [comment]
I'm hitting so many problems with rubygems and 503 errors at the moment though. Causes docker to bomb out :|

**Comment by richardontheinternet** [comment]
So I just go and clone the version meatballs has? Point my browser at the external IP and done... If this is true, you sir have become another internet star.

**Comment by richardontheinternet** [comment]
Meatballs you've just made a change to a docker file in your GitHub also... Does this mean I can somehow pull a new docker build rather than reinstall.

**Comment by Meatballs1** [comment]
I'm just learning how to docker at the mo, you can build from my github:

`sudo docker build -t="phishingfrenzy"  github.com/Meatballs1ubuntu-phishingfrenzy`

But I haven't tried the latest version yet... It should pick up cached images, but I have been playing around with it a fair amount so it may rebuild pretty much from the start.

**Comment by richardontheinternet** [comment]
Thanks for this. @rfdevere @antisocial_eng hit me up!

**Comment by JC-SoCal** [comment]
just an fyi meatballs, ur git link is missing a slash
sudo docker build -t="phishingfrenzy" github.com/Meatballs1/ubuntu-phishingfrenzy

**Comment by Meatballs1** [comment]
Good spot, fixed.

**Comment by Meatballs1** [comment]
I have added additional access controllers to the default site to allow access only to local subnets/127.0.0.1. Otherwise someone browsing to the IP/URL when no virtualhost is available would hit the PF admin page.

**Comment by richardontheinternet** [comment]
Great stuff. So on a fresh VPS what way would you install?

**Comment by Meatballs1** [comment]
I've moved away from Docker at the moment, but I'm playing around a lot which makes having to go through docker to make changes a pain.

**Comment by richardontheinternet** [comment]
No worries, thanks so much for the changes, i'll build from your github.

**Comment by n0x00** [comment]
alright, I gave a few hours to this this morning ... and I only read the install guide (instead of the open issues) ... is there any confidence in the docker install yet ? any success stories ? any updates to the installation guide from new box to looking at the login screen ? - sank youuuuu

**Comment by richardontheinternet** [comment]
Doesn't seem to be, from my own experience, installing Kali as a host, then git clone works flawlessly. Avoid the Docker headache!

**Comment by n0x00** [comment]
Thanks Richard, I'll bust out an EC2 Kali, looks like the guides should be *work in progress* then apart from the one's that work eh :)
