### ISSUE TITLE
Problems getting PF off the ground

### ISSUE THREAD

**Issue by Alphann** [pentestgeek/phishing-frenzy#179]
I've followed the Kali install instructions with only a few minor kinks along the way (version differences and whatnot) but Im still having problems accessing PF. My apache web server is up but I cant access the PF portal, just stuck in endless loading. 
Ive also had some problems running the rakes as of late, getting an error like:

rake aborted!
cannot load such file -- bundler/setup
/var/www/phishing-frenzy/config/boot.rb:6:in `<top (required)>'
/var/www/phishing-frenzy/config/application.rb:1:in `<top (required)>'
/var/www/phishing-frenzy/Rakefile:5:in `<top (required)>'

I don't know if it's becuase of version differences or something like that but any help would be appreciated

**Comment by zeknox** [comment]
`cannot load such file -- bundler/setup`

This seems like your missing the bundler gem.  Try something like `gem install bundler` to see if that assists with your rake task crash.

As for the web interface not showing up, use `apachectl -S` to determine if the VHOSTs have been configured properly to server up your PF interface.

**Comment by Alphann** [comment]
The gem install bundler worked and now Ive completed all the rakes, thank you.

As for apache, running apachectl -S gives me

VirtualHost configuration:
wildcard NameVirtualHosts and _default_ servers:
*:80                   is a NameVirtualHost
         default server localhost (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost localhost (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost portal.phishing-frenzy.com (/etc/apache2/pf.conf:6)
Syntax OK

**Comment by zeknox** [comment]
Alright, so what this output tells us is that if you use the IP address of the PF box you will be served up with the default website defined at /etc/apache2/sites-enabled/000-default.

The only way that your PF interface is going to be served up is if you hit it on the FQDN of portal.phishing-frenzy.com. So what the means is you either need to setup DNS to route you to the ip address or you need to edit your hosts file you redirect you.

**Comment by Alphann** [comment]
Which file in particular would I be looking to edit?
And if it's not too much to ask, what exactly would I be looking to add/edit?

**Comment by zeknox** [comment]
Lets say the IP address of your PF box is 192.168.1.250.  If that is the case on your system (assuming mac or linux) you would edit your `/etc/hosts` file to something like so:

<pre>
192.168.1.250	 portal.phishing-frenzy.com
</pre>

This means when your local system tries to navigate to portal.phishing-frenzy.com the hosts file will redirect you to the IP address. Once you hit the IP address apache will see the request for portal.phishing-frenzy.com and serve up the proper VirtualHost.

**Comment by Alphann** [comment]
Where can I find the IP of my PF box?

**Comment by zeknox** [comment]
I'm sorry but if you cannot find the IP address of the PF box, you probably shouldn't be using this tool...

**Comment by Alphann** [comment]
Sorry, I figured it out, added the IP to the hosts file and was able to log in to PF, thanks for your help and VERY timely responses.

**Comment by zeknox** [comment]
Awesome, enjoy!
