### ISSUE TITLE
Campaign test sends email but link in email not working

### ISSUE THREAD

**Issue by Alphann** [pentestgeek/phishing-frenzy#180]
I have phishing frenzy installed on kali and it appears to be working.
I am using the efax template for testing and I sent a test to my email. The test came over fine but when I click the link in the test efax email I just get 'This page can't be displayed'.
My phishing url is campaign.test.co
My FQDN is campaign1.test.co
When I run apachectl -S I get:
VirtualHost configuration:
wildcard NameVirtualHosts and _default_ servers:
*:80                   is a NameVirtualHost
         default server localhost (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost localhost (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost portal.phishing-frenzy.com (/etc/apache2/pf.conf:6)
Syntax OK

Not sure what I missed or did wrong. Can you help.
Thanks,

**Comment by zeknox** [comment]
The campaign needs to be active in order to serve up the phishing site. You can either manually make the campaign active within the campaign settings or launch the campaign.

http://phishingfrenzy.com/resources/getting_started

Test email does just that, only sends the email that you have tied to the campaign, but it does not make the phishing website active.

**Comment by Alphann** [comment]
I just made it active and got the same result.

**Comment by zeknox** [comment]
Post the result of `apachectl -S` now that the campaign is active.

**Comment by Alphann** [comment]
VirtualHost configuration:
wildcard NameVirtualHosts and _default_ servers:
*:80                   is a NameVirtualHost
         default server localhost (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost localhost (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost campaign1.co (/etc/apache2/sites-enabled/1.conf:2)
         port 80 namevhost portal.phishing-frenzy.com (/etc/apache2/pf.conf:6)
Syntax OK

**Comment by zeknox** [comment]
Looks like its operating properly.  Your phishing site on campaign 1 is available on the fully qualified domain name of:  campaign1.co

**Comment by Alphann** [comment]
I still get 'This page can't be displayed' when I click the link in the email. I've tried it as a test and campaign to my email.

**Comment by zeknox** [comment]
campaign1.co is not really a fully qualified domain name. You would need to run a DNS service to route this FQDN to the proper IP address or edit your hosts file to route properly. Just like we discussed with the PF interface when you were having issues.

**Comment by Alphann** [comment]
WOW, I should have thought of that. I will update the DNS server and see if that solves it.

**Comment by zeknox** [comment]
Your apache configuration tells you everything you need to know:
<pre>port 80 namevhost campaign1.co (/etc/apache2/sites-enabled/1.conf:2)</pre>

This tells us the phishing site is only live on campaign1.co name.

**Comment by zeknox** [comment]
bump

**Comment by Alphann** [comment]
Thank you, I was able to solve the problem of the link not working, but now Im facing a new issue.
My campaigns are tracking every stat other than password seen, for multiple copied site login pages and even my own fake login pages that I've made.

**Comment by zeknox** [comment]
Take a look here for credential harvesting how to and explanation of how it works:
http://phishingfrenzy.com/resources/credential_harvesting

If you still have issues create a separate ticket for the separate issue. Also search past tickets on this repo, I believe that has been addressed previously.
