### ISSUE TITLE
Disable storage of passwords

### ISSUE THREAD

**Issue by ryman1** [pentestgeek/phishing-frenzy#181]
Would it be possible to add an option for not storing passwords for a particular campaign? Instead, PF would just gather all the other normal statistics. The intended use is for engagements that are not full-on pen tests and are just intended for gather stats on end user awareness.

**Comment by zeknox** [comment]
Yeah this could certainly be an addition to the framework. I would imagine that we could add a boolean attribute to the `Campaign` model that is used to determine if credentials are stored or not.

**Comment by Meatballs1** [comment]
Best to add javascript in the form to replace the password with COLLECTED or something. This means that the password is never transmitted etc. :)

**Comment by zeknox** [comment]
What will likely end up happening is updating the PHP tags that are used for tracking and sending credentials to have some additional code added for something like an input with the name of `PasswordTracking` will not actually submit the password, but still track that a password was entered.

JS could also certainly be leveraged, but this is up to the user to tweak the HTML website to their needs.

**Comment by UnicornPwned** [comment]
It would be nice if it replaced submitted password info with representative characters. For Example, an uppercase letter would be represented with an uppercase L. A lowercase letter with a lowercase l. A number with a lowercase n and a special character with a lowercase s. 

For example, A password entered PassWord12$ would be submitted and stored as LlllLlllnns. This would prevent any actual password data being passed and stored, but could give us a good idea wither or not they are entering garbage data vs what appears to be legitimate data.

**Comment by zeknox** [comment]
@UnicornPwned that's a pretty stellar idea

**Comment by UnicornPwned** [comment]
For those interested, here is what I have currently setup. I use the below javascript function to replace the password with representative characters.

    <script language="javascript">
    function stripPassword() {
        var password = document.getElementById("PasswordForm").value;
        password = password.replace(/[A-Z]/g, 'L');
        password = password.replace(/[a-z]/g, 'l');
        password = password.replace(/[&\/\\#,+()$~%.'":*?<!@>{}]/g,'s');
        password = password.replace(/[0-9]/g, 'n');
        safePassword = password;
        document.getElementById("PasswordForm").value = safePassword;
    };
    </script>

I then use onblur="stripPassword()" in the password input type. This executes the function when the user clicks out of the password text box.
