### ISSUE TITLE
Problem harvesting passwords

### ISSUE THREAD

**Issue by Alphann** [pentestgeek/phishing-frenzy#182]
Whenever I run a campaign, it will track everything including email sent, opened, and link clicked but it won't harvest any passwords entered. 
I've been mostly cloning website logins for my campaigns and have checked the code to make sure they have correctly formatted password forms and I even tried using the exact code used in the "Creating a New Template" video (https://www.youtube.com/watch?t=153&v=5lN3lvbkuXk)
but no luck still,

**Comment by zeknox** [comment]
You likely have an issue with your HTML form if all other tracking analytics are working properly. You're likely gonna need to show some HTML source code of your form which includes the input fields for username and password.

**Comment by Alphann** [comment]
Heres some of the code from a facebook template i made

 <section class="login-form-wrap">
  <h1>Facebook</h1>
  <form class="login-form" action="#" action="#">
    <label>
      <input type="email" name="email" required placeholder="Email">
    </label>
    <label>
      <input type="password" name="PasswordForm" required placeholder="Password">
    </label>
    <input type="submit" value="Login">
  </form>
  <h5><a href="#">Forgot </a></h5>
</section>

**Comment by Alphann** [comment]
<form class="login-form" action="#" action="#">
    <label>
      <input type="email" name="email" required placeholder="Email">
    </label>
    <label>
      <input type="password" name="PasswordForm" required placeholder="Password">
    </label>
    <input type="submit" value="Login">
  </form>

**Comment by Alphann** [comment]
Heres some of the code for a facebook template I made

#    <section class="login-form-wrap">
#  <h1>Facebook</h1>
#  <form class="login-form" action="#" action="#">
#    <label>
#      <input type="email" name="email" required placeholder="Email">
#    </label>
#    <label>
#      <input type="password" name="PasswordForm" required placeholder="Password">
#    </label>
#    <input type="submit" value="Login">
#      </form>
#  <h5><a href="#">Forgot </a></h5>
#      </section>

**Comment by Alphann** [comment]
```html
  <body>
    <section class="login-form-wrap">
  <h1>Facebook</h1>
  <form class="login-form" action="#" action="#">
    /<label>
      <input type="email" name="email" required placeholder="Email">
    </label>
    <label>
      <input type="password" name="PasswordForm" required placeholder="Password">
    </label>
    <input type="submit" value="Login">
  </form>
  <h5><a href="#">Forgot </a></h5>
</section>
    ```

**Comment by zeknox** [comment]
So the action is also very important. You need to make sure that you are passing in the specific UID parameter to the next page that you're redirecting to so that when you land on it the PHP tags will automatically see the UID, password and store it in the DB.

**Comment by zeknox** [comment]
any update here. I would like to see some more code related to you `action=...` portion of the form.

**Comment by zeknox** [comment]
Your issue is likely related to not passing the UID onto the action page so that the credentials can be logged, please re-open if you still have issues.
