### ISSUE TITLE
Hardcoded Rails Secret

### ISSUE THREAD

**Issue by Meatballs1** [pentestgeek/phishing-frenzy#183]
http://daniel.fone.net.nz/blog/2013/05/20/a-better-way-to-manage-the-rails-secret-token/

**Comment by zeknox** [comment]
Good call, I've been meaning to get around to this. Thanks for the motivation boost.

**Comment by zeknox** [comment]
Documentation updated as well:  https://phishingfrenzy.com/resources/rails_production_mode
