### ISSUE TITLE
Feature Request: Log Pages

### ISSUE THREAD

**Issue by Meatballs1** [pentestgeek/phishing-frenzy#190]
It would be nice to have a couple of views that show logfiles. Gitlab does this really well:

![image](https://cloud.githubusercontent.com/assets/1854557/8685734/9df74e6a-2a78-11e5-887e-af01a79a6035.png)

It also has a decent background jobs tracker for Sidekiq:

![image](https://cloud.githubusercontent.com/assets/1854557/8685748/bd2d45be-2a78-11e5-95f2-98079aea0ccd.png)

I think this is basically just mounting ```mount Sidekiq::Web, at: '/admin/sidekiq', as: :sidekiq``` in routes.rb

**Comment by Meatballs1** [comment]
Ah I see now sidekiq is mounted on /sidekiq :)

**Comment by zeknox** [comment]
Yup, but I'll work on getting a link to the navbar as well for ease of navigation to access that interface.
