### ISSUE TITLE
Template links are hardcoded to http://

### ISSUE THREAD

**Issue by Meatballs1** [pentestgeek/phishing-frenzy#191]
e.g. `<a href="http://#{url}">Click here to view the message</a><br>`

We should have users define the full URL value and prompt them for http(s)?

**Comment by zeknox** [comment]
Maybe... not sold on the idea quite yet... you want to change the phishing URL to include the full http(s)://fqdn it sounds like.

**Comment by Meatballs1** [comment]
Also what happens when you spin up SSL template website? Surely the http:// link would be invalid unless you are listening on both ports by default?

**Comment by zeknox** [comment]
If the user is going to run a phishing gig over HTTPS, they should just update the template. However, if they do not update the template and hit the Phishing URL over HTTP, they will simply be redirected to HTTPS if the campaign is configured to use SSL (which PF fully supports through the Web UI with valid SSL certificates).

Here is the VHOST that gets configured for a Phishing campaign configured with SSL:
https://github.com/pentestgeek/phishing-frenzy/blob/master/app/views/campaigns/virtual_host_ssl.txt.erb#L4

**Comment by Meatballs1** [comment]
There is some inconsistencies around the use of the protocol and its not always clear where you should define with or without it. e.g. SITE_URL is used for the tracking image link, and also the index.php calback code. I dont think these honour the SSL settings. 

Its not always obvious what the generated URL will be like :)

**Comment by zeknox** [comment]
I plan to move the SITE_URL to the global settings menu. Perhaps at this time we can better define where the protocol belongs and firm up the consistencies.

**Comment by zeknox** [comment]
Fixed with PR #203
