### ISSUE TITLE
Tracking is linked to the base rails site.

### ISSUE THREAD

**Issue by Meatballs1** [pentestgeek/phishing-frenzy#197]
As I understand it, we use some PHP in each index.php (run on Apache) to pass the UID to the internal  /report/results/ page (Rails). 

For email tracking however the link is generated to point to Rails from `SITE_URL`  instead of the Apache virtualhost page. This means to track this we need to expose our Rails interface to the internet. This isn't ideal as we dont want people browsing to say, the IP address, and hitting the phishing frenzy landing page (depending on the configuration!)

Ideally each campaign should deploy a `tracking_image.php?UID=` which uses the same mechanism as the index.php to forward the details to rails. Rails should stay unexposed to the internet and would ideally be configurable itself with an access list of IPs (e.g. a mgmt range 10.0.0.0/24).

I tried resolving this with ProxyPass to pass /reports/image/ to Rails. However I have a `Deny from all, Allow from 10.0.0.0/24` rule and Apache still recognises this request as external and blocks it.

My configuration is slightly different than default as I configured PF as 000-default so I didn't have to set a VirtualHost to access the site. However the access control model shouldn't just be based just on VirtualHosts... And obviously we dont want customers to do an investigation and spot the PF login page.

**Comment by Meatballs1** [comment]
I struggled to find how you do access control with Apache and Phusion, but it looks like you can just do

```
    <Location /reports/>
                Order allow,deny
                Allow from all
                Require all granted
        </Location>
```

To allow the ProxyPass solution to work.

**Comment by Meatballs1** [comment]
Potentially going for Apache ProxyPass means you could remove the requirement for external PHP scripting. This is an easy solution for the email image check as the display is constant.

For the initial UID registering and password registering we could use the reports controller (or another controller as I think collection and reporting should be seperate concerns?.

This would have actions like:

* TrackImage => /track/image?UID=
* TrackClick => /track/Click?UID=
* TrackPassword /track/Password?Username=&Password=

You could have configurable names for these in the campaign/template. These would be used for the ProxyPass settings e.g.:

`ProxyPass /visit http://127.0.0.1/track/image`

The view for each of these would basically be a 'ProxyView'. They could contain some boilerplate view, but if the user has defined a password view, an image view, or a click view it would just render that page instead. 

Just some thoughts, I had a long commute to ponder :)

**Comment by zeknox** [comment]
So I have mixed feelings on this topic.  By forcing a proxy for collecting stats like this, you are now limited to hosting your phishing sites on the PF server.  Currently the websites can be hosted anywhere, and the PHP tags can be added to communicate stats and data to the PF collection API

**Comment by Meatballs1** [comment]
You can ProxyPass to a remote URL?

**Comment by zeknox** [comment]
Not sure tbh, haven't looked into ProxyPass so would need to get up to speed
