### ISSUE TITLE
Mail message ID contains system hostname

### ISSUE THREAD

**Issue by Meatballs1** [pentestgeek/phishing-frenzy#209]
Looks like ruby's Mail library creates a random identifier and appends @SYSTEM_NAME.mail

Would be good to anonymize this :)

**Comment by Meatballs1** [comment]
This may not be system hostname, it may come from the VirtualHost `ServerName` field... 

Mine are identical so hard to tell :)

**Comment by Meatballs1** [comment]
```
    def generate_message_id
      "<#{Mail.random_tag}@#{::Socket.gethostname}.mail>"
    end
```

We can override this probably with code like

mail.message_id = "<#{Mail.random_tag}@something.mail>"

**Comment by Meatballs1** [comment]
Example of current output:

```
sudo python -m smtpd -n -c DebuggingServer localhost:1025 |grep dev
Message-ID: <55ad48f784f7b_134c3ad561c1016c8@ben-dev.mail>
  <img src="cid:55ad48f77b999_134c3ad561c101444@ben-dev.mail" />
Content-ID: <55ad48f77b999_134c3ad561c101444@ben-dev.mail>
```

**Comment by zeknox** [comment]
Yes, I really like this idea. We could make the `#{something.mail}` dynamic and configureable within the Global Settings. Or just randomly come up with some random FQDN.  Lots of possibilities.

**Comment by Meatballs1** [comment]
It doesn't look like `SMTP Domain` is being used? This looks perfect for the job?

**Comment by zeknox** [comment]
Yeah I don't believe that SMTP domain is being used anywhere currently.  Just being collected from the Campaign#edit Form under SMTP Settings.
