### ISSUE TITLE
Install error at passenger and apache

### ISSUE THREAD

**Issue by MaryGrosholz** [pentestgeek/phishing-frenzy#213]
Installing on Kali.
After installing passenger and running this command I get a libs error as mentioned in the instructions.
When I run "apt-get install apache2-threaded-dev libapr1-dev libaprutil1-dev" I get an unmet dependencies error.  
I have tried apt-get clean, update, you name it.
Do you have a work around or alternate method to get the libs installed?

**Comment by zeknox** [comment]
Sounds like your package manager and or sources.list might be borked. This is not a PF specific issue but checkout some articles like so:
http://askubuntu.com/questions/140246/how-do-i-resolve-unmet-dependencies-after-adding-a-ppa

**Comment by zeknox** [comment]
Bump
