### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by stathmarxis** [pentestgeek/phishing-frenzy#214]
i have changed the hostname in config/application.rb with this "http://portal.phishingfrenzy.com" ,i have started the apache but when i tried to open the link in my browser i got a message  LOADING... (in htmcode)and nothing show.Plzzzz can you help me  i am very close.

**Comment by zeknox** [comment]
Edit your hosts file to point portal.phishingfrenzy.com to the IP address of your PF box.

**Comment by stathmarxis** [comment]
How to do that?

**Comment by stathmarxis** [comment]
VirtualHost configuration:
wildcard NameVirtualHosts and _default_ servers:
*:80                   is a NameVirtualHost
         default server kali.kali (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost kali.kali (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost portal.phishingfrenzy.com (/etc/apache2/pf.conf:6)
Syntax OK

check this whats my fault?

**Comment by zeknox** [comment]
Edit your hosts file: http://community.linuxmint.com/tutorial/view/159

You need to point `portal.phishingfrenzy.com` to the IP address of your PF system.

**Comment by stathmarxis** [comment]
thnxxxxx bro really thnx!!!!!!!!
one last question when i reboot i will do this to start it again
# bundle exec sidekiq -C config/sidekiq.yml
# service sidekiq start
# apachectl start

**Comment by stathmarxis** [comment]
thnx bro really thnx!!!!!!!!!!!! it works!
one last question when i reboot i do this to start it again
1)bundle exec sidekiq -C config/sidekiq.yml
2)service sidekiq start
3)apachectl start

**Comment by zeknox** [comment]
This will start the sidekiq service which is used to background the sending of emails
```bundle exec sidekiq -C config/sidekiq.yml```

This should not be needed as the line above starts sidekiq
```service sidekiq start```

Yes you need to make sure apache is running, it probably will auto start on reboot
