### ISSUE TITLE
Send Error Problem

### ISSUE THREAD

**Issue by stathmarxis** [pentestgeek/phishing-frenzy#216]
I created new campaign i filled on all text field but when i press the launch button i not got any message confirmation.Also i checked at my email box and nothing  has arrived. How to solve this i am a bit confused

**Comment by zeknox** [comment]
Check to make sure you have targets showing in the campaign options page. Also always take a look at your "Recent Blasts" section of the Campaign Options. This will show you the result of every email sent.

**Comment by stathmarxis** [comment]
when i loaded the campaign the radio button is green only in active section and no in email section. Maybe there  the problem is?

**Comment by zeknox** [comment]
You have not added in any targets to the campaign.

**Comment by zeknox** [comment]
Please review the appropriate documentation on how to enter targets into a campaign:
http://phishingfrenzy.com/resources/getting_started#importing_targets

**Comment by stathmarxis** [comment]
#touch /etc/apache2/httpd.conf
#chown www-data:www-data /etc/apache2/httpd.conf
 and at sudoers i have this
#www-data ALL=(ALL) NOPASSWD: /etc/init.d/apache2 reload
I dont know what else to do and i checked your documentation

**Comment by zeknox** [comment]
Why are you posting this stuff, this has nothing to do with the symptoms you've explained. I told you what needs to be done. Go add targets into the campaign options page.  You should have a number next to the `Targets (1)` text with a link to view targets imported.

**Comment by stathmarxis** [comment]
I created new campaign and i managed i go to reports and i show the message
which has sent BUT when i open my mailbox(gmail) I cant see the message.
Why this happens?

2015-07-24 17:47 GMT+03:00 Brandon McCann <notifications@github.com>:

**Comment by zeknox** [comment]
Have you configured PF to send emails in the background?  Perhaps your Sidekiq and Redis instances are not running to deliver the email, perhaps its getting caught in the SPAM filters, perhaps you should fire up wireshark or tcpdump on whatever port your sending on to further debug...

**Comment by stathmarxis** [comment]
if you mean the Background Email checkbox has been clicked and also Redis and sidek runs

**Comment by zeknox** [comment]
Look at the SMTP logs of your SMTP service that you send through then... follow the path of where the email is going...

**Comment by stathmarxis** [comment]
534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbsbY 
i got this message at SMTP logs

**Comment by stathmarxis** [comment]
I managed to Solved the problem,for all THOSE want to ship email via gmail do this in your spam acount:

Gmail has some security features that have to be enabled/disabled 1 - Inside your gmail account go to Settings > Forwarding and POP/IMAP and enable the protocols(s) that you wish to use

2 - Enable access of less secure apps https://www.google.com/settings/security/lesssecureapps

**Comment by zeknox** [comment]
Thank you for sharing, I will work on getting this added to the troubleshooting section of the website.

**Comment by zeknox** [comment]
These details have been added to the troubleshooting section of the website:
http://phishingfrenzy.com/resources/troubleshooting
