### ISSUE TITLE
Partially working, but phishing URL landing site is blank, uid present - but doesn't count lander...

### ISSUE THREAD

**Issue by amade2** [pentestgeek/phishing-frenzy#217]
Hey Zeknox.

First of all: mad respect for your work and phishing-frenzy!  Great concept and package, however, I cannot get the last few items in line to get it off the ground in full functionality. I suspect that I am overthinking it and missing some minute detail or config... 

Current issue and most functionality is up on a Kali vm and I have access to the portal and send out emails successfully. However, when I click on the email, I get:

Index of /
[ICO]	Name	Last modified	Size	Description
Apache/2.2.22 (Debian) Server at ilak.xyxzyxz.com Port 80

Under reports -> raw apache logs, I was seeing the UID and GET request, but it does not get counted and it seems that whatever I try to do to fix it have taken me backwards, because now the UID isn't even showing on clicks anymore...

It is the linkedin template that I am using for a survey to see how many people in a small office (permission given and asked to be phished actually, 9 people total). So my plan was to count how many of them click and then simply redirect them to linkedin without harvesting or attempting to harvest their credentials. In other words, establsih a baseline...

Here is what my apachectl -S reads (modified and anonymized to protect the innocent):

===
Warning: DocumentRoot [/var/www/phishing-frenzy/public] does not exist
[Tue Jul 28 17:39:18 2015] [error] (EAI 2)Name or service not known: Could not resolve host name VirtualHost -- ignoring!
VirtualHost configuration:
wildcard NameVirtualHosts and _default_ servers:
*:443                  kali.xyzzyx.lan (/etc/apache2/sites-enabled/000-default-ssl:2)
*:80                   is a NameVirtualHost
         default server phishing-frenzy.com (/etc/apache2/pf.conf:8)
         port 80 namevhost phishing-frenzy.com (/etc/apache2/pf.conf:8)
         port 80 namevhost kali.xyzzyx.lan (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost ilak.xyzzyx.com (/etc/apache2/sites-enabled/1.conf:2)
         port 80 namevhost portal.phishingfrenzy.com (/etc/apache2/sites-enabled/100-pf:6)
         port 80 namevhost ilak.xyzzyx.com (/etc/apache2/sites-enabled/2.conf:2)
Syntax OK
===

Maybe I am confusing myself having tried to install phishing frenzy on 3 platfroms and lost my place and sanity in the process, but I could swear it's the first time I see it here... 

Any and all input is appreciated.

**Comment by amade2** [comment]
Update ---

Warning: DocumentRoot [/var/www/phishing-frenzy/public] does not exist
[Tue Jul 28 17:39:18 2015] errorName or service not known: Could not resolve host name VirtualHost -- ignoring!

Was fixed by removing the - dash from the name... I believe that I may have started to try and match "-" and "no -" instances of phishing-frenzy and phishingfrenzy. I was doing this when it was not working out of the box after several hours of troubleshooting. Make matters worse, two of my mail clients I use to click and test the links started to auto block the links...

**Comment by zeknox** [comment]
<pre>ilak.xyzdomain.com/?uid=KMRXNWZV</pre>

This URL example above is perfectly normal and fine.  What's happening here is that you define a default index page within the template page so you don't actually need the specific page like `index.php`.  Apache knows that when you hit the website it will serve up whatever file is defined as your index page.

base64 encoded email addresses are a thing of the past. Now days we use a hash which is stored in the db for each target so when we see this UID hash we are able to correlate the metrics to a specific target.

**Comment by amade2** [comment]
Thanks for your response. 

I think I am getting it.

Upon further tinkering last night, got the landing page working by assigning a different subdomains to diffferent campaigns and then entering them into their respective settings folders. However the partially working demo impressed my friends and it is becoming a group project to get it up and running. :-) 

Here is my new apachectl -S

[Thu Jul 30 10:54:22 2015] [error] (EAI 2)Name or service not known: Could not resolve host name VirtualHost -- ignoring!
VirtualHost configuration:
wildcard NameVirtualHosts and _default_ servers:
*:443                  kali.aci.lan (/etc/apache2/sites-enabled/000-default-ssl:2)
*:80                   is a NameVirtualHost
         default server phishing-frenzy.com (/etc/apache2/pf.conf:6)
         port 80 namevhost phishing-frenzy.com (/etc/apache2/pf.conf:6)
         port 80 namevhost kali.xyzdomain.lan (/etc/apache2/sites-enabled/000-default:1)
         port 80 namevhost ilak.xyzdomain.com (/etc/apache2/sites-enabled/1.conf:2)
         port 80 namevhost portal.phishingfrenzy.com (/etc/apache2/sites-enabled/100-pf:6)
         port 80 namevhost ilak2.xyzdomain.com (/etc/apache2/sites-enabled/2.conf:2)
Syntax OK

**Comment by amade2** [comment]
By the way, are you open to having more templates available? I could make some generic, non-trademark/copyright infringing ones after the events in vegas...

**Comment by Meatballs1** [comment]
Which logs are you looking at? If you are seeing the UID in /var/log/apache2/access.log then the user isn't going to the correct VirtualHost configuration.

if you are seeing them in /var/www/phishing-frenzy/public/logs (or something like this) then it should be going via the correct VirtualHost config...

**Comment by amade2** [comment]
Hey Meatballs, thanks for your response.

I get the results from:

 /var/www/phishingfrenzy/log/www-campaign-1-access.log

**Comment by zeknox** [comment]
We are always open to new templates, please re-open if this is unresolved!
