### ISSUE TITLE
Refresh problem

### ISSUE THREAD

**Issue by stathmarxis** [pentestgeek/phishing-frenzy#218]
i would like to know why when i refreshes page nothing refreshed. Also when i write at campaign setting targets stay the same after the refreshed page. i have the same problems at the report manager how fix it?

**Comment by zeknox** [comment]
Not sure what your issues are off hand.  Perhaps you could tell me if your rails application is running in development or production mode?

Your description isn't exactly clear, but you need to Save all your campaign settings in order for them to save to the db and when the page refreshes all the changes should be saved out.

**Comment by stathmarxis** [comment]
redis-sidekig is running. I always saves my campaign settings but i have problem with targets when i saves settings or when refreshes page. How can i test  if my rails application is running in development or production mode?

**Comment by zeknox** [comment]
The development or production mode will be defined in the `/etc/apache/pf.conf` configuration file.

**Comment by stathmarxis** [comment]
<IfModule mod_passenger.c>
    PassengerRoot %ROOT
    PassengerRuby %RUBY
  </IfModule>

  <VirtualHost *:80>
    ServerName http://portal.phishingfrenzy.com
    # !!! Be sure to point DocumentRoot to 'public'!
    DocumentRoot /var/www/phishing-frenzy/public
    RailsEnv development
    <Directory /var/www/phishing-frenzy/public>
      # This relaxes Apache security settings.
      AllowOverride all
      # MultiViews must be turned off.
      Options -MultiViews
    </Directory>
  </VirtualHost>

**Comment by zeknox** [comment]
You're running in development mode. Could you please be a bit more specific whats not working with the refreshing of targets page?

**Comment by stathmarxis** [comment]
i have problem with target options. The targets not refreshed either when i saved settings and either when pressed launch button

**Comment by zeknox** [comment]
Please look over the importing a target section here and ensure you are performing the proper steps:
http://phishingfrenzy.com/resources/documentation

**Comment by stathmarxis** [comment]
i pressed delete all targets and then I could not add new targets,page didn't manage to renewed. Also at targets i put only email i didn't put name like in the example and this works

**Comment by zeknox** [comment]
So if you click the "Delete All" button it will not technically delete the target if you have sent an email to that target, but rather it will disable that target because it still needs to retain the stats.

Try adding a target to the campaign which is a different email address than what you previously added and it should work.

**Comment by stathmarxis** [comment]
yes it works thnx for the help. I know its was useless issue so i suggest to delete this issue.
