### ISSUE TITLE
Campaign Limitations

### ISSUE THREAD

**Issue by elaverriere** [pentestgeek/phishing-frenzy#222]
Is it possible to run more than one email campaign at a time?  If I use the same URL on multiple campaigns it uses the web page of the first campaign, which makes sense, but I'm unsure if I can add another SITE_URL to the application.rb file, or if that would break everything. 
Thanks for a great tool.

**Comment by Meatballs1** [comment]
SITE_URL is only used for tracking images in emails at present. If you run multiple campaigns the FQDN you configure in each campaign will be used for the Apache VirtualHostname. However, the emails will have the SITE_URL in the tracking images.

I have changes that mean that the SITE_URL will not be used for the tracking images. Instead the tracking images will goto the FQDN url:

https://github.com/pentestgeek/phishing-frenzy/pull/220

**Comment by elaverriere** [comment]
Cool, Thanks for clearing that up Meatballs1.
