### ISSUE TITLE
Not all emails are sending

### ISSUE THREAD

**Issue by elaverriere** [pentestgeek/phishing-frenzy#225]
I am running PhishingFrenzy on Kali Linux.  I'm having an issue where I have an active campaign with a list of targets, but when I launch not all of the targets are receiving the email.  Everything works fine as far as click counts and email sending, except when I go above a certain number of emails, or I guess maybe time for that matter the emails don't go out.  Phishing frenzy will show the emails as sent, but when I look at the SMTP logs it will show the correct number of emails sent (actual number not the number of targets) and I see the same thing in my gmail account.  I tried introducing a time delay for troubleshooting purposes but it sent even fewer emails, so this suggests that I'm hitting some kind of timeout which is cancelling the process.  Any ideas?

**Comment by zeknox** [comment]
Your likely hitting the 200-250 email relay cap for a gmail account, get yourself an actual SMTP service.

**Comment by elaverriere** [comment]
The first time it stopped at 16 emails, the second time it stopped at 5.  This is a gmail business account.

**Comment by Meatballs1** [comment]
Is this with background emails?

**Comment by elaverriere** [comment]
yes, so I'm wondering if it has something to do with redis or sidekiq, but I'm not too familiar with them besides the function that they are serving with PF.

**Comment by Meatballs1** [comment]
Does it work fine if you don't background the emails?

**Comment by elaverriere** [comment]
So, I just did a test with 19 users and all of those went out successfully, so I think background sending may be the culprit.  I can also compile a larger list for testing.  I'm ok leaving that disabled for the time being, but will that cause any performance issues?

**Comment by Meatballs1** [comment]
only issue afaik is with a large number of users the foreground sending can timeout... Would be nice to see if the logs show any issues though

**Comment by elaverriere** [comment]
Which logs would I view to identify issues?

**Comment by Meatballs1** [comment]
/var/logs/phishingfrenzy/logs ... either the sidekiq.log or the production.log (maybe development if you haven't set it in production mode)

**Comment by elaverriere** [comment]
So here's what I see in the sidekiq.log that stands out (sorry tried to attach a txt file but it didn't like that):

2015-09-03T13:37:37.575Z 4203 TID-ekm54 MailWorker JID-99d426b2cbbbfd13df117541 INFO: done: 4.812 sec
2015-09-03T13:37:37.583Z 4203 TID-ekm54 MailWorker JID-0dadb97b43c317f01b35d41d INFO: start
2015-09-03T13:37:37.584Z 4203 TID-ekm54 MailWorker JID-0dadb97b43c317f01b35d41d INFO: Attempting to send mail: campaign_id 6, target testuser@bs.com, blast_id 160
2015-09-03T13:37:37.824Z 4203 TID-81h7w MailWorker JID-480c9a67fa2f537ca3291e86 ERROR: Failed to send mail: campaign_id 6, target testuser@bs.com, blast_id 160 - could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
2015-09-03T13:37:37.824Z 4203 TID-81h7w MailWorker JID-480c9a67fa2f537ca3291e86 INFO: fail: 5.004 sec
2015-09-03T13:37:37.825Z 4203 TID-81h7w WARN: {"retry"=>false, "queue"=>"default", "class"=>"MailWorker", "args"=>[6, "testuser@bs.com", 160, 1], "jid"=>"480c9a67fa2f537ca3291e86", "enqueued_at"=>1441287452.815348}
2015-09-03T13:37:37.825Z 4203 TID-81h7w WARN: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
2015-09-03T13:37:37.825Z 4203 TID-81h7w WARN: /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:190:in `block in wait_poll'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `loop'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `wait_poll'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:136:in `block in poll'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:146:in `synchronize'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:134:in `poll'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:418:in `acquire_connection'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_handling.rb:87:in `connection'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/relation/delegation.rb:48:in `connection'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/relation/finder_methods.rb:424:in `find_one'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/relation/finder_methods.rb:413:in `find_with_ids'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/relation/finder_methods.rb:68:in `find'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/querying.rb:3:in `find'
/var/www/phishing-frenzy/app/mailers/phishing_frenzy_mailer.rb:7:in `phish'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.1.7/lib/abstract_controller/base.rb:189:in `process_action'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.1.7/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:82:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.1.7/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.1.7/lib/abstract_controller/base.rb:136:in `process'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionview-4.1.7/lib/action_view/rendering.rb:30:in `process'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionmailer-4.1.7/lib/action_mailer/base.rb:580:in `block in process'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.7/lib/active_support/notifications.rb:159:in `block in instrument'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.7/lib/active_support/notifications.rb:159:in `instrument'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionmailer-4.1.7/lib/action_mailer/base.rb:577:in `process'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionmailer-4.1.7/lib/action_mailer/base.rb:568:in `initialize'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionmailer-4.1.7/lib/action_mailer/base.rb:551:in `new'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionmailer-4.1.7/lib/action_mailer/base.rb:551:in `method_missing'
/var/www/phishing-frenzy/app/workers/mail_worker.rb:8:in `perform'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:75:in `execute_job'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/logging.rb:24:in `with_context'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:132:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:51:in `block in process'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:98:in `stats'
/usr/local/rvm/gems/ruby-2.1.5/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:50:in `process'
/usr/local/rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/usr/local/rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/usr/local/rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/usr/local/rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/usr/local/rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/usr/local/rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/usr/local/rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/usr/local/rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
2015-09-03T13:37:37.828Z 4203 TID-74ov4 MailWorker JID-d17a4512652e8dc0dbda5fbb ERROR: Failed to send mail: campaign_id 6, target mailuser@bs.com, blast_id 160 - could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
2015-09-03T13:37:37.828Z 4203 TID-81h7w MailWorker JID-2d706b49424e9ef46c691aa5 INFO: start
2015-09-03T13:37:37.829Z 4203 TID-74ov4 MailWorker JID-d17a4512652e8dc0dbda5fbb INFO: fail: 5.002 sec
2015-09-03T13:37:37.829Z 4203 TID-81h7w MailWorker JID-2d706b49424e9ef46c691aa5 INFO: Attempting to send mail: campaign_id 6, target mailuser@bs.com, blast_id 160
2015-09-03T13:37:37.830Z 4203 TID-74ov4 WARN: {"retry"=>false, "queue"=>"default", "class"=>"MailWorker", "args"=>[6, "mailuser@bs.com", 160, 1], "jid"=>"d17a4512652e8dc0dbda5fbb", "enqueued_at"=>1441287452.8238263}
2015-09-03T13:37:37.830Z 4203 TID-74ov4 WARN: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
2015-09-03T13:37:37.830Z 4203 TID-74ov4 WARN: /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:190:in `block in wait_poll'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `loop'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `wait_poll'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:136:in `block in poll'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'

**Comment by zeknox** [comment]
Performance issue perhaps?
<pre>2015-09-03T13:37:37.825Z 4203 TID-81h7w WARN: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)</pre>

**Comment by zeknox** [comment]
Try to change the following value inside the `config/sidekiq.yml` and see if it helps:
<pre>concurrency:  25</pre>

Try changing the 25 to something like 5 and startup sidekiq again to see if any change happens.

**Comment by Meatballs1** [comment]
Is it also worthwhile changing `sidekiq_options :retry => false` within the worker so that failed attempts are retried a certain number of times?

**Comment by elaverriere** [comment]
Hey Guys, I changed the concurrency to 5, turned background sending back on, and all of the messages went out successfully...that is until they trigged an outbound spam filter with gmail.  So, thank you for your help in getting this resolved so quickly.  It's an awesome tool.  
Do you know of alternative SMTP services that won't have the same issues?

**Comment by zeknox** [comment]
You could always install something like sendmail on the localhost configured as a smarthost, and then when sending emails it will route to the local sendmail instance, sendmail will work on delivering the emails on your behalf.

**Comment by elaverriere** [comment]
yeah, I tried that, and also tried iredmail.  Both worked, but at the moment I'm sending these through a residential TWC connection, so that immediately triggers spam filters because of the address block.  Thanks again for the help in getting this resolved.  I'm going to focus on getting my mail server hosted at an official location so that I can avoid these problems.

**Comment by Meatballs1** [comment]
@zexnok can we increase the connection pools in database.yml to match the sidekiq workers also or do you think this is an isolated occurrence?

**Comment by zeknox** [comment]
Yes, I agree that the sidekiq config needs to match the database.yml.  I have re-opened this ticket as a reminder.  Perhaps 25 for each?

**Comment by elaverriere** [comment]
Do I need to change anything in the database.yml?  I'm seeing that the pool for production, development, and test are all set to 5, so could that have caused the issue with sidekiq over running it?

**Comment by zeknox** [comment]
You should be fine if your sidekiq.yml is now at 5 because it matches the 5 inside database.yml.  The issue you had was because sidekiq was overrunning the allowed limit of the db.

**Comment by elaverriere** [comment]
Understood, so if I wanted to get back up to full speed, then I would just need to make the change in both spots?  I guess that's what happens when you give a box 4GB of ram and this is it's only purpose in life.

**Comment by zeknox** [comment]
Yeah you could likely change both to 25 and be A ok.
