### ISSUE TITLE
Production mode issue

### ISSUE THREAD

**Issue by amzatoune** [pentestgeek/phishing-frenzy#226]
Noting that my PF WebUI is running slow in dev mode, I thought maybe I'd switch over the production, but I can't seem to have any luck doing that ! 
When I run the first command : RAILS_ENV=production rake assets:precompile
**I get this prompted error :** rake aborted!
cannot load such file -- bundler/setup
/var/www/phishing-frenzy/config/boot.rb:6:in `<top (required)>'
/var/www/phishing-frenzy/config/application.rb:1:in `<top (required)>'
/var/www/phishing-frenzy/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

**with --trace :** 
RAILS_ENV=production rake assets:precompile --trace
rake aborted!
cannot load such file -- bundler/setup
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/var/www/phishing-frenzy/config/boot.rb:6:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/var/www/phishing-frenzy/config/application.rb:1:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/var/www/phishing-frenzy/Rakefile:5:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rake/rake_module.rb:25:in `load'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rake/rake_module.rb:25:in `load_rakefile'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rake/application.rb:637:in `raw_load_rakefile'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rake/application.rb:94:in `block in load_rakefile'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rake/application.rb:165:in `standard_exception_handling'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rake/application.rb:93:in `load_rakefile'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rake/application.rb:77:in `block in run'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rake/application.rb:165:in `standard_exception_handling'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rake/application.rb:75:in `run'
/usr/local/rvm/rubies/ruby-2.1.5/bin/rake:33:in `<main>'

And by the way **Apache** don't seem to be highlighted in the system status of PF ! 
Thanks

**Comment by zeknox** [comment]
Looks like this is your issue here:
<pre>
cannot load such file -- bundler/setup
</pre>

Google this to see what you can figure out!

**Comment by amzatoune** [comment]
haven't had any luck playing with the ruby versions !

**Comment by zeknox** [comment]
You should be running ruby version 2.1.5 as defined in the `.ruby-version` file.  You can validate that by running RVM list to see what versions are installed, default, and currently active.

It sounds to me like the bundler gem itself is not installed and you can likely do something like:
<pre>$ gem install bundler</pre>

It seems like the issue you're having is that the system doesn't have bundler installed and it's complaining.

**Comment by amzatoune** [comment]
When I try using the 2.1.5, this is what I get 
**dash@kali:~/Desktop66/6/^^#**/  *rvm use ruby-2.1.5
Using /root/.rvm/gems/ruby-2.1.5
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:1: invalid multibyte char (UTF-8) (SyntaxError)
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/command_manager.rb:96:in `initialize'
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/command_manager.rb:74:in `new'
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/command_manager.rb:74:in `instance'
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/gem_runner.rb:41:in `run'
	from /usr/local/rvm/rubies/ruby-2.1.5/bin/gem:21:in `<main>'
*

**Comment by amzatoune** [comment]
the same error I get when I try to install Bundler : 
gem install bundler
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:1: invalid multibyte char (UTF-8) (SyntaxError)
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/command_manager.rb:96:in `initialize'
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/command_manager.rb:74:in `new'
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/command_manager.rb:74:in `instance'
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/gem_runner.rb:41:in `run'
	from /usr/local/rvm/rubies/ruby-2.1.5/bin/gem:21:in `<main>'

**Comment by zeknox** [comment]
Can you show me the result of `rvm list` please?

**Comment by amzatoune** [comment]
rvm rubies
**
=* ruby-2.1.1 [ x86_64 ]
   ruby-2.1.5 [ x86_64 ]
   ruby-2.2.1 [ x86_64 ]
**
# => - current
# =* - current && default
#  * - default

**Comment by zeknox** [comment]
I'm sensing that your ruby 2.1.5 version could be borked. Try to uninstall it and reinstall it, this should remove it for you:
<pre>
$ rvm uninstall 2.1.5
</pre>

<pre>
$ rvm install 2.1.5
</pre>

**Comment by zeknox** [comment]
Also, I noticed you were running `rvm use ruby-2.1.5`, not sure if it matters  but try just `rvm use 2.1.5`

**Comment by amzatoune** [comment]
I'm installing the bundler successfully now, I'll post  the details of the production mode later on, thanks !

**Comment by amzatoune** [comment]
It's all good now. Everything s gone smoothly , you can close this ticket now !
Thanks man, it is a really inspiring project ... PF !

**Comment by amzatoune** [comment]
this is what phishingfrenzy.local gave me now :
**We're sorry, but something went wrong.**

**Comment by amzatoune** [comment]
I see that the problem is with the default database password associated with **rake**,
how am I supposed to edit that ! 
rake aborted!
Mysql2::Error: Access denied for user 'pf_prod'@'localhost' (using password: YES)

**Comment by zeknox** [comment]
In order to view that actual error that is causing the `We're sorry, but something went wrong.` you need to view the `log/production.log` file.

In order to change the credentials used for the mysql database you need to edit the `config/database.yml` file.

**Comment by amzatoune** [comment]
I checked the *yml* file, it is set up with the same modified password I set up the database with ! wait I ll switch over to production again and check the log file after the error !

**Comment by amzatoune** [comment]
the log file is still empty, because I didn't get to migrate and seed the db !

**Comment by zeknox** [comment]
Log file is likely empty because of improper permissions.
<pre>$ chown -R /var/www/phishing-frenzy</pre>

Then restart apache and let ir buck
<pre>$ apachectl restart</pre>

**Comment by amzatoune** [comment]
Am I to run PF in production M with the rake failing ?

**Comment by amzatoune** [comment]
I am such an idiot, I'm sorry I took your time when I really just forgot to create the new database for production :D / Thanks man this is closed now ! Appreciate it, really.

**Comment by amzatoune** [comment]
Now I lost all my emails, how am I supposed to import em from the dev mode ?
