### ISSUE TITLE
How to change name of UID field / param?

### ISSUE THREAD

**Issue by lojadaantu** [pentestgeek/phishing-frenzy#227]
Hello

My Spam filter is detecting phishing campings sent with phishing frenzy and based on my dig in it's most likely checking if the URL presented matches with the link, if not, it looks for a link with a UID param and a value 8 char long all caps. So I would like to try a simple workaround just to confirm, how can I change that? Is any configuration?

If not, what code and line is responsible for this generation and tracking?

Thanks.

**Comment by zeknox** [comment]
Thanks for the feedback here.  One quick and dirty way that might fix this quickly is to edit how the UID param is generated in the Victim model:
https://github.com/pentestgeek/phishing-frenzy/blob/master/app/models/victim.rb#L12

For example, you might be able to simply change up line 12 to something like this which will generate alpha numeric all lowercase:
```ruby
[*('a'..'z'),*('0'..'9')].shuffle[0,8].join
```

This won't change the UID parameter itself, but it will change how the UID is generate.  Tweak this example how you'd like to make the string longer or shorter, I think you can get creative.

**Comment by zeknox** [comment]
There are also many other alternatives you could do to generate the UID:
```ruby
2.1.2 :028 > require 'securerandom'
 => true 
2.1.2 :031 > SecureRandom.hex
 => "f08caa2480550e2da57df39909688d5f" 
2.1.2 :032 > SecureRandom.hex(4)
 => "d18561d4" 
2.1.2 :033 > SecureRandom.hex(6)
 => "3350a5b4af23" 
2.1.2 :034 > SecureRandom.hex(8)
 => "9db01aa0da6a7d5f" 
2.1.2 :035 > SecureRandom.hex(10)
 => "6e34d533e690f7c612c1"
```

**Comment by lojadaantu** [comment]
Hi Brandon,

Thanks for your answer, I will give a try.

I checked and change the UID param looks like complex since it's used in
many places of the code.

Kind regards.

**Comment by zeknox** [comment]
You're correct that changing the UID would need to be changed in alot of places because its used when generating the phishing url, used when tracking clicks, etc...

I think long-term the better option would be to make the UID parameter customizable within the global settings menu so the user could make any parameter they wanted.
