### ISSUE TITLE
Email Enumeration 

### ISSUE THREAD

**Issue by amzatoune** [pentestgeek/phishing-frenzy#228]
Can't we get the Email enumeration tool , so when we start a harvesting with let's say a 50 links to crawl, can't we get it to start when it left over if we repeat an enumeration with the same domain name, I think that would help a lot the gathering ?
Any ideas how to implement such thing ?
Thanks.

**Comment by zeknox** [comment]
The tool is not written the way. The tool leverages the bing API to make search requests on your behalf and essentially looks for specific regex patters to pull our the email addresses and store them to the database.

This is where the code starts for email enumeration:
https://github.com/pentestgeek/phishing-frenzy/blob/master/app/controllers/tools_controller.rb#L6

**Comment by amzatoune** [comment]
So I see there is no way tweaking around it !?

**Comment by amzatoune** [comment]
what about to go beyond 1000 links to crawl ?

**Comment by zeknox** [comment]
The code is open source, there is certainly ways to tweak it or get around it.
