### ISSUE TITLE
Test / Email Sending Issue

### ISSUE THREAD

**Issue by amzatoune** [pentestgeek/phishing-frenzy#229]
Can't get any email sent via sidekiq, they are all bound to fail  ! ( Via Gmail or any other mail service provider )

**Comment by amzatoune** [comment]
When I disable Sidekiq the test email is fluently sent ! I think my sidekiq has some problem !

**Comment by Meatballs1** [comment]
Is redis running? Is sidekiq running? :) Check /var/www/phishingfrenzy/logs/sidekiq.log

**Comment by zeknox** [comment]
We need more info here. Log results, etc... like meatballs already mentioned.  Please supply additional info so we can assist further.

**Comment by amzatoune** [comment]
extrait of sidekiq.log

**Comment by Meatballs1** [comment]
have you started sidekiq in development mode when phishing frenzy is in production mode?

`RAILS_ENV=production bundle exec sidekiq -C config/sidekiq.yml`

**Comment by amzatoune** [comment]
nah I usually daemonize it only with bundle exec sidekiq -C config/sidekiq.yml

**Comment by amzatoune** [comment]
@Meatballs1 thanks man , that did it :D

**Comment by amzatoune** [comment]
but still, sidekiq shows that the emails are being sent alright, but when I do a check, it doesn't really send 'em , it has a loss ratio about 80% of the whole batch ! what's that ?
