### ISSUE TITLE
Using a purchased domain

### ISSUE THREAD

**Issue by get-that-money** [pentestgeek/phishing-frenzy#231]
Can you please provide me with some help on what to do if I want to use a custom domain that I purchased to track clickers?

I installed PF via Docker.

**Comment by zeknox** [comment]
Create a DNS A record to point to the public IP address of your PF box. Then configure your FQDN within the campaign the same as the DNS A record and make the campaign active.

**Comment by get-that-money** [comment]
I have installed PF via docker on DigitalOcean. What do I need to change to be able to access the portal on there from the web? I keep seeing the default Apache page when visiting the public facing IP.

**Comment by zeknox** [comment]
Got this question addressed via IRC.
