### ISSUE TITLE
Importing emails limitation

### ISSUE THREAD

**Issue by amzatoune** [pentestgeek/phishing-frenzy#233]
1 error prohibited this record from being saved

   There were problems with the following fields:

    Emails is too long (maximum is 60000 characters)

Where can I find the file responsible for such limitation to modify it !?

**Comment by Meatballs1** [comment]
https://github.com/pentestgeek/phishing-frenzy/blob/e83e1d18084f364980b973c744bdf2eeeb470304/app/models/campaign.rb

**Comment by amzatoune** [comment]
thanks man, that I missed x)
