### ISSUE TITLE
Sending emails as test emails 

### ISSUE THREAD

**Issue by amzatoune** [pentestgeek/phishing-frenzy#235]
Can I somehow send the emails as test without assigning a track id to every single target, because it is taking too much time adding/deleting targets 
thanks in advance.

**Comment by zeknox** [comment]
No there is not a way to send multiple test targets at this time.  The best thing to do is add in all your test targets as normal targets.  Execute the phish like you normally would as if it wasn't a test.

Once all the emails are sent and testing appears to be proper what you can do is goto the reports page and "Delete All Statistics" for that specific campaign.  This will also remove all of the targets for the campaign.

Now that you know everything is working properly all you need to do is add in your actual targets and click "Launch" again.
