### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by deannick** [pentestgeek/phishing-frenzy#237]
I have fixed some issue by reading some tickets and other things around. Now im getting ActiveRecord::StatmentInvalid in Devise::SessionController#new.  Mysql2:Error: Table'pf_dev.global_settings'dosen't exist: SELECT ' global_settings'.*From 'global_settings' ORDERED BY 'global_settings'.'id' ASC LIMIT 1.

**Comment by zeknox** [comment]
Your rake db:seed did not execute properly.

Brandon

**Comment by deannick** [comment]
I started over but i used Ubuntu this time. All seems to be working better.  I can get into the web interface and have Redis and Sidekiq running, but not appache. This is weird to me since i can access the web interface.  I can access it on another computer but only by IP address.  I started to play with a campaign, and tried to launch it but it tell me i need the FQDN. From what i thought i would be putting in the IP for the PF server. I was wrong there.

**Comment by Meatballs1** [comment]
The campaign and the web interface are all hosted on the same IP and the same Apache server port.

They each have a VirtualHostName which is used to determine which page should be loaded - so you need to visit the page via the appropriate hostname. If needed modify your /etc/hosts file to contain a manual DNS entry.
