### ISSUE TITLE
Sidekiq Error - Cannot find campaign ID

### ISSUE THREAD

**Issue by nerbix** [pentestgeek/phishing-frenzy#238]
After pulling the latest version, I am running into Sidekiq issues when attempting to launch a campaign and no e-mails are sent.  Here is the Sidekiq log output: 

2015-10-08T15:40:30.894Z 4402 TID-1bi3aw MailWorker JID-d7ed7ed28c631241784a24a1 INFO: start
2015-10-08T15:40:30.894Z 4402 TID-1bi3aw MailWorker JID-d7ed7ed28c631241784a24a1 INFO: Attempting to send mail: campaign_id 22, target XXXXXXX@gmail.com, blast_id 254
2015-10-08T15:40:30.896Z 4402 TID-1bi3aw MailWorker JID-d7ed7ed28c631241784a24a1 ERROR: Failed to send mail: campaign_id 22, target XXXXXXX@gmail.com, blast_id 254 - Couldn't find Campaign with 'id'=22
2015-10-08T15:40:30.896Z 4402 TID-1bi3aw MailWorker JID-d7ed7ed28c631241784a24a1 INFO: fail: 0.002 sec
2015-10-08T15:40:30.899Z 4402 TID-1bi3aw WARN: {"retry"=>false, "queue"=>"default", "class"=>"MailWorker", "args"=>[22, "XXXXX@gmail.com", 254, 1], "jid"=>"d7ed7ed28c631241784a24a1", "enqueued_at"=>1444318830.8925767}
2015-10-08T15:40:30.899Z 4402 TID-1bi3aw WARN: Couldn't find Campaign with 'id'=22
2015-10-08T15:40:30.899Z 4402 TID-1bi3aw WARN: /var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/relation/finder_methods.rb:320:in `raise_record_not_found_exception!'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/relation/finder_methods.rb:429:in `find_one'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/relation/finder_methods.rb:413:in `find_with_ids'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/relation/finder_methods.rb:68:in `find'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/querying.rb:3:in `find'
/var/www/phishing-frenzy/app/mailers/phishing_frenzy_mailer.rb:7:in `phish'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.7/lib/abstract_controller/base.rb:189:in `process_action'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.7/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:82:in `run_callbacks'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.7/lib/abstract_controller/callbacks.rb:19:in `process_action'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.7/lib/abstract_controller/base.rb:136:in `process'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.7/lib/action_view/rendering.rb:30:in `process'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.7/lib/action_mailer/base.rb:580:in `block in process'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/notifications.rb:159:in `block in instrument'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/notifications.rb:159:in `instrument'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.7/lib/action_mailer/base.rb:577:in `process'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.7/lib/action_mailer/base.rb:568:in `initialize'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.7/lib/action_mailer/base.rb:551:in `new'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.7/lib/action_mailer/base.rb:551:in `method_missing'
/var/www/phishing-frenzy/app/workers/mail_worker.rb:8:in `perform'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:75:in `execute_job'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/logging.rb:24:in `with_context'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:132:in `call'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:51:in `block in process'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:98:in `stats'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:50:in `process'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'

**Comment by nerbix** [comment]
I did confirm that the campaign (#22) is in phishing-frenzy/public/deployed/campaigns/22

**Comment by zeknox** [comment]
You are likely starting up sidekiq in development mode when the application is running in production mode?

Try starting sidekiq in production mode like so:
<pre>$ RAILS_ENV=production bundle exec sidekiq -C config/sidekiq.yml</pre>

**Comment by nerbix** [comment]
That worked. thanks!

**Comment by zeknox** [comment]
Website has been updated to include this appropriate command for production mode:
http://phishingfrenzy.com/resources/rails_production_mode
