### ISSUE TITLE
Configuring Page Timeout

### ISSUE THREAD

**Issue by curi0usJack** [pentestgeek/phishing-frenzy#239]
Hello,

I'm trying to use PF to send a large batch of emails (5000+). I have sidekiq up and running, successfully processing messages, and have been able to send about 1000 messages before the page seems to timeout. How can I adjust the page timeout setting in the application? 

Bonus question: I'm a complete novice when it comes to Ruby. Could someone tell me how to run the bundle-exec command which starts sidekiq when PF starts up?

Many thanks. Your help is appreciated.

**Comment by zeknox** [comment]
The first thing we need to confirm is if your actually sending the emails via Sidekiq.  Can you confirm if "Background Emails" is checked within the Global Settings menu?

If it is sending emails in the background this surprises me because the webpage should not hang for long when you launch emails via Sidekiq (that's it's intended purpose).

As a workaround to send all of the 5K emails you can used a the phased sending approach.  Take a look here how you can chunk of your email batches into chunks to launch the entire 5K:
http://phishingfrenzy.com/resources/getting_started#phased_send

For starting Sidekiq on startup see the wiki here which describes this process:
https://github.com/mperham/sidekiq/wiki/Deployment#daemonization

**Comment by curi0usJack** [comment]
Yes, Background Emails is checked. I've also confirmed that Sidekiq is successfully queueing and processing emails. Concurrency is set to 25 in both database & sidekiq yml files. 

I did notice this message in production.log: Completed 401 Unauthorized in 30492ms. Interesting that a 401 is displaying in the log because an "Internal Server Error" is thrown to the page (assuming a 500 error). In my last test, 288 emails were sent before the error occurred. That is the only message I can find in the logs that would indicate a problem.

I can batch send as you suggest, but that seems a bit tedious. Is there a setting that governs how many threads PF uses to queue messages with sidekiq? I'm assuming the sidekiq concurrency setting governs the amount of threads sidekiq uses for processing, not the amount of threads PF uses to communicate with sidekiq. Either that, or can I up the page timeout somehow?

Thanks by the way for the link to the Sidekiq docs. That's exactly what I needed.

**Comment by zeknox** [comment]
How long would you say your are waiting once you click the launch button?  What should be happening is that it should load all 5K jobs into sidekiq, and then it should process 25 jobs at a time taking one of the queue in a FIFO manner.

I wonder if the 401 is happening because of an idle timeout issue with devise perhaps.  @Meatballs1 have you run into any issues launching large batches with sidekiq?

**Comment by Meatballs1** [comment]
No never tried anything that ambitious yet :)

**Comment by curi0usJack** [comment]
I did some more testing. After launching the campaign the time till error is approximately 30 seconds (consistently). In the first test, 833 emails were sent before error. In the second, 1383. I am monitoring progress through the sidekiq dashboard and the production log. It is spawning the jobs to sidekiq as you say, but it takes anywhere from 80-140ms per email. For example, from my production.log:

Sent mail to afakeaddress1@mailinator.com (117.5ms)
Sent mail to afakeaddress2@mailinator.com (112.7ms)
Sent mail to afakeaddress3@mailinator.com (136.6ms)
Sent mail to afakeaddress4@mailinator.com (112.3ms)

Seems that it will spawn as many jobs as it can until some threshold is hit.

Additionally, this from my apache error.log: 

[ 2015-10-12 08:49:49.0838 24748/7f7bc32e1780 agents/Watchdog/Main.cpp:386 ]: Some Phusion Passenger agent processes did not exit in time, forcefully shutting down all.

Do you know where is the server page timeout set? I'd like to tweak this and see if it has any impact.

Thanks for responding!

**Comment by Meatballs1** [comment]
Just checking, is redis up and running?

**Comment by curi0usJack** [comment]
Yessir, listening on 6379.

**Comment by zeknox** [comment]
You're running an up to date version of PF from git?

**Comment by curi0usJack** [comment]
Unfortunately not. How do I check the version (I don't see it in the UI)?

**Comment by zeknox** [comment]
Navigate to `/var/www/phishing-frenzy` and run `git log`.  Let us know what commit ID is at the top of the log.  This will allow us to determine what version of PF you're running and how outdated it is.

**Comment by curi0usJack** [comment]
ab777b034acd765d5f89377a613790444c408815

1/6/2015

**Comment by zeknox** [comment]
Yup, that is likely the issue.  @Meatballs1 did some work on the `phishing_frenzy_mailer` to address some bugs and likely an updated version may address your issues here.

**Comment by curi0usJack** [comment]
I'll give upgrading a shot. Is there a guide posted by chance? I'm not a ruby dev and don't want to get stuck in gem dependency hell. =)

**Comment by zeknox** [comment]
Yes there is some guidance here:
http://phishingfrenzy.com/resources/updating_phishing_frenzy

There has been a number of changes that have taken place since your last update.  The biggest change will likely be that you'll need to navigate to `Global Settings` after the upgrade to update the Application URL which has moved from `config/application.rb` to the Admin page.

**Comment by curi0usJack** [comment]
Awesome. Thanks for your responsiveness guys. Much appreciated.  If you don't mind, please leave this issue open. I will upgrade today and report back with progress. 

Thanks.

**Comment by curi0usJack** [comment]
Upgrade was successful, but the issue persists with the same symptoms (error after 30s). Additionally, sidekiq is no longer sending emails, with the following in the sidekiq.log file:

2015-10-12T16:09:46.525Z 9696 TID-owybdrp8g WARN: {"retry"=>false, "queue"=>"default", "class"=>"MailWorker", "args"=>[26, "fakemail1@mailinator.com", 487, 1], "jid"=>"d79c8aa65ef0b5e39cd0b3d0", "enqueued_at"=>1444666186.5155866}
2015-10-12T16:09:46.546Z 9696 TID-owybdrp8g WARN: **wrong number of arguments (4 for 1..2)**
2015-10-12T16:09:46.546Z 9696 TID-owybdrp8g WARN: /var/www/phishing-frenzy/app/workers/mail_worker.rb:5:in `perform'

Seems as though a dependency was changed in the upgrade. Any thoughts?

The same Phusion Passenger error is displayed in the apache log.

**Comment by zeknox** [comment]
Make sure you restart the sidekiq service and restart the apache service.  Based on this error here `wrong number of arguments (4 for 1..2)` I don't think you've restarted both services.

**Comment by curi0usJack** [comment]
Restarting sidekiq worked, and I can now send nearly 2000 emails before the error occurs. The default time to spawn a job to sidekiq is now only around 70ms. Nice!

The fundamental problem seems to be with a setting in mod_rails. The watchdog process isn't getting any feedback (even though jobs are spawning) so it terminates everything after a given time period (around 30s). I'm trying to find out where that setting is.

**Comment by curi0usJack** [comment]
Bummer. This appears to be the setting I need:

https://www.phusionpassenger.com/library/config/apache/reference/#passengermaxrequesttime

Seems as though it's available in Passenger Enterprise only. :-(

**Comment by curi0usJack** [comment]
Solved!

Even though the documentation says that the switches to modify the timeout are only in the Enterprise version of Passenger, the timeout value is simply hardcoded in the source code of the community version. 

The fix is to change line 337 of ~/.rvm/gems/ruby-2.2.0/gems/passenger-4.0.57/ext/common/agents/Watchdog/Main.cpp:

    unsigned long long deadline = 30000; //milliseconds

I set my value to 300000 (5 minutes) and restarted apache. I was then able to send 6000 emails in a single campaign launch. It took 3:09 to spawn all the emails to sidekiq and about 2 minutes after that for the email server to send them all to their targets. Not bad!

Thanks all for your help!

**Comment by zeknox** [comment]
All hail @curi0usJack! Thanks for posting this creative solution and sharing your experience with us.

**Comment by curi0usJack** [comment]
Thanks for making a great product! We use it for pretty much everything. :-) Take care!

**Comment by Meatballs1** [comment]
n.b. I wonder if changing the campaign sleep setting would reduce that delay:

https://github.com/pentestgeek/phishing-frenzy/blob/master/app/mailers/phishing_frenzy_mailer.rb#L71
`     sleep(@campaign.campaign_settings.smtp_delay)`

Or commenting out that line if we are running in sidekiq mode...

**Comment by Meatballs1** [comment]
Maybe we should make the loop in `email_controller` an async job itself removing it from here:

https://github.com/pentestgeek/phishing-frenzy/blob/master/app/controllers/email_controller.rb#L55

```
def deliver_async(campaign_id, victim_emails, blast_id)
      victims_emails.each do |e|
          MailWorker.perform_async(campaign_id, e, blast_id, PhishingFrenzyMailer::ACTIVE)
        end
end
```

**Comment by Meatballs1** [comment]
Also wonder if we can configure sidekiq to use unix sockets to increase performance (or does it use these by default?):

https://github.com/mperham/sidekiq/wiki/Using-Redis

**Comment by Meatballs1** [comment]
n.b. my performance for queuing up 5003 emails is as follows in development mode with webbrick:

`Redirected to http://localhost:3000/campaigns/1
Completed 302 Found in 18038ms (ActiveRecord: 2399.4ms)`

**Comment by Meatballs1** [comment]
Simple optimization reduces it to `Completed 302 Found in 9278ms (ActiveRecord: 1680.9ms)`

**Comment by Meatballs1** [comment]
With some further optimizations can reduce it down to:

`Completed 302 Found in 3333ms (ActiveRecord: 23.8ms)`

**Comment by Meatballs1** [comment]
With #240 should be able to handle 10k mails imo - targeting even larger campaigns may again hit the issue again at some point.

**Comment by Meatballs1** [comment]
A second approach https://github.com/pentestgeek/phishing-frenzy/pull/241 means that the whole queue creation is done via Sidekiq - removing this issue altogether. However do we want to create additional background job for each email etc, or run them all in the single background job?
