### ISSUE TITLE
Install Phishing Frenzy with Docker on Kali 2.0, not working on WAN ...

### ISSUE THREAD

**Issue by uslap** [pentestgeek/phishing-frenzy#242]
Hello,

I have follow all the step to build phishing frenzy with docker : 
http://www.phishingfrenzy.com/resources/install_with_docker

I do my local IP on /etc/hosts : 
@LocalIP    phishingfrenzy.local

Then all sems to work perfectly for the acces of the website phishingfrenzy.local :
 
![capture d ecran 2015-10-14 a 15 58 39](https://cloud.githubusercontent.com/assets/5678141/10485882/b27d15fc-728c-11e5-8636-b7249a825fcd.png)

When i put my public IP on the Campaign Options & when i lauch the campaign : 
![capture d ecran 2015-10-14 a 16 02 43](https://cloud.githubusercontent.com/assets/5678141/10485957/0b2a5a2a-728d-11e5-8e09-29dabf4436a9.png)

I receive a e-mail but nothing append when i click on the link : 
![capture d ecran 2015-10-14 a 16 05 18](https://cloud.githubusercontent.com/assets/5678141/10486038/64800494-728d-11e5-9acf-58f435712015.png)

I try porforwarding but is the same it doens't work ...

Do you have an idea ?

Best regards,
David.

**Comment by uslap** [comment]
I want to add when i do my local IP for a test is the same : 
![capture d ecran 2015-10-14 a 16 22 33](https://cloud.githubusercontent.com/assets/5678141/10486599/fb4d29fe-728f-11e5-9195-d932ea382ff9.png)

**Comment by Meatballs1** [comment]
I dont think Apache supports IP addresses in the `VirtualHostName` field. The URLs and FQDN should be domains.

**Comment by uslap** [comment]
Ok but what can i do ??

**Comment by Meatballs1** [comment]
Well you can either use a real domain that you own `something.com` or a fake domain `something.tld`.

Then either configure your real domain to point to your site or set the IP in your hosts file again for `something.tld`

**Comment by uslap** [comment]
i don't understand ... i point my domain to my site ? witch website ?

**Comment by uslap** [comment]
![capture d ecran 2015-10-14 a 17 06 25](https://cloud.githubusercontent.com/assets/5678141/10487782/fafddeac-7295-11e5-8935-1bda3bfe0493.png)

?

**Comment by Meatballs1** [comment]
So now configure a new campaign with Phishing URL `http://something.tld` and FQDN `something.tld`. 

Make the campaign active and you should be able to visit `something.tld` in your web browser. n.b. This will only work internally for you.

**Comment by uslap** [comment]
![capture d ecran 2015-10-14 a 19 03 52](https://cloud.githubusercontent.com/assets/5678141/10491316/5fc0f6fc-72a6-11e5-8c72-e3d90aa30e96.png)

I think is the same ...

**Comment by uslap** [comment]
![capture d ecran 2015-10-14 a 22 56 16](https://cloud.githubusercontent.com/assets/5678141/10497694/9338a4f0-72c7-11e5-92d4-f6bc7a064f85.png)


![capture d ecran 2015-10-14 a 23 03 54](https://cloud.githubusercontent.com/assets/5678141/10497745/e28c06dc-72c7-11e5-92eb-b24abc490dfb.png)

![capture d ecran 2015-10-14 a 23 06 02](https://cloud.githubusercontent.com/assets/5678141/10497794/2cd92f08-72c8-11e5-84e4-7fa42006c453.png)

![capture d ecran 2015-10-14 a 23 06 42](https://cloud.githubusercontent.com/assets/5678141/10497811/493e745a-72c8-11e5-8004-03d85f40f85c.png)

Do you have an idea ? I think i follow step by step, the documentation, etc ...

**Comment by uslap** [comment]
OK now the website on the mail link now work : 
![capture d ecran 2015-10-15 a 17 21 21](https://cloud.githubusercontent.com/assets/5678141/10518375/6595d5d2-7361-11e5-86f7-337301c1f166.png)


![capture d ecran 2015-10-15 a 17 22 24](https://cloud.githubusercontent.com/assets/5678141/10518358/572ab3a0-7361-11e5-8b19-e246da207172.png)

But i don't get any statistics . Could you help me plz ?

**Comment by zeknox** [comment]
You likely need to update your Application Site URL to the proper FQDN which is used as a callback URL for your phishing sites to track analytics. This will required you make any active campaigns inactive, and active again to update the php tracking tags with the proper Site URL.

This guide should assist, the portion about config/application.rb is outdated as this has not moved to the "Global Settings" menu.
http://phishingfrenzy.com/resources/troubleshooting
