### ISSUE TITLE
sidekiq error kali Sana

### ISSUE THREAD

**Issue by jteslaxxx** [pentestgeek/phishing-frenzy#243]
using system Kali Sana and running in error in sidekiq configuration!

No such file or directory @ rb_sysopen - ./log/sidekiq.log
/usr/lib/ruby/2.1.0/logger.rb:600:in `initialize'
/usr/lib/ruby/2.1.0/logger.rb:600:in `open'
/usr/lib/ruby/2.1.0/logger.rb:600:in `create_logfile'
/usr/lib/ruby/2.1.0/logger.rb:594:in `rescue in open_logfile'
/usr/lib/ruby/2.1.0/logger.rb:591:in `open_logfile'
/usr/lib/ruby/2.1.0/logger.rb:549:in `initialize'
/usr/lib/ruby/2.1.0/logger.rb:318:in `new'
/usr/lib/ruby/2.1.0/logger.rb:318:in `initialize'
/var/www/html/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/logging.rb:31:in `new'
/var/www/html/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/logging.rb:31:in `initialize_logger'
/var/www/html/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/cli.rb:344:in `initialize_logger'
/var/www/html/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/cli.rb:39:in `parse'
/var/www/html/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/bin/sidekiq:7:in `<top (required)>'
/var/www/html/phishing-frenzy/vendor/bundle/ruby/2.1.0/bin/sidekiq:23:in `load'
/var/www/html/phishing-frenzy/vendor/bundle/ruby/2.1.0/bin/sidekiq:23:in `<main>'

**Comment by zeknox** [comment]
Create the file /log/sidekiq.log and then start sidekiq again. That is what the error message says.

**Comment by jteslaxxx** [comment]
hello again!
Thanks for your answer! So figured it out mysef! Made installation, all seems fine no errors, but when I am moving in browser to phishingfrenzy.local i get /var/www/phishing-frenzy/public index page with file listing:
Index of /
[ICO]	Name	Last modified	Size	Description
[TXT]	404.html	2015-10-18 10:33 	728 	 
[TXT]	422.html	2015-10-18 10:33 	711 	 
[TXT]	500.html	2015-10-18 10:33 	643 	 
[IMG]	favicon.ico	2015-10-18 10:33 	0 	 
[TXT]	index_default.html	2015-10-18 10:33 	5.8K	 
[DIR]	javascripts/	2015-10-18 10:33 	- 	 
[TXT]	robots.txt	2015-10-18 10:33 	26 	 
[DIR]	stylesheets/	2015-10-18 10:33 	- 	 
[DIR]	templates/	2015-10-18 10:33 	- 	 
[IMG]	tracking_pixel.png	2015-10-18 10:33 	95 	 
[DIR]	uploads/	2015-10-18 10:33 	- 	 
Apache/2.4.10 (Debian) Server at phishingfrenzy.local Port 80

Here is my apachectl configuration:
root@kali:~# apachectl -S
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server kali.JTGroup (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost kali.JTGroup (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost phishingfrenzy.local (/etc/apache2/pf.conf:6)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex watchdog-callback: using_defaults
Mutex default: dir="/var/lock/apache2" mechanism=fcntl 
Mutex mpm-accept: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33
Group: name="www-data" id=33

And here is my pf.conf: <IfModule mod_passenger.c>
    PassengerRoot %ROOT
    PassengerRuby %RUBY
  </IfModule>

  <VirtualHost *:80>
    ServerName http://phishingfrenzy.local
    # !!! Be sure to point DocumentRoot to 'public'!
    DocumentRoot /var/www/phishing-frenzy/public
    RailsEnv development
    <Directory /var/www/html/phishing-frenzy/public>
      # This relaxes Apache security settings.
      AllowOverride all
      # MultiViews must be turned off.
      Options -MultiViews
    </Directory>
  </VirtualHost>

maybe i have some directory error listing? 
I,m new in Ruby so thanks for your answer!

**Comment by jteslaxxx** [comment]
Hello Zeknox!

So got tired to play with Kali Sana to install PF decided to try it out on my backbox ubuntu(64amd)
Installation passed nice, no problems at all, but now when i navigate to phishingfrenzy.local I get this:
![screenshot from 2015-10-20 14 31 18](https://cloud.githubusercontent.com/assets/13330266/10605981/4623ae06-7738-11e5-954b-9648680ea250.png)


this is my pf.conf:
VirtualHost *:80> 
    ServerName phishingfrenzy.local 
    # !!! Be sure to point DocumentRoot to 'public'! 
    DocumentRoot /var/www/phishing-frenzy/public 
    RailsEnv development 
    <Directory /var/www/phishing-frenzy/public> 
      # This relaxes Apache security settings. 
      AllowOverride all 
      # MultiViews must be turned off. 
      Options -MultiViews 
    </Directory> 
  </VirtualHost> 

this is apachctl -s: 
adminpc@adminpc-VirtualBox:/var/www/phishing-frenzy$ apachectl -S 
VirtualHost configuration: 
*:80                   is a NameVirtualHost 
         default server localhost (/etc/apache2/sites-enabled/000-default.conf:1) 
         port 80 namevhost localhost (/etc/apache2/sites-enabled/000-default.conf:1) 
         port 80 namevhost phishingfrenzy.local (/etc/apache2/pf.conf:1) 
ServerRoot: "/etc/apache2" 
Main DocumentRoot: "/var/www" 
Main ErrorLog: "/var/log/apache2/error.log" 
Mutex default: dir="/var/lock/apache2" mechanism=fcntl 
Mutex mpm-accept: using_defaults 
Mutex watchdog-callback: using_defaults 
PidFile: "/var/run/apache2/apache2.pid" 
Define: DUMP_VHOSTS 
Define: DUMP_RUN_CFG 
User: name="www-data" id=33 not_used 
Group: name="www-data" id=33 not_used

and this is my apache.conf:

# This is the main Apache server configuration file.  It contains the 
# configuration directives that give the server its instructions. 
# See http://httpd.apache.org/docs/2.4/ for detailed information about 
# the directives and /usr/share/doc/apache2/README.Debian about Debian specific 
# hints. 
# 
# 
# Summary of how the Apache 2 configuration works in Debian: 
# The Apache 2 web server configuration in Debian is quite different to 
# upstream's suggested way to configure the web server. This is because Debian's 
# default Apache2 installation attempts to make adding and removing modules, 
# virtual hosts, and extra configuration directives as flexible as possible, in 
# order to make automating the changes and administering the server as easy as 
# possible. 

# It is split into several files forming the configuration hierarchy outlined 
# below, all located in the /etc/apache2/ directory: 
# 
#	/etc/apache2/ 
#	|-- apache2.conf 
#	|	`--  ports.conf 
#	|-- mods-enabled 
#	|	|-- *.load 
#	|	`-- *.conf 
#	|-- conf-enabled 
#	|	`-- *.conf 
# 	`-- sites-enabled 
#	 	`-- *.conf 
# 
# 
# * apache2.conf is the main configuration file (this file). It puts the pieces 
#   together by including all remaining configuration files when starting up the 
#   web server. 
# 
# * ports.conf is always included from the main configuration file. It is 
#   supposed to determine listening ports for incoming connections which can be 
#   customized anytime. 
# 
# * Configuration files in the mods-enabled/, conf-enabled/ and sites-enabled/ 
#   directories contain particular configuration snippets which manage modules, 
#   global configuration fragments, or virtual host configurations, 
#   respectively. 
# 
#   They are activated by symlinking available configuration files from their 
#   respective *-available/ counterparts. These should be managed by using our 
#   helpers a2enmod/a2dismod, a2ensite/a2dissite and a2enconf/a2disconf. See 
#   their respective man pages for detailed information. 
# 
# * The binary is called apache2. Due to the use of environment variables, in 
#   the default configuration, apache2 needs to be started/stopped with 
#   /etc/init.d/apache2 or apache2ctl. Calling /usr/bin/apache2 directly will not 
#   work with the default configuration. 


# Global configuration 
# 

# 
# ServerRoot: The top of the directory tree under which the server's 
# configuration, error, and log files are kept. 
# 
# NOTE!  If you intend to place this on an NFS (or otherwise network) 
# mounted filesystem then please read the Mutex documentation (available 
# at <URL:http://httpd.apache.org/docs/2.4/mod/core.html#mutex>); 
# you will save yourself a lot of trouble. 
# 
# Do NOT add a slash at the end of the directory path. 
# 
#ServerRoot "/etc/apache2" 

# 
# The accept serialization lock file MUST BE STORED ON A LOCAL DISK. 
# 
Mutex file:${APACHE_LOCK_DIR} default 

# 
# PidFile: The file in which the server should record its process 
# identification number when it starts. 
# This needs to be set in /etc/apache2/envvars 
# 
PidFile ${APACHE_PID_FILE} 

# 
# Timeout: The number of seconds before receives and sends time out. 
# 
Timeout 300 

# 
# KeepAlive: Whether or not to allow persistent connections (more than 
# one request per connection). Set to "Off" to deactivate. 
# 
KeepAlive On 

# 
# MaxKeepAliveRequests: The maximum number of requests to allow 
# during a persistent connection. Set to 0 to allow an unlimited amount. 
# We recommend you leave this number high, for maximum performance. 
# 
MaxKeepAliveRequests 100 

# 
# KeepAliveTimeout: Number of seconds to wait for the next request from the 
# same client on the same connection. 
# 
KeepAliveTimeout 5 


# These need to be set in /etc/apache2/envvars 
User ${APACHE_RUN_USER} 
Group ${APACHE_RUN_GROUP} 

# 
# HostnameLookups: Log the names of clients or just their IP addresses 
# e.g., www.apache.org (on) or 204.62.129.132 (off). 
# The default is off because it'd be overall better for the net if people 
# had to knowingly turn this feature on, since enabling it means that 
# each client request will result in AT LEAST one lookup request to the 
# nameserver. 
# 
HostnameLookups Off 
 
# ErrorLog: The location of the error log file. 
# If you do not specify an ErrorLog directive within a <VirtualHost> 
# container, error messages relating to that virtual host will be 
# logged here.  If you *do* define an error logfile for a <VirtualHost> 
# container, that host's errors will be logged there and not here. 
# 
ErrorLog ${APACHE_LOG_DIR}/error.log 

# 
# LogLevel: Control the severity of messages logged to the error_log. 
# Available values: trace8, ..., trace1, debug, info, notice, warn, 
# error, crit, alert, emerg. 
# It is also possible to configure the log level for particular modules, e.g. 
# "LogLevel info ssl:warn" 
# 
LogLevel warn 

# Include module configuration: 
IncludeOptional mods-enabled/*.load 
IncludeOptional mods-enabled/*.conf 

# Include list of ports to listen on 
Include ports.conf 


# Sets the default security model of the Apache2 HTTPD server. It does 
# not allow access to the root filesystem outside of /usr/share and /var/www. 
# The former is used by web applications packaged in Debian, 
# the latter may be used for local directories served by the web server. If 
# your system is serving content from a sub-directory in /srv you must allow 
# access here, or in any related virtual host. 
<Directory /> 
	Options FollowSymLinks 
	AllowOverride None 
	Require all denied 
</Directory> 

<Directory /usr/share> 
	AllowOverride None 
	Require all granted 
</Directory> 

<Directory /var/www/> 
	Options Indexes FollowSymLinks 
	AllowOverride None 
	Require all granted 
</Directory> 

#<Directory /srv/> 
#	Options Indexes FollowSymLinks 
#	AllowOverride None 
#	Require all granted 
#</Directory> 




# AccessFileName: The name of the file to look for in each directory 
# for additional configuration directives.  See also the AllowOverride 
# directive. 
# 
AccessFileName .htaccess 

# 
# The following lines prevent .htaccess and .htpasswd files from being 
# viewed by Web clients. 
# 
<FilesMatch "^\.ht"> 
	Require all denied 
</FilesMatch> 


# 
# The following directives define some format nicknames for use with 
# a CustomLog directive. 
# 
# These deviate from the Common Log Format definitions in that they use %O 
# (the actual bytes sent including headers) instead of %b (the size of the 
# requested file), because the latter makes it impossible to detect partial 
# requests. 
# 
# Note that the use of %{X-Forwarded-For}i instead of %h is not recommended. 
# Use mod_remoteip instead. 
# 
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined 
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined 
LogFormat "%h %l %u %t \"%r\" %>s %O" common 
LogFormat "%{Referer}i -> %U" referer 
LogFormat "%{User-agent}i" agent 

# Include of directories ignores editors' and dpkg's backup files, 
# see README.Debian for details. 

# Include generic snippets of statements 
IncludeOptional conf-enabled/*.conf 

# Include the virtual host configurations: 
IncludeOptional sites-enabled/*.conf 

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet 


 
LoadModule passenger_module /home/adminpc/.rvm/gems/ruby-2.1.5/gems/passenger-5.0.20/buildout/apache2/mod_passenger.so 
   <IfModule mod_passenger.c> 
     PassengerRoot /home/adminpc/.rvm/gems/ruby-2.1.5/gems/passenger-5.0.20 
     PassengerDefaultRuby /home/adminpc/.rvm/gems/ruby-2.1.5/wrappers/ruby 
   </IfModule> 



Include pf.conf 

etc/hosts:


127.0.0.1	localhost
127.0.1.1	adminpc-VirtualBox
192.168.0.116   phishingfrenzy.local

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters


Any ideas zeknox??

**Comment by jteslaxxx** [comment]
Closing up this issue! Problem was i had double installations files and needed to clean up!
If somebody have any installation problems in Kali Sana 64AMD just use RVM install 2.1.5 and 
before new installation attempt, clean all previous ones, drop databases and make everything from start!

**Comment by jteslaxxx** [comment]
It is a Beast zeknox:)
Super, keep continue:)
