### ISSUE TITLE
4th campaign SSL won't upload

### ISSUE THREAD

**Issue by hrazzell** [pentestgeek/phishing-frenzy#249]
Hey Zeknox,

I'm having trouble uploading the SSL certs for my fourth campaign (2nd SSL enabled). The site just hangs on clicking 'Save Settings' and then displays: 

"Network Error (tcp_error) 

A communication error occurred: ""

This is the fourth campaign I've created, and I noticed there are only 9 folders in the public/ssl/filename (1 for each file, 3 for each campaign). Is there a possibility Phishing Frenzy is only set up for SSL on the first 3 sites, or will new folders be created for each site?

Also is there a manual way to set up SSL on a virtual host after its campaign is launched?

Thanks in advance for any help!

**Comment by zeknox** [comment]
First thing I would check is to make sure that the www-data account has the ability to write to the public/* directory. If you have updated or made any changes as root it may have messed up the permissions (now owned by root or something).

Yes you can certainly configure SSL on a VHOST after the campaign is launched.  You could probably do this 2 ways.  Either go into the campaign, add the SSL files, make campaign inactive, and active again.  Once its activated again it will see SSL enabled and deploy with SSL certs.

The other way is to find the ID of the campaign and manually configure Apache to use the SSL certificates you have in place.  You can find the VHOST file located at /etc/apache2/sites-enabled/:id.conf

**Comment by hrazzell** [comment]
Thanks so much for your prompt reply!

It turns out the issue was the password on the private key file. After removing that with SSL the certs upload properly. 

Now I'm having issues with Virtual host overlap, as both URLs point to the first site. I'm going to try to change it with NameVirtualHost directives.

Will keep you updated!

**Comment by hrazzell** [comment]
So adding the lines:

NameVirtualHost *:80
NameVirtualHost *:443

before including the sites-enabled folder fixed the second issue.

So everything works now. Thanks for developing this great product and supporting it with such quick responses!
