### ISSUE TITLE
Harvesting Data!

### ISSUE THREAD

**Issue by jteslaxxx** [pentestgeek/phishing-frenzy#250]
Hey Zeknox!

Hey just wanted to ask, its not issue!

How I can configure PF to harvest input data from several pages! I mean not only from page you assign when you start campaign, but for example, login.php redirects to next page where client is asket some additional information and this data would be harvested also! 

Thanks!

**Comment by zeknox** [comment]
Currently there is not a great way to handle this use case.  The current implementation is looking for parameters that were submitted with an input name of 'UsernameForm' and 'PasswordForm'. Without both of these inputs it does not send the info to the PF API.
