### ISSUE TITLE
phishing-frenzy

### ISSUE THREAD

**Issue by hardrock1234** [pentestgeek/phishing-frenzy#252]
Hi Thank you very much for such an amazing framework 

I followed your awesome Kali phishing frenzy setup and it works fine , i can load the application, i can select template and can send out emails all working fine!

The issue i have currently i click on InterlPassword checker email and say i put random password, however i do not know why i don't get the records, No tracks, no password ? 

it could be me not understanding apache properly or might be something i have done wrong . 

pf.conf 

<IfModule mod_passenger.c>
    PassengerRoot %ROOT
    PassengerRuby %RUBY
  </IfModule>

  <VirtualHost *:80>
    ServerName phishingfrenzy.local
    # !!! Be sure to point DocumentRoot to 'public'!
    DocumentRoot /var/www/phishing-frenzy/public
    RailsEnv development
    <Directory /var/www/phishing-frenzy/public>
      # This relaxes Apache security settings.
      AllowOverride all
      # MultiViews must be turned off.
      Options -MultiViews
    </Directory>
  </VirtualHost>

=================

when i click on the phishing email > i get redirects me to 82.45.15.193/?uid=PRVZJRLR however i don't get to see user clicked on the link or types in his/her password 

Much appreciate your help

**Comment by zeknox** [comment]
Likely a misconfiguration within the Application SITE URL section within the Global Settings. This URL is used as a callback server to track the clicks and other analytics.

**Comment by zeknox** [comment]
Please take a look at the troubleshooting section of the website to invoke manual click entries, there are also a number of closed tickets on here to address this question.
