### ISSUE TITLE
Running Phishing with Docker in Linux

### ISSUE THREAD

**Issue by JohnTet** [pentestgeek/phishing-frenzy#253]
I am using Linux 14.04, everything is configured perfectly fine , I have followed the instructions from phishing-frenzy website as how to download the image,

docker images command confirms that the download was successful.

The problem is when I execute this comand

sudo docker run -d -p 80:80 b00stfr3ak/ubuntu-phishingfrenzy

It just return some md5 sort of string, and nothing else.
Now what ? Is frenzy installed properly ? How can I access it now ? what are the next steps , I know something is bind to port 80 but when I do localhost in browser I just get Apache welcome page. I tried doing my internal IP as well but nothing happened.

phishing-frenzy.local doesn't return anything either, any help from here ?

Thanks

**Comment by zeknox** [comment]
Docker install is not supported at this time.
