### ISSUE TITLE
Using names in the emails

### ISSUE THREAD

**Issue by TheRapture** [pentestgeek/phishing-frenzy#254]
Is there currently a way to pass the names (First and last) to the template so that when it sends an email to each victim, that the email starts with "Hello <VictimName>," and ends with the name of the sender ?  I just wondered if there is a set of variables that I can pass to it.  Sorry if this is a noobish question and if the answer is documented somewhere else, I just couldn't find an answer, so I have to ask.

![image](https://cloud.githubusercontent.com/assets/13596679/11544633/88974ada-9908-11e5-944b-5b4a1f843568.png)

**Comment by zeknox** [comment]
The documentation addresses the `victims first name` portion of the question as located here:
http://phishingfrenzy.com/resources/getting_started#phishing_emails

Let me know if you have questions about this but I think your after the `@target.firstname` instance variable as demonstrated in the example email on the webpage.

For the second part of your question related to the From address, don't quote me on this but I also believe you can access those variables with:

- @campaign.email_settings.display_from - From
- @campaign.email_settings.from - Display From

https://github.com/pentestgeek/phishing-
frenzy/blob/master/app/mailers/phishing_frenzy_mailer.rb#L38

**Comment by TheRapture** [comment]
Fantastic!  thank you for such a quick response Brandon.  I will give it a try, and let you know if I have any further questions.
~Sean
