### ISSUE TITLE
Office 365 template

### ISSUE THREAD

**Issue by hardrock1234** [pentestgeek/phishing-frenzy#255]
Hi 

Thanks for an amazing framework.

I seem to have an issue with office 365 template . when i click on the phishing website. "www.companyname.com via an email. i get http://www.http.com headers prefix to my phishing site . 
 
i.e  the site would like this  http://www.http.com//mysite.com?uid=GZEQOO

Not entirely sure why the http://www.http.com prefix where it comes from ? 

I have pretty much looked at the code within the template, i can't really see any issues at all 

Any suggestions ?

Much appreciate it

Regards,

**Comment by zeknox** [comment]
Likely this line here:
https://github.com/pentestgeek/phishing-frenzy-templates/blob/master/office365/email/office365.html.erb#L15

**Comment by hardrock1234** [comment]
Can you advise i how to fix this ? 

I'm student learning security all slow start for me:) 
Regards,

**Comment by zeknox** [comment]
You likely just need to modify the HTML A tag to something like this:
<pre>&lta href="<%= @url %>">https://www.companyname.com&lt/a></pre>

You'll probably want to learn basic HTML before jumping into security. A good foundation will go miles...

**Comment by hardrock1234** [comment]
Awesome, thanks for that .
I will take your advise and learn  basics first :) much appreciate it .

Regards,
