### ISSUE TITLE
New Installation

### ISSUE THREAD

**Issue by daveday2** [pentestgeek/phishing-frenzy#256]
I am not able to get the application web page to display.  Everything installed correctly.  I am getting the following when running the apachectl -S command:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message

 VirtualHost configuration: 
*:80 is a NameVirtualHost 
                  default server 127.0.1.1 (/etc/apache2/sites-enabled/000-default.conf:1)
                  port 80 namevhost 127.0.1.1 (/etc/apache2/sites-enabled/000-default.conf:1) 
                  port 80 namevhost phishing-frenzy.local (/etc/apache2/pf.conf:6) 
ServerRoot: "/etc/apache2" 
Main DocumentRoot: "/var/www/html" Main 
ErrorLog: "/var/log/apache2/error.log" 
Mutex default: dir="/var/lock/apache2" mechanism=fcntl 
Mutex mpm-accept: using_defaults 
Mutex watchdog-callback: using_defaults 
PidFile: "/var/run/apache2/apache2.pid" 
Define: DUMP_VHOSTS 
Define: DUMP_RUN_CFG 
User: name="www-data" id=33 
Group: name="www-data" id=33

Any help is greatly appreciated.  Thanks.

**Comment by zeknox** [comment]
The website should be live on this FQDN:
<pre>phishing-frenzy.local</pre>

You will have to edit your hosts file or create a DNS A record to forward this english address to the numeric address.

If you use only the IP address it will hit the default website which is configured within:
<pre>/etc/apache2/sites-enabled/000-default.conf</pre>

**Comment by daveday2** [comment]
Thanks, now I get:

Mysql2::Error
Can't connect to local MySQL server through socket '/var/run/mysqld.sock'(2)

Rails.root: /var/www/phishing-frenzy

**Comment by daveday2** [comment]
I got it fixed.  Had to redo the Mysql install portion.  Thanks.
