### ISSUE TITLE
System Status

### ISSUE THREAD

**Issue by daveday2** [pentestgeek/phishing-frenzy#258]
Redis is the only item that shows green on the system status.  I have SideKiq installed and when I click on the SideKiq Console it brings it up.  It does say {DEVELOPMENT] Sidekig.  I also have the following displayed:  Your have 3 jobs enqueued, but Siekiq is not running. Thanks.

**Comment by daveday2** [comment]
Figured out the Sidekiq issue.  Apache still doesn't show as active in System Status.

**Comment by zeknox** [comment]
Yeah I think it's a bug in the way it displays the status of Apache, but if your web interface to PF is working, obviously Apache is working properly.

**Comment by slashtolau** [comment]
The apache2 issue is fixed in #266. System Status should show apache correctly.

**Comment by zeknox** [comment]
Thanks @slashtolau

**Comment by slashtolau** [comment]
Your welcome! Phishing Frenzy rocks
