### ISSUE TITLE
Statictics tracking

### ISSUE THREAD

**Issue by muffigi122** [pentestgeek/phishing-frenzy#261]
Hello, I have strange issue with stats tracking. 
Statistic tracking seems to work, but I cannot manually invoke "email opened" and "email clicked". I ask it because during actual tests I may need to troubleshoot it.

Here are the settings:
Access PF server: https://192.168.1.5
Global Settings / Application Site URL https://192.168.1.5
Campaign Options/Email Settings/ Phishing URL : http://External_IP/index.phpP
Campaign Options/Email Settings/ FQDN : External IP
Index.php is line: $url = "https:/192.168.1.5" . '/reports/results/';

Organisation where I am conducting the phishing test, can access to external IP, but cannot access to 192.168.1.5 (it is supposed to be that). Statistics under Reports is collected, but if I try to invoke hits, 
http://External_IP/reports/image/ILYQIVVW.png
http://External_IP/reports/results/?uid=ILYQIVVW

browser tells me, page cannot be found. 

If I set Application Site URL: http://External_IP, disable and enable Campaign, index.php line is changed accordingly. But, stats are not collected and to open phishing URL takes around 30 seconds. 

Does anyone have a hint how to properly set up campaign, so that stats are running in real test and I can manually invoke the hits?

Thank you

**Comment by muffigi122** [comment]
I found some hint, /etc/apache2/pf.conf seems to be a mess. only https://192.168.1.5 was allowed. Try to change that all four options are working : HTTPS and HTTP External_IP and 192.168.1.5

**Comment by zeknox** [comment]
For the stats to track properly you will want to be using a public facing FQDN that can resolve using external DNS.

If you are just testing and want to get it to work, you can setup your own FQDN and leverage hosts files to resolve the domain names properly.

You'll want to configured your pf.conf file with the FQDN you have chosen, or an public external IP address (but FQDN is intended). Any changes to this file need a restart of the Apache service to take effect.

Make sure that you modify your "Site URL" within the Admin settings to exactly what the URL is of the PF application.  This is what is used as the tracking URL for stat generation.

Also read through this, it may help:
https://www.phishingfrenzy.com/resources/troubleshooting

**Comment by muffigi122** [comment]
Zeknox, wonderful. Although I read https://www.phishingfrenzy.com/resources/troubleshooting more than 10 times, your sentence  - "Site URL" within the Admin settings to exactly what the URL is of the PF application - helped me a lot. I solved the issue and helped me to understand how your product is working.

Thank you.
