### ISSUE TITLE
Phishing URL doesn't load

### ISSUE THREAD

**Issue by cyopk** [pentestgeek/phishing-frenzy#263]
Hi guys,
Firstly just want to give a huge thanks to you zeknox for PF and for any help you may be able to give.

I've gotten PF installed and everything goes smoothly until I go to my inbox, check the phishing email and then when I click on the phishing URL instead of taking me to the "intel password checker page" it comes up with a "404 error page not found". I found a past issue similar to this but it didn't help my case.

I'm really roadblocked here and if you could help I would greatly appreciate it, I really want to get this working! Let me know what screenshots I could take to help you troubleshoot too please

Thanks!

**Comment by cyopk** [comment]
EDIT: I thought if anything a screen capture of "apachectl -S" might help, thanks again for any help :)

![apachectl -s capture](https://cloud.githubusercontent.com/assets/16647520/12372309/cc7d43b0-bca5-11e5-820a-87f31a169547.jpg)

**Comment by cyopk** [comment]
Edit: After playing around trying to fix it my apachectl -S now outputs the following:
![issuespf](https://cloud.githubusercontent.com/assets/16647520/12376425/0e5491ba-bd48-11e5-8e59-0a53cc97a71a.png)

**Comment by cyopk** [comment]
further update: when I enable the default config, typing "intel.domain.com" into the browser brings up the default apache page but when I disable default-000.conf with 'a2dissite' I get the screenshot from my previous edit and it goes back to "404 page not found" when I type "intel.domain.com" into the browser. The following screenshot is when I enable default-000.conf:
![issues](https://cloud.githubusercontent.com/assets/16647520/12380142/b4844040-bdbf-11e5-8b5f-39b38c6b142b.png)

**Comment by zeknox** [comment]
The phishing site should be live on the FQDN of `intel.domain.com` based on the screenshot above.  If it is not live, then try restarting the apache service to load in the configuration changes inside of `2.conf`.

If the page is loading but you are getting a 404, you should look at the actual configuration settings within `2.conf` to see where the DirectoryRoot is pointing and if the website files exist there.

Also use the log files to help troubleshoot your issue. They should exist within `/var/www/phishing-frenzy/logs/*`

Good Luck

**Comment by cyopk** [comment]
Thanks so much for your quick reply, i'll do my best and get back when I think I've made some progress!!

**Comment by cyopk** [comment]
After going through this today with my friend we were able to get the site up on our local computer, i.e. when I typed "intel.domain.com/index.php" into my browser the correct page displayed but then when reactivating the campaign we lost the changes we made so it might take a while but if we get it I will be sure to post the solution we came up with

**Comment by zeknox** [comment]
Sounds to me like that Phishing Frenzy application is not restarting the Apache service for you properly.  Either the command within `Global Settings` is off, or you have not granted the www-data account access within `/etc/sudoers` properly.

**Comment by cyopk** [comment]
hey zeknox ! thanks again for all your replies. So here are a few screenshots of the solution we came up with to make at least the template come up in our browser correctly. We still get a 404 error when opening the phishing url in the email unforunately.

((Soln so far)) After activating the campaign we changed the file 2.conf located at "/etc/apache2/sites-enabled/2.conf from:
![1pf](https://cloud.githubusercontent.com/assets/16647520/12445468/8b8fd4e2-bfb8-11e5-80bd-954fd5911717.png)

to:
![2pf](https://cloud.githubusercontent.com/assets/16647520/12445492/92c10a2e-bfb8-11e5-8404-b5fa4ce6150f.png)

Next, we moved the index.php file and the index2.php file from /var/www/phishing-frenzy/public/deployed/campaigns/2/ to /var/www/html/

Also, here is a screenshot of my /etc/sudoers file and global settings page:
![3pf](https://cloud.githubusercontent.com/assets/16647520/12445718/17ab15b2-bfba-11e5-9219-1aa5a63581d5.png)

![4pf](https://cloud.githubusercontent.com/assets/16647520/12445737/3e5182aa-bfba-11e5-95fd-e68b5300a0e7.png)

**Comment by zeknox** [comment]
I keep forgetting that the 404 is expected behavior. You need to add any UID parameter to the URL and the phishing site will load.

This is to keep people from browsing the site without a UID. Add something like ?UID=aaaaaa to the end.

Brandon

**Comment by cyopk** [comment]
Ok cool, it all seems to work well locally except for tracking user clicks and passwords now. I know there are some other issues on this already so I'll go through them when I get time and try to solve it. Thanks Brandon! I'll open a new one about tracking if for some reason I can't work it out!

**Comment by zeknox** [comment]
Make sure that end users are able to resolve whatever FQDN you have placed within Admin -> Global Settings, this is used as a callback server to send the HTTP POST requests to the API for tracking stats.

**Comment by cyopk** [comment]
Thanks for your help it seems to be working now, at the moment I'm now stuck with some tracking issues but if I have a problem will open another ticket. Thanks again !!! :)

**Comment by xander4588** [comment]
I also ran into this issue, what fixed the issue for me was changing the permissions on the files in "/var/www/phishing-frenzy/public/deployed/campaigns/2".

**Comment by Cxtr011** [comment]
Firstly - props zeknox, appreciate your effort and delivering such a great tool.  

I'm having a similar issue and was hoping for some insight.  Initially i was able to get PF off the ground quickly and setup SSL for the main site.  My campaigns come online and send out emails quite smooth, where it seems i am having issues is i need to restart my ubuntu server for the sites to respond to the email link.  I was thinking potentially something related to the apache restart though when i run just that, the site does not work.    I am able to work around this but appreciate any feeback.

Also the tracking does not seem to work.  My campaign sites are child sites of the global admin site, i.e. my primary site for example is phishingfrenzy.local and my campaigns are pf.phishingfrenzy.local.

Thanks in advance!!

**Comment by zeknox** [comment]
@Cxtr011 one thing you want to be certain about is each campaign should have a uniq FQDN to hose the phishing site properly.  If you create 2 Campaigns with the same FQDN it won't know which phishing site to load when a target falls onto the site.

Another thing to keep in mind is that a domain on the primary site like phishingfrenzy.local typically will not work in the real world since this domain does not actually resolve to the IP address of your PF box.

The way you need to configure PF is with a valid domain that you own. Make sure that domain is configured with a DNS A record which points to the IP address of the PF interface. Once this is working properly you can configure your FQDN of the main site into the "Global Settings" > "Site URL".  This is the URL that is used as a callback API to track your analytics.  This is likely why your stats are never tracking.

**Comment by Cxtr011** [comment]
zeknox - Thanks for the quick response!!  

Sorry for not clarifying but my primary site is publically accessible setup with a DNS record....the phishingfrenzy.local was just for example though i realize considering the .local not a good example. 

Re my campaigns I've been created a different child records per each campaign i am running as i realized that they would potentially conflict even if i used a different landing page.

Specifically with the linkedin template, i've customized my email definitions but all else is as is from the pf template repository.  

After launching and rebooting my server, the campaigns come online and the sites work.  I get to my bogus linkedin login page and throw some login details and neither those details nor the actually click are logged.  

I do see both index.php and login-submit.php in the deployed campaign folder.  Any other things you would recommend I check?

**Comment by zeknox** [comment]
The problem where you have to restart the box or restart Apache manually, that sounds like a permissions issue where www-data accounts doesn't have the ability to reload apache when a campaign goes active.  Make sure your `/etc/sudoers` file is configured properly to grant this permission.

There are some steps on the troubleshooting page that you should try out to make sure you can manually invoke a click event:  https://www.phishingfrenzy.com/resources/troubleshooting

**Comment by Cxtr011** [comment]
Gotcha....odd thing is I manually throw a restart and the sites don't function until i reboot.

So i just noticed i think the click and credential harvesting may be specific to the linked profile as I noticed the eFax is able to track.  I noticed that page and will walk through it some more.

Thanks much!!

**Comment by zeknox** [comment]
Strange indeed.  If a campaign is active it should be live.  If it's not, a sudo restart of the apache service I would think should load all configured virtual hosts.  You can see your apache virtual host configuration with `apachectl -S`

**Comment by Cxtr011** [comment]
Hmmm, so i am using SSL for the main site which it immediately gets redirected to.  the record is under 443 in pf.conf, should i enter an equivalent for port 80?  

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server 127.0.1.1 (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost 127.0.1.1 (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost pf.xxx.com (/etc/apache2/sites-enabled/1.conf:2)
                 alias pf.xxx.com
         port 80 namevhost efax.xxx.com (/etc/apache2/sites-enabled/4.conf:2)
                 alias efax.xxx.com
*:443                  xxx.com (/etc/apache2/pf.conf:6)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex watchdog-callback: using_defaults
Mutex ssl-stapling: using_defaults
Mutex ssl-cache: using_defaults
Mutex default: dir="/var/lock/apache2" mechanism=fcntl
Mutex mpm-accept: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33
Group: name="www-data" id=33

**Comment by zeknox** [comment]
You only have one virtual hosts configured for HTTPS and it's not the main PF interface site like it should be.
<pre>*:443 xxx.com (/etc/apache2/pf.conf:6)</pre>

**Comment by Cxtr011** [comment]
Appreciate all the feedback.  
I'm using xxx.com as the main, and the campaigns are child domains of that, pf.xxx.com.  Do they need to be completely different records, i.e. is the child/parent naming causing an issue?  Should i use yyy.com for the campaigns, or am i missing you completely?

**Comment by Cxtr011** [comment]
Thanks Zeknox....I used an alternate domain record for the campaign and it is rocking and rolling.

To confirm for anyone else: Looks like the child record was the issue.  I was using xxx.com as my main PF interface site, and abc.xxx.com for the campaigns.  I changed the campaigns to use yyy.com and the tracking is now working.

**Comment by zeknox** [comment]
Thanks for the feedback!

**Comment by Cxtr011** [comment]
Thanks for all your help.....and especially for such a great tool!!!

Btw....i've compiled some additional notes for an ubuntu install.  Happy to share/update the notes if you like....of course once i get the campaign sites launching automatically ;)

Do you know if there any other repositories or other users who have created some additional templates?  I'm interested in working to build that out.
