### ISSUE TITLE
Installation confusion

### ISSUE THREAD

**Issue by n0x00** [pentestgeek/phishing-frenzy#265]
Hey, this installation guide doesn't like Kali rolling (latest) 

what version of kali was used for the guide to succeed ?

I've had no success with docker or kali now hehe

please helps.

**Comment by zeknox** [comment]
Need more info here, you have not given enough specifics to offer assistance.

**Comment by n0x00** [comment]
I've ended up using something else, I really wanted to use PF having seen it in action but, for me getting it working on the platforms that I tried was to time consuming. I'll close this ticket, maybe if someone else in in the same situation i was in they might pose the question better. good luck with PF i'll be keeping my eye on it :)
