### ISSUE TITLE
BeEF and GeoIP

### ISSUE THREAD

**Issue by zildac** [pentestgeek/phishing-frenzy#269]
Hi,

 May be a stupid question but I can't  see any option in the PF UI to display the World Map with GeoIP info from BeEF (as per antisnatchors commits). I have enabled GeoIP in BeEF and also also enabled PF integration in config.yaml. However I see no info relating to PF in BeEF or vice versa. Am I missing something obvious?

**Comment by antisnatchor** [comment]
hey @zildac my pull request was never merged actually ;-)

**Comment by zildac** [comment]
Thanks @antisnatchor. I should have read the comments more thoroughly :-) So I guess I can use your PF fork (beef-love) to obtain this functionality....
