### ISSUE TITLE
problem in sidekiq

### ISSUE THREAD

**Issue by el-mdarhri** [pentestgeek/phishing-frenzy#270]
hi ,

after launch this command : bundle axec sidekiq -C config/sidekiq

it remains blocked in this phase 
![image](https://cloud.githubusercontent.com/assets/17147126/13053067/5437d750-d3fa-11e5-8683-676c9e7da615.png)

log sidekiq :
![image](https://cloud.githubusercontent.com/assets/17147126/13053123/9d63c6a0-d3fa-11e5-8fa5-73120c091add.png)

2016-02-15T11:10:03.055Z 5982 TID-115jyk DEBUG: Celluloid::Condition signaled spuriously
        /var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/manager.rb:215:in `shutdown'
        /var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/manager.rb:107:in `block in processor_died'
        /var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/util.rb:16:in `watchdog'
        /var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/manager.rb:96:in `processor_died'
        /var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:15:in `block in call'
        /var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
        /var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
        /var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
        /var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'

thank you in advance

**Comment by zeknox** [comment]
Never seen this error TBH.  I would ensure that you are running Sidekiq in the same environment (development or production) as the application is running under to ensure it's not an issue with that.

**Comment by ccammilleri** [comment]
I had the very same issue. I can confirm what @zeknox mentioned, that specifying the matching environment does fix this. For me I was in production and the following worked:

`rvmsudo bundle exec sidekiq -C config/sidekiq.yml -e production`

**Comment by ccammilleri** [comment]
also, if you are demonizing sidekiq with the script provided from installation instructions, consider adding rvmsudo to the start_cmd within the init script.
