### ISSUE TITLE
Did I do something wrong ?

### ISSUE THREAD

**Issue by RobsonMr** [pentestgeek/phishing-frenzy#271]
![captura de tela de 2016-02-26 07-31-37](https://cloud.githubusercontent.com/assets/1574794/13349861/2e42aa70-dc5b-11e5-9d37-15535650a3bb.png)

**Comment by zeknox** [comment]
This is the default landing page for a rails application. It almost seams like the pf.conf is pointing to the wrong directory and serving up a different rails app?

**Comment by iHasanYK** [comment]
i'm stuck on this point too, the default landing page in pf.conf in my current configuration file is:
    DocumentRoot /var/www/phishing-frenzy/public
    RailsEnv development
    <Directory /var/www/phishing-frenzy/public>

is there anything else can cause this problem ?!

**Comment by zeknox** [comment]
Start looking at some apache logs to see if a different VHOST or something is getting leveraged.  Logs should be located at `/var/log/apache2/*`
