### ISSUE TITLE
Not able to install PF in Kali Rolling

### ISSUE THREAD

**Issue by CrazianT3k** [pentestgeek/phishing-frenzy#273]
The **passenger-install-apache2-module** script requires **apache2-threaded-dev** as a dependency which is not on the Kali Rolling repository.  I tried doing the following:

- added the debian main weezy repository to the /etc/apt/sources.list.d directory
- apt-get clean
- apt-get update
- apt-get install apache2-threaded-dev

and I get this error:

Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apache2-threaded-dev : Depends: apache2.2-common (= 2.2.22-13+deb7u6) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Please let me know if there is a work around.

Thanks in advance!

**Comment by zeknox** [comment]
Based on the error messages above apt wants to ensure apache2.2-common is installed.  Can you run this to determine what version of apache is installed?

<pre>dpkg -l | grep apache</pre>

**Comment by CrazianT3k** [comment]
Thanks for the speedy reply!

Here are the results:

ii  apache-users                                                2.1-1kali2                          amd64        Enumerate usernames on systems with Apache UserDir module
ii  apache2                                                     2.4.18-1                            amd64        Apache HTTP Server
ii  apache2-bin                                                 2.4.18-1                            amd64        Apache HTTP Server (modules and other binary files)
ii  apache2-data                                                2.4.18-1                            all          Apache HTTP Server (common files)
ii  apache2-utils                                               2.4.18-1                            amd64        Apache HTTP Server (utility programs for web servers)
ii  libapache2-mod-dnssd                                        0.6-3.1                             amd64        Zeroconf support for Apache 2 via avahi
ii  libapache2-mod-php5                                         5.6.17+dfsg-3                       amd64        server-side, HTML-embedded scripting language (Apache 2 module)

**Comment by zeknox** [comment]
Any difference if you try aptitude instead of apt?

<pre>aptitude install apache2-threaded-dev</pre>

**Comment by CrazianT3k** [comment]
I got the following error:

bash: aptitude: command not found

I forgot to add earlier, I tried to install apache2.2-common I got additional dependency errors.

I'm currently fixing the broken packages by doing apt-get clean, etc...

**Comment by zeknox** [comment]
I've never seen this issue before, but it could be something new with the latest version of Kali. Initially I feel like something may be borked with your apt package manager perhaps?

**Comment by CrazianT3k** [comment]
I don't think so, I initially only had kali rolling repositories added to my sources.list.  I checked out the apache version included to Rolling and it doesn't contain **apache2-threaded-dev**

See below for link:
http://pkg.kali.org/news/160800

I tried adding the sana respositories to my main sources list earlier, but then decided to look for the debian one and add it to the sources.list.d directory so I don't dork up my install.

Have you been able to install PF onto the Kali Rolling edition successfully yet?

Thanks!

**Comment by zeknox** [comment]
I have not installed PF on the latest version of Kali

**Comment by CrazianT3k** [comment]
Ok, so maybe I would need to do the following:

- add kali sana repos into the sources.list.d directory

- uninstall apache2

- reinstall apache2-common?

- Pray that nothing breaks :)

**Comment by zeknox** [comment]
Sounds like a decent course of action.  Just keep a copy of your original sources in case you want to reinstall apache back.

**Comment by CrazianT3k** [comment]
Thanks for the help!

**Comment by zeknox** [comment]
Certainly, keep us posted and if you find a workaround I can document that on the Kali install guides.

**Comment by iHasanYK** [comment]
i have been stuck on this point, i have used apt-get install apache2-dev, PF is still not working properly with me to confirm that this is a correct command :S

**Comment by 0x776b7364** [comment]
FWIW, I replaced

```
apt-get install apache2-threaded-dev
```

with

```
apt-get install apache2-dev
```

and it seems to work. See also: http://stackoverflow.com/questions/2939670/phusion-passenger-on-ubuntu-10-04-why-apache2-prefork-dev-when-we-want-apache2

**Comment by CrazianT3k** [comment]
Nice!  Thanks @0x776b7364 !  I ended up building a Ubuntu box to host PF, but I'll try this in my lab.

**Comment by iHasanYK** [comment]
i have been stuck with many issues in kali linux, ubuntu is much better to use PF, go for it, it's much better and more stable

**Comment by 0x776b7364** [comment]
I've created a Kali Rolling install script which works for me. https://github.com/0x776b7364/kali-scripts/blob/master/install-phishing-frenzy.sh. Hope this helps.
