### ISSUE TITLE
Incorrect dafault page

### ISSUE THREAD

**Issue by iHasanYK** [pentestgeek/phishing-frenzy#274]
Hi,

thank you for sharing this great tool, i have run all commands and i have faced multiple issue during installation, i have solve all of them but this one i couldn't

when i open https://<serverIP> it sends me to index page which shows the following:
Index of /
[ICO]	Name	Last modified	Size	Description
[TXT]	404.html	2016-03-04 20:29 	728 	 
[TXT]	422.html	2016-03-04 20:29 	711 	 
[TXT]	500.html	2016-03-04 20:29 	643 	 
[IMG]	favicon.ico	2016-03-04 20:29 	0 	 
[TXT]	index_default.html	2016-03-04 20:29 	5.8K	 
[DIR]	javascripts/	2016-03-04 20:29 	- 	 
[TXT]	robots.txt	2016-03-04 20:29 	26 	 
[DIR]	stylesheets/	2016-03-04 20:29 	- 	 
[DIR]	templates/	2016-03-04 20:29 	- 	 
[IMG]	tracking_pixel.png	2016-03-04 20:29 	95 	 
[DIR]	uploads/	2016-03-04 20:29 	- 	 

may you please help me in redirecting the server to the correct page ?!

many thanks in advance.

**Comment by zeknox** [comment]
Take a look at the result of `apachectl -S` and see what websites are configured for :443 and what directory root they are pointing too.

**Comment by iHasanYK** [comment]
thanks for reply zeknox, 

here is the result of apachectl -S 
root@kali:/etc/apache2/sites-enabled# apachectl -S
VirtualHost configuration:
*:80                   phishing-frenzy.hmg.local (/etc/apache2/sites-enabled/000         -default.conf:1)
*:443                  phishing-frenzy.hmg.local (/etc/apache2/pf.conf:7)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex watchdog-callback: using_defaults
Mutex ssl-stapling-refresh: using_defaults
Mutex ssl-stapling: using_defaults
Mutex ssl-cache: using_defaults
Mutex default: dir="/var/lock/apache2" mechanism=fcntl
Mutex mpm-accept: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33
Group: name="www-data" id=33


when i click on "about your application's environment" it says: 
Not Found

The requested URL /rails/info/properties was not found on this server.
Apache/2.4.18 (Debian) Server at 192.168.100.6 Port 443

![pf error 1](https://cloud.githubusercontent.com/assets/17649207/13535388/ed77b206-e24a-11e5-9c00-178d4d91643f.JPG)

thanks again :)

**Comment by zeknox** [comment]
Restart your apache just to make sure all configurations have been loaded properly.  Then for testing this out, edit your hosts file and add `phishing-frenzy.hmg.local` to point to the IP address of the PF box.

Looks like the FQDN if hit properly by name should serve up pf.conf.

**Comment by iHasanYK** [comment]
is the main DocumenRoot path correct ?!

**Comment by zeknox** [comment]
I don't believe the `main DocumenRoot path` plays a roll in this equation because the `DcoumentRoot` that really does matter is what you have defined within pf.conf.

Any chance you can post pf.conf as well?

**Comment by iHasanYK** [comment]
that's great
yes sure, here is my pf.conf

<IfModule mod_passenger.c>
    PassengerRoot %ROOT
    PassengerRuby %RUBY
  </IfModule>

  <VirtualHost *:443>
    ServerName phishing-frenzy.hmg.local

    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/pf.crt
    SSLCertificateKeyFile /etc/apache2/ssl/pf.key

    # !!! Be sure to point DocumentRoot to 'public'!
    DocumentRoot /var/www/phishing-frenzy/public
    RailsEnv development
    <Directory /var/www/phishing-frenzy/public>
      # This relaxes Apache security settings.
      AllowOverride all
      # MultiViews must be turned off.
      Options -MultiViews
    </Directory>
  </VirtualHost>

**Comment by zeknox** [comment]
Yeah I don't see any issues with your pf.conf.  Just make sure you don't have anything in the tags that is binding it to port 80.  It would look something like `*:80`

**Comment by iHasanYK** [comment]
only apache2 is bind with it 
root@kali:/etc/apache2# netstat -plant
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1958/mysqld
tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN      643/redis-server *:
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1462/sshd
tcp        0     64 192.168.100.6:22        192.168.100.3:6768      ESTABLISHED 12808/sshd: root@pt
tcp        0      0 127.0.0.1:58124         127.0.0.1:6379          ESTABLISHED 12768/sidekiq 3.3.3
tcp        0      0 127.0.0.1:6379          127.0.0.1:58126         ESTABLISHED 643/redis-server *:
tcp        0      0 192.168.100.6:22        192.168.100.3:6392      ESTABLISHED 2109/sshd: root@pts
tcp        0      0 127.0.0.1:6379          127.0.0.1:58124         ESTABLISHED 643/redis-server *:
tcp        0      0 127.0.0.1:58126         127.0.0.1:6379          ESTABLISHED 12768/sidekiq 3.3.3
tcp6       0      0 :::443                  :::*                    LISTEN      13003/apache2
tcp6       0      0 :::6379                 :::*                    LISTEN      643/redis-server *:
tcp6       0      0 :::80                   :::*                    LISTEN      13003/apache2
tcp6       0      0 :::22                   :::*                    LISTEN      1462/sshd

**Comment by zeknox** [comment]
Alright, I'm pretty convinced this is an issue with passenger not actually rendering your VirtualHost (pf.conf) properly.

Ensure that you have installed passenger properly, and likely needed to add the 3 lines to the bottom of your apache.conf file.

Also try removing the Passenger tags at the top of pf.conf, restart apache and see if it makes any difference.

**Comment by iHasanYK** [comment]
by running this command "passenger-install-apache2-module", right ?!

**Comment by zeknox** [comment]
Correct, you would want to make sure that install ran properly, and I believe at the end of the install it asks you to include 3 lines to the apache.conf file.

**Comment by iHasanYK** [comment]
i have done it. but unfortunately, it didnt work :( 
i have seen wiki in your video, but i can't find it, is it different in comparison to the installation procedure listed in the website phishingfrenzy.com ?!

**Comment by zeknox** [comment]
Can you confirm you have 3 lines within your apache.conf file that you added after you ran the passenger install script?  Yes this is part of the install guide, but it's not a command you run so it's ofter overlooked when reading the guide.

**Comment by iHasanYK** [comment]
i have made sure that the 3 lines are existing before ending the passenger installation, 
i have been using setoolkit and cloned some websites, if i browse http://serverIP it shows up the cloned website by setoolkit, if i browse https://serverIP it shows the index list mentioned in my question above

**Comment by zeknox** [comment]
If your getting the directory index, that leads me to believe that passenger is not rendering the website properly.  Passenger is what is required to actually interpret the ruby code properly, which is why you get a list of files.

**Comment by iHasanYK** [comment]
and btw, httpd.conf is empty

**Comment by iHasanYK** [comment]
maybe something like here http://stackoverflow.com/questions/21207033/rails-app-only-displaying-public-directory-with-passenger ?

**Comment by zeknox** [comment]
Yes, absolutely, maybe you want to try reinstalling passenger against with rvmsudo?

Wrong way : sudo passenger-install-apache2-module

Right way : rvmsudo passenger-install-apache2-module

**Comment by iHasanYK** [comment]
Thank you very much zeknox, i will keep trying until i find the problem and solve it, i will update you once i find a solution :) :+1:

**Comment by iHasanYK** [comment]
and i do apologize for taking much of your time

**Comment by iHasanYK** [comment]
Zeknox, which version of ruby we can use other than 2.1.5 ?! does make any difference if i use 2.3.0 ?!

**Comment by iHasanYK** [comment]
i have re-installed everything on ubuntu 14, i have used other resources to install rvm properly, i can now open the web page when i run 'rails server' in /var/www/phishing-frenzy

however, im still facing some issue in cloning website.

thank you for your great efforts Zeknox :)
