### ISSUE TITLE
Sidekiq 3.3.3 does not support Ruby 1.9 error , yet I have 2.1.5 running.

### ISSUE THREAD

**Issue by JohnJuan** [pentestgeek/phishing-frenzy#275]
Good evening, 

So, i have spent some time trying to figure this out on my own and had to resort to posting on here.  when I run rvm list, it shows that I am running ruby-2.1.5.  However, if I try running "rake templates:load", I receive the following: 

johnjuan@ubuntu:/var/www/phishing-frenzy$ rake templates:load
rake aborted!
Sidekiq 3.3.3 does not support Ruby 1.9.
/var/lib/gems/1.9.1/gems/sidekiq-3.3.3/lib/sidekiq.rb:3:in `<top (required)>'
/var/www/phishing-frenzy/config/application.rb:5:in `<top (required)>'
/var/www/phishing-frenzy/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
johnjuan@ubuntu:/var/www/phishing-frenzy$ rvm list

rvm rubies

=* ruby-2.1.5 [ x86_64 ]

I am nearing the end of installing/configuring this ans was going strong without needing help on previous steps lol.  I did get stuck a couple of times but Google helps :)  I am unable to figure out this issue though.  I would appreciate any help.  

This is the part of the installation process that I am currently on.  

System Configuration

Edit the sudoers file (likely located at /etc/sudoers) to ensure the www-data account can reload apache. Insert a line similar to that shown below.

www-data ALL=(ALL) NOPASSWD: /etc/init.d/apache2 reload

Load the Efax and Intel default templates for PF using the rake helper

$ rake templates:load

# => - current
# =* - current && default
#  * - default

Prior to this step I have gone through these: 
$ bundle install
$ bundle install --deployment
$ rake db:migrate
$ rake db:seed
Everything installed correctly.  I even got this message: 
Post-install message from prawn:

  ********************************************

  A lot has changed recently in Prawn.

  Please read the changelog for details:

  https://github.com/prawnpdf/prawn/wiki/CHANGELOG

  ********************************************

Any help would be greatly appreciated.  

Thank you, 
John

**Comment by zeknox** [comment]
Try starting your sidekiq instance with bundle exec?
<pre>$ bundle exec sidekiq</pre>

**Comment by JohnJuan** [comment]
Thanks for the prompt response.  I then get the same error.  

johnjuan@ubuntu:/var/www/phishing-frenzy$ bundle exec sidekiq
/var/www/phishing-frenzy/vendor/bundle/ruby/1.9.1/gems/sidekiq-3.3.3/lib/sidekiq.rb:3:in `<top (required)>': Sidekiq 3.3.3 does not support Ruby 1.9. (RuntimeError)
	from /var/www/phishing-frenzy/vendor/bundle/ruby/1.9.1/gems/sidekiq-3.3.3/lib/sidekiq/cli.rb:10:in `require'
	from /var/www/phishing-frenzy/vendor/bundle/ruby/1.9.1/gems/sidekiq-3.3.3/lib/sidekiq/cli.rb:10:in `<top (required)>'
	from /var/www/phishing-frenzy/vendor/bundle/ruby/1.9.1/gems/sidekiq-3.3.3/bin/sidekiq:3:in `require_relative'
	from /var/www/phishing-frenzy/vendor/bundle/ruby/1.9.1/gems/sidekiq-3.3.3/bin/sidekiq:3:in `<top (required)>'
	from /var/www/phishing-frenzy/vendor/bundle/ruby/1.9.1/bin/sidekiq:23:in `load'
	from /var/www/phishing-frenzy/vendor/bundle/ruby/1.9.1/bin/sidekiq:23:in `<main>'
johnjuan@ubuntu:/var/www/phishing-frenzy$

**Comment by zeknox** [comment]
What happens when you run `rvm list` and `ruby -v`

**Comment by JohnJuan** [comment]
johnjuan@ubuntu:/var/www/phishing-frenzy$ rvm list

rvm rubies

=* ruby-2.1.5 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

johnjuan@ubuntu:/var/www/phishing-frenzy$ ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
johnjuan@ubuntu:/var/www/phishing-frenzy$

**Comment by zeknox** [comment]
Weird, looks like the ruby 2.1.5 is installed but it't not being leveraged by the bash shell.

Can you try running `rvm --default use 2.1.5` and then type `rvm list` again

**Comment by JohnJuan** [comment]
That is what I was thinking.  I just don't have the skills to troubleshoot this YET.  

johnjuan@ubuntu:/var/www/phishing-frenzy$ rvm --default use 2.1.5

RVM is not a function, selecting rubies with 'rvm use ...' will not work.

You need to change your terminal emulator preferences to allow login shell.
Sometimes it is required to use `/bin/bash --login` as the command.
Please visit https://rvm.io/integration/gnome-terminal/ for an example.

johnjuan@ubuntu:/var/www/phishing-frenzy$

**Comment by zeknox** [comment]
It looks like your RVM hasn't fully installed or you need to re-initialize a new bash shell to load RVM as part of it.  Currently RVM is not functioning properly because of this.  If you do a simple restart or even logoff / login it may just start working.

If it does not start working you likely need to edit your .bash_profile file and add something like `source ~/.rvm/scripts/rvm` to load RVM when bash is started.

**Comment by JohnJuan** [comment]
Alright.  I am going to try restarting real quick.  brb

**Comment by JohnJuan** [comment]
So now I am getting this message:
johnjuan@ubuntu:/var/www/phishing-frenzy$ rake templates:load
Could not find rake-10.4.2 in any of the sources
Run `bundle install` to install missing gems.
johnjuan@ubuntu:/var/www/phishing-frenzy$ 

So it looks like i need run bundle install again?

**Comment by zeknox** [comment]
Yes, run `bundle install` as indicated. This is because RVM is likely loading the proper 2.x version of ruby which has never installed the required gems before.

**Comment by JohnJuan** [comment]
Thanks for your your help man.  I really appreciate it.  

Alright, it's doing its thing.  Do i complete the following as well once this is complete?

bundle install --deployment
 rake db:migrate
 rake db:seed

**Comment by JohnJuan** [comment]
johnjuan@ubuntu:/var/www/phishing-frenzy$ rake db:migrate
rake aborted!
You have already activated rake 10.1.0, but your Gemfile requires rake 10.4.2. Prepending `bundle exec` to your command may solve this.
/home/johnjuan/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:34:in `block in setup'
/home/johnjuan/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:19:in `setup'
/home/johnjuan/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:121:in `setup'
/home/johnjuan/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/setup.rb:7:in `<top (required)>'
/var/www/phishing-frenzy/config/boot.rb:6:in `<top (required)>'
/var/www/phishing-frenzy/config/application.rb:1:in `<top (required)>'
/var/www/phishing-frenzy/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
johnjuan@ubuntu:/var/www/phishing-frenzy$

**Comment by zeknox** [comment]
<pre>$ bundle exec rake db:migrate</pre>

**Comment by JohnJuan** [comment]
That seems to have worked!  So after this, is there anything else that i need to do before going back to the system configuration stage and loading the templates with rake templates:load ?

johnjuan@ubuntu:/var/www/phishing-frenzy$ bundle exec rake db:migrate== 20130525213800 CreateCampaigns: migrating ==================================
-- create_table(:campaigns)
   -> 0.0038s
-- add_index("campaigns", "template_id")
   -> 0.0118s
== 20130525213800 CreateCampaigns: migrated (0.0160s) =========================

== 20130527203608 CreateTemplates: migrating ==================================
-- create_table(:templates)
   -> 0.0055s
-- add_index("templates", "campaign_id")
   -> 0.0104s
== 20130527203608 CreateTemplates: migrated (0.0167s) =========================

== 20130607140912 CreateAdmins: migrating =====================================
-- create_table(:admins)
   -> 0.0028s
== 20130607140912 CreateAdmins: migrated (0.0030s) ============================

== 20130615234648 CreateCampaignSettings: migrating ===========================
-- create_table(:campaign_settings)
   -> 0.0088s
-- add_index("campaign_settings", "campaign_id")
   -> 0.0115s
== 20130615234648 CreateCampaignSettings: migrated (0.0208s) ==================

== 20130616161250 CreateEmailSettings: migrating ==============================
-- create_table(:email_settings)
   -> 0.0030s
-- add_index("email_settings", "campaign_id")
   -> 0.0145s
== 20130616161250 CreateEmailSettings: migrated (0.0179s) =====================

== 20130621213836 CreateStatistics: migrating =================================
-- create_table(:statistics)
   -> 0.0032s
== 20130621213836 CreateStatistics: migrated (0.0035s) ========================

== 20130623010640 CreateVictims: migrating ====================================
-- create_table(:victims)
   -> 0.0046s
== 20130623010640 CreateVictims: migrated (0.0048s) ===========================

== 20131026191507 CreateGlobalSettings: migrating =============================
-- create_table(:global_settings)
   -> 0.0076s
== 20131026191507 CreateGlobalSettings: migrated (0.0079s) ====================

== 20131112215256 CreateSmtpCommunications: migrating =========================
-- create_table(:smtp_communications)
   -> 0.0033s
-- add_index("smtp_communications", "campaign_id")
   -> 0.0085s
== 20131112215256 CreateSmtpCommunications: migrated (0.0124s) ================

== 20131114150136 AddCommandApacheStatusToGlobalSettings: migrating ===========
-- add_column(:global_settings, :command_apache_status, :string)
   -> 0.0142s
== 20131114150136 AddCommandApacheStatusToGlobalSettings: migrated (0.0145s) ==

== 20131114175733 AddTestEmailToCampaign: migrating ===========================
-- add_column(:campaigns, :test_email, :string)
   -> 0.0058s
== 20131114175733 AddTestEmailToCampaign: migrated (0.0062s) ==================

== 20131115173841 AddDeviseToAdmins: migrating ================================
-- change_table(:admins)
   -> 0.0592s
-- add_index(:admins, :email, {:unique=>true})
   -> 0.0179s
-- add_index(:admins, :reset_password_token, {:unique=>true})
   -> 0.0156s
== 20131115173841 AddDeviseToAdmins: migrated (0.0933s) =======================

== 20131115212342 AddApprovedToAdmin: migrating ===============================
-- add_column(:admins, :approved, :boolean, {:default=>false, :null=>false})
   -> 0.0045s
-- add_index(:admins, :approved)
   -> 0.0079s
== 20131115212342 AddApprovedToAdmin: migrated (0.0127s) ======================

== 20131204204849 CreateVersions: migrating ===================================
-- create_table(:versions)
   -> 0.0028s
-- add_index(:versions, [:item_type, :item_id])
   -> 0.0128s
== 20131204204849 CreateVersions: migrated (0.0207s) ==========================

== 20131207180630 CreateBlasts: migrating =====================================
-- create_table(:blasts)
   -> 0.0025s
== 20131207180630 CreateBlasts: migrated (0.0027s) ============================

== 20131214014942 AddCommandApacheVhostsToGlobalSettings: migrating ===========
-- add_column(:global_settings, :command_apache_vhosts, :string, {:default=>"apache2ctl -S"})
   -> 0.0103s
== 20131214014942 AddCommandApacheVhostsToGlobalSettings: migrated (0.0107s) ==

== 20131214025854 AddAsynchronousToGlobalSettings: migrating ==================
-- add_column(:global_settings, :asynchronous, :boolean, {:default=>false})
   -> 0.0051s
== 20131214025854 AddAsynchronousToGlobalSettings: migrated (0.0054s) =========

== 20131216174057 CreateVisits: migrating =====================================
-- create_table(:visits)
   -> 0.0027s
-- add_index(:visits, :victim_id)
   -> 0.0120s
== 20131216174057 CreateVisits: migrated (0.0151s) ============================

== 20131216180010 AddFieldsToVisit: migrating =================================
-- add_column(:visits, :browser, :string)
   -> 0.0073s
-- add_column(:visits, :ip_address, :string)
   -> 0.0038s
-- add_column(:visits, :extra, :string)
   -> 0.0037s
== 20131216180010 AddFieldsToVisit: migrated (0.0151s) ========================

== 20131216180144 AddUidToVictim: migrating ===================================
-- add_column(:victims, :uid, :string)
   -> 0.0134s
== 20131216180144 AddUidToVictim: migrated (0.0136s) ==========================

== 20131218020440 CreateBaits: migrating ======================================
-- create_table(:baits)
   -> 0.0030s
== 20131218020440 CreateBaits: migrated (0.0033s) =============================

== 20131219033338 CreateAttachments: migrating ================================
-- create_table(:attachments)
   -> 0.0050s
-- add_index(:attachments, :attachable_id)
   -> 0.0156s
== 20131219033338 CreateAttachments: migrated (0.0210s) =======================

== 20131219045315 AddFunctionToAttachment: migrating ==========================
-- add_column(:attachments, :function, :string, {:default=>"website"})
   -> 0.0040s
== 20131219045315 AddFunctionToAttachment: migrated (0.0042s) =================

== 20131220204833 AddMoreToEmailSettings: migrating ===========================
-- add_column(:email_settings, :openssl_verify_mode, :string)
   -> 0.0053s
-- add_column(:email_settings, :domain, :string)
   -> 0.0133s
-- add_column(:email_settings, :authentication, :string)
   -> 0.0042s
-- add_column(:email_settings, :enable_starttls_auto, :boolean)
   -> 0.0036s
== 20131220204833 AddMoreToEmailSettings: migrated (0.0269s) ==================

== 20131222200357 AddDirectoryIndexToTemplates: migrating =====================
-- add_column(:templates, :directory_index, :string)
   -> 0.0040s
== 20131222200357 AddDirectoryIndexToTemplates: migrated (0.0042s) ============

== 20140109211528 ChangeDataTypeForCampaignId: migrating ======================
-- change_table(:victims)
   -> 0.0084s
== 20140109211528 ChangeDataTypeForCampaignId: migrated (0.0098s) =============

== 20140429034353 AddNamesToVictims: migrating ================================
-- add_column(:victims, :firstname, :string)
   -> 0.0053s
-- add_column(:victims, :lastname, :string)
   -> 0.0041s
== 20140429034353 AddNamesToVictims: migrated (0.0096s) =======================

== 20140506021435 AddArchiveToVictim: migrating ===============================
-- add_column(:victims, :archive, :boolean, {:default=>false})
   -> 0.0080s
-- add_column(:victims, :sent, :boolean, {:default=>false})
   -> 0.0037s
== 20140506021435 AddArchiveToVictim: migrated (0.0119s) ======================

== 20140624025030 CreateClones: migrating =====================================
-- create_table(:clones)
   -> 0.0026s
== 20140624025030 CreateClones: migrated (0.0028s) ============================

== 20140706224849 AddDelayToCampaignSettings: migrating =======================
-- add_column(:campaign_settings, :smtp_delay, :integer, {:default=>0})
   -> 0.0123s
== 20140706224849 AddDelayToCampaignSettings: migrated (0.0125s) ==============

== 20140724034738 CreateHarvestedEmails: migrating ============================
-- create_table(:harvested_emails)
   -> 0.0032s
-- add_index(:harvested_emails, :email_search_id)
   -> 0.0081s
== 20140724034738 CreateHarvestedEmails: migrated (0.0117s) ===================

== 20140724035900 CreateEmailSearches: migrating ==============================
-- create_table(:email_searches)
   -> 0.0078s
-- add_index(:email_searches, :harvested_email_id)
   -> 0.0122s
== 20140724035900 CreateEmailSearches: migrated (0.0207s) =====================

== 20140724073404 AddBingApiToGlobalSettings: migrating =======================
-- add_column(:global_settings, :bing_api, :string)
   -> 0.0040s
== 20140724073404 AddBingApiToGlobalSettings: migrated (0.0042s) ==============

== 20140730212703 AddOriginalToHarvestedEmail: migrating ======================
-- add_column(:harvested_emails, :original, :string)
   -> 0.0116s
== 20140730212703 AddOriginalToHarvestedEmail: migrated (0.0117s) =============

== 20140910021300 AddBeefUrlToCampaignSettings: migrating =====================
-- add_column(:campaign_settings, :beef_url, :string)
   -> 0.0037s
== 20140910021300 AddBeefUrlToCampaignSettings: migrated (0.0039s) ============

== 20140910021338 AddBeefUrlToGlobalSettings: migrating =======================
-- add_column(:global_settings, :beef_url, :string)
   -> 0.0039s
== 20140910021338 AddBeefUrlToGlobalSettings: migrated (0.0041s) ==============

== 20140916202808 AddSitesEnabledToGlobalSettings: migrating ==================
-- add_column(:global_settings, :sites_enabled_path, :string, {:default=>"/etc/apache2/sites-enabled"})
   -> 0.0148s
-- remove_column(:global_settings, :path_apache_httpd)
   -> 0.0038s
== 20140916202808 AddSitesEnabledToGlobalSettings: migrated (0.0189s) =========

== 20141111055919 CreateSsls: migrating =======================================
-- create_table(:ssls)
   -> 0.0105s
== 20141111055919 CreateSsls: migrated (0.0107s) ==============================

== 20141111063547 AddSslToCampaignSettings: migrating =========================
-- add_column(:campaign_settings, :ssl, :boolean)
   -> 0.0074s
== 20141111063547 AddSslToCampaignSettings: migrated (0.0075s) ================

== 20150415015416 AddBaitsCountToBlasts: migrating ============================
-- add_column(:blasts, :baits_count, :integer, {:default=>0})
   -> 0.0042s
== 20150415015416 AddBaitsCountToBlasts: migrated (0.0127s) ===================

== 20150415021923 AddRefreshTimeToGlobalSettings: migrating ===================
-- add_column(:global_settings, :reports_refresh, :integer, {:default=>15})
   -> 0.0044s
== 20150415021923 AddRefreshTimeToGlobalSettings: migrated (0.0047s) ==========

== 20150515010202 CreateActivities: migrating =================================
-- create_table(:activities)
   -> 0.0032s
-- add_index(:activities, [:trackable_id, :trackable_type])
   -> 0.0126s
-- add_index(:activities, [:owner_id, :owner_type])
   -> 0.0115s
-- add_index(:activities, [:recipient_id, :recipient_type])
   -> 0.0078s
== 20150515010202 CreateActivities: migrated (0.0361s) ========================

== 20150515012820 AddAdminIdToModels: migrating ===============================
-- add_reference(:campaigns, :admin, {:index=>true, :foreign_key=>true})
   -> 0.0227s
-- add_reference(:templates, :admin, {:index=>true, :foreign_key=>true})
   -> 0.0195s
== 20150515012820 AddAdminIdToModels: migrated (0.0425s) ======================

== 20150714194319 AddReplytoToEmailSettings: migrating ========================
-- add_column(:email_settings, :reply_to, :string)
   -> 0.0050s
== 20150714194319 AddReplytoToEmailSettings: migrated (0.0053s) ===============

== 20150718022848 ChangeDefaultAsynchronousValueInGlobalSettings: migrating ===
-- change_column(:global_settings, :asynchronous, :boolean, {:default=>true})
   -> 0.0029s
== 20150718022848 ChangeDefaultAsynchronousValueInGlobalSettings: migrated (0.0178s) 

== 20150718023513 AddSiteUrlToGlobalSettings: migrating =======================
-- add_column(:global_settings, :site_url, :string, {:default=>"https://phishingfrenzy.local"})
   -> 0.0047s
== 20150718023513 AddSiteUrlToGlobalSettings: migrated (0.0050s) ==============

johnjuan@ubuntu:/var/www/phishing-frenzy$

**Comment by zeknox** [comment]
Any updates here, looks like your migrations ran properly.

**Comment by JohnJuan** [comment]
Sorry I have been at work all day.  Trying "rake templates: load" gives me this error now: 

johnjuan@ubuntu:/var/www/phishing-frenzy$ rake templates:load
rake aborted!
You have already activated rake 10.1.0, but your Gemfile requires rake 10.4.2. Prepending `bundle exec` to your command may solve this.
/home/johnjuan/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:34:in `block in setup'
/home/johnjuan/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:19:in `setup'
/home/johnjuan/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:121:in `setup'
/home/johnjuan/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/setup.rb:7:in `<top (required)>'
/var/www/phishing-frenzy/config/boot.rb:6:in `<top (required)>'
/var/www/phishing-frenzy/config/application.rb:1:in `<top (required)>'
/var/www/phishing-frenzy/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
johnjuan@ubuntu:/var/www/phishing-frenzy$

**Comment by zeknox** [comment]
Read this error, you need to pre-pend `bundle exec` in front of any of your ruby commands cause otherwise it wants to use you're ruby 1.9.x it seems like.  The `bundle exec` from within the phishing-frenzy directory should ensure that RVM is used with your proper ruby version for the app.

**Comment by JohnJuan** [comment]
Ahhh I see.  So I need to run "bundle exec rake templates: load" ?

I'll try that when I have some time.  I am still at work for another 2 hours :/

**Comment by JohnJuan** [comment]
It worked!!  

So I am getting closer to finishing this.  When I try to run sudo apachectl start, I get this message: 

johnjuan@ubuntu:/var/www/phishing-frenzy$ sudo apachectl start
[sudo] password for johnjuan: 
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
httpd (pid 1369) already running

I figured out the first error.  I added "ServerName localhost"   line to the Apache2.conf and then the error went away.  
But I am still getting the (httpd (pid 1369) already running message.

**Comment by JohnJuan** [comment]
Learning is occurring!  httpd pid 1369 is the Apache server and it is already running.  Great! 

I am getting the Apache Server default page when i go to local host.  How do I get to the Admin Global settings page?  Sorry I am asking so many questions...

**Comment by zeknox** [comment]
Closing out the ticket since main issue has been resolved.

You get to the Global Settings page from the Nav bar within the UI.
