### ISSUE TITLE
Global setting url error

### ISSUE THREAD

**Issue by foliwe** [pentestgeek/phishing-frenzy#276]
I get this error when i go to the Admin => Global settings link. I don't know that i did wrong

![selection_001](https://cloud.githubusercontent.com/assets/7389818/13610425/8d4a2c66-e555-11e5-8b97-c4d1447a94df.png)

**Comment by zeknox** [comment]
Have you seeded your database?

**Comment by foliwe** [comment]
Thanks so much. I had a broken migration .i rolled it back and forgot to migrate again.

**Comment by zeknox** [comment]
Yup, It seemed like a migration wasn't in place or the DB hadn't been seeded properly.  Feel free to close the ticket if your issue is solved.

**Comment by foliwe** [comment]
one  more question. What should my Application Site URL be like?. are the defaults ok?
Thanks

**Comment by zeknox** [comment]
The application url is going to be specific for your environment.  So whatever the public facing url is going to be is what you need in that input.

Example might be phishing.phishingfrenzy.com if you owned the phishingfrenzy.com domain.

**Comment by foliwe** [comment]
ok . so i put http://phishing.com 
Since that is my local domain

**Comment by zeknox** [comment]
You can put whatever you like, but you're going to want to have a public domain that is resolvable by all your targets otherwise you'll never track the metrics automatically.

**Comment by foliwe** [comment]
ok Thanks So i think is better for me to register a public domain name
Thanks so much for your help

**Comment by foliwe** [comment]
Do i have to close the ticket ?

**Comment by zeknox** [comment]
Ticket closed.
