### ISSUE TITLE
Not able to collect data/feedbacks

### ISSUE THREAD

**Issue by foliwe** [pentestgeek/phishing-frenzy#277]
Hi i manage to install PF instance on my machine, But for some reason when i n tried to create a campaign i have a missing template error. I used the $ rake templates:load, the message was still the same. So i created a campaign anywhere to try to figure out the isssue. But when i launched the campaign, Everything blowout. This is my  apachectl -S output.

 AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server phishing.com (/etc/apache2/sites-enabled/4.conf:2)
         port 80 namevhost phishing.com (/etc/apache2/sites-enabled/4.conf:2)
                 alias http://phishing.com
         port 80 namevhost phishing.com (/etc/apache2/pf.conf:6)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex watchdog-callback: using_defaults
Mutex default: dir="/var/lock/apache2" mechanism=fcntl 
Mutex mpm-accept: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33 not_used
Group: name="www-data" id=33 not_used

The application is not loading any more, the page loads with a 404 Page Not Found error

**Comment by zeknox** [comment]
It looks like you are defining the phishing url to that identical of the application url (with global settings).  I guess It's not exactly clear in the docs, but you never want to use the same FQDN as the application url.

You need to configure the campaign with a uniq name such as `phish1.phishing.com` in your case.

Regarding your templates issue.  When you view the templates#index page, can you see any templates in the list?

**Comment by foliwe** [comment]
efax and intel password checker

**Comment by zeknox** [comment]
Within your campaign options you should now be able to select a template, then click save. This should be all that is required to use the templates.

**Comment by foliwe** [comment]
ok. so how do i get the app up and running again to make changes ?

**Comment by zeknox** [comment]
Remove the file within `/etc/apache2/sites-enabled/*.conf` which in your case I believe is 4.conf.

Alternatively, you can
<pre>$ a2disite</pre>

Then select the site causing problems. Reload apache. Test.

**Comment by foliwe** [comment]
ok .  now working. i will create another campaign and tell you the result.
Before i say anything more. i wish to tell you that you are a wonderful person.
I which i could offer you a beer

**Comment by zeknox** [comment]
thanks for the kind words, glad its working well, enjoy.

**Comment by foliwe** [comment]
i lauched the campaign this time , no errors. but i receive no mail

**Comment by zeknox** [comment]
Take a look at the details of your emails within the recent blasts section within the campaign settings.  The timestamp is clickable to see the status code of the emails it attempted.

**Comment by foliwe** [comment]
All has got SMTP Failures. hmmmm

**Comment by foliwe** [comment]
i used gmail smtp with my gmails details for the SMTP settings. is that enough to send emails?

**Comment by zeknox** [comment]
Sometimes you need to enable some stuff within the Gmail UI.  Login and see if there are any notifications.  I know some guys had issues sending through Gmail in some previous tickets here on github.  Forgot what the workaround was atm.

**Comment by foliwe** [comment]
Hi i finally used my sendgrid account and it works successfully. The email came to my junk. but i will figured that later following your Docs on email spam.
May issue is when i click on the link am redirected to a blank page.

**Comment by zeknox** [comment]
It's likely an old template that no longer works properly.  View the
source of the White page to see if it yields anything, or modify the
HTML to something simple like "TEST" to see if it is present when viewing.

**Comment by foliwe** [comment]
There is something am not getting right here.
In the emails Setting, What is the 
Phishing URL:
and
FQDN:
i own a free domain name. How can i use it? I have been sending these campaigns and clicking them, but my report still shows 0 clicks.
I use my free domain on the Phishing URL: in the email settings and a made up domain on the FQDN field the same address i used in the FQDN in the general settings.

**Comment by foliwe** [comment]
i have been trying to make my phishing links work, i watched your video on setting a new campaign on youtube. your links have the UID at the end. i can't get that to work.  when i hover my mouse over the link in the emails, i have a very very very long link like this  

https://u2319295.ct.sendgrid.net/wf/click?upn=cEEL29sAnORacXJwE9KfUP0jsqZSk56Y5PD2dE7OYd-2BqoAXgvlSxqcHrOdX63zZFdi0-2F3edbQDrJG622NaovdQ-3D-3D_7
4uG6pHWugDcyl1zAtZlyaWdaBzZl-2Br8KII9-2F845fXnARj0kGHu7 ..............etc
 when i click on it,  it displays the "Sorry, we could not find http".

![selection_002](https://cloud.githubusercontent.com/assets/7389818/13652762/f1e1c9ea-e645-11e5-8023-640aff75f1d1.png)
![selection_003](https://cloud.githubusercontent.com/assets/7389818/13652774/fb04bb90-e645-11e5-85c0-f01f0c161d39.png)

**Comment by Meatballs1** [comment]
goto your sendgrid web portal and disable the sendgrid tracking

**Comment by zeknox** [comment]
Yup, what he said.  Looks like sendgrid is rewriting your links to something of their own.

**Comment by foliwe** [comment]
Ok . i did i disable the emial tracking on sendgrid. 
How the link url on the email changes. to http//from...... and not http(://from........ with the column.
So when i click on the email link,  it flashes for a second and again goes to an error page

**Comment by zeknox** [comment]
Look at modifing the HTLM a tag within the e-mail template whatever protocol you want (http:// or https://)

**Comment by foliwe** [comment]
This is my tag
<a href="http://<%= @url %>">
Iam try to use the simple template you create on your tutorial.
I change my setting to this. 
![selection_005](https://cloud.githubusercontent.com/assets/7389818/13681009/0c9bb5d6-e6f3-11e5-88ab-6bfd314a2ff0.png)

it looks ok. but still no feeback when i click or enter data
I also realizes that after the first attempt of entering the data to the form, when the pages redirects me to the process page , the uid = nill like this
http://fromfoli.comxa.com/process.php?uid=

**Comment by foliwe** [comment]
i have change all setting possible but i just can't get tracking and data collection

**Comment by foliwe** [comment]
Help please .im getting frustrated making this app tracks clicks, open, and collect data. after many weeks i still don't get it.
Here is the screen shots of all my configuration. What am i doing wrong . All the emails have the uid attact to them. but when the target click, open and fills the form, i get no results. Please Help.

                          # Here is the screen shots of all my configuration
![selection_007](https://cloud.githubusercontent.com/assets/7389818/13706646/db80ec72-e79d-11e5-80e7-ed4afe776af8.png)
## Email settings
![selection_009](https://cloud.githubusercontent.com/assets/7389818/13706653/e1e17dfc-e79d-11e5-84e8-b13391c17f76.png)
## Pf.conf
![selection_010](https://cloud.githubusercontent.com/assets/7389818/13706660/e9d138f4-e79d-11e5-83f0-84de090254b3.png)
## application.rb
![selection_011](https://cloud.githubusercontent.com/assets/7389818/13706667/f3c0b9f2-e79d-11e5-9ff9-55df5349a323.png)

**Comment by zeknox** [comment]
Have you tried to manually invoke a click event using the troubleshooting guide?
https://www.phishingfrenzy.com/resources/troubleshooting

What was the result of manually visiting these URL listed in the guide?

**Comment by foliwe** [comment]
http://fromfoli.comxa.com/reports/results/?uid=VDGZLNJX
404 page not found

**Comment by zeknox** [comment]
And if you visit just: http://fromfoli.comxa.com/ do you get the PF login page?

**Comment by foliwe** [comment]
no. i get the the live wesite

**Comment by zeknox** [comment]
That is your problem.  You need to use the URL for tracking that is what you use to login to the PF site.  Replace your PF FQDN with the tracking URL you tried above.

**Comment by foliwe** [comment]
i did that. but when i visite the Url, it takes me to the live site.

**Comment by foliwe** [comment]
should i have something in the httpd.conf file?

**Comment by zeknox** [comment]
Then you must have configured your campaign with the same FQDN of the PF application.  This is not possible, you need to have your campaign with a unique FQDN that is different from the PF application.

**Comment by foliwe** [comment]
ok thanks. i will try that now.  Hope the application.rb file is ok. look above

**Comment by zeknox** [comment]
Actually the newest version of PF does not use the application.rb SITE_URL.  Instead that was moved out to the Application URL within the Global Settings.

**Comment by foliwe** [comment]
How i can get to the PF login page. when i enter the url, it takes me to the life site

## PF.CONF

<IfModule mod_passenger.c>
    PassengerRoot %ROOT
    PassengerRuby %RUBY
  </IfModule>

<VirtualHost *:80>
    ServerName   http://fromfoli.comxa.com/ 
    # !!! Be sure to point DocumentRoot to 'public'!
    DocumentRoot /var/www/phishing.com/public
    RailsEnv development
    <Directory /var/www/phishing.com/public>
      # This relaxes Apache security settings.
      AllowOverride all
      # MultiViews must be turned off.
      Options -MultiViews
    </Directory>
  </VirtualHost>

HOSTS.
127.0.0.1       http://fromfoli.comxa.com/
127.0.0.1       localhost
127.0.1.1       devlpm-X555LJ

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

**Comment by zeknox** [comment]
You need to show the result of `apachectl -S` to see all of your VirtualHosts configured on the system.

**Comment by foliwe** [comment]
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server fromfoli.comxa.com (/etc/apache2/sites-enabled/9.conf:2)
         port 80 namevhost fromfoli.comxa.com (/etc/apache2/sites-enabled/9.conf:2)
                 alias fromfoli.comxa.com
         port 80 namevhost fromfoli.comxa.com/ (/etc/apache2/pf.conf:6)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex default: dir="/var/lock/apache2" mechanism=fcntl 
Mutex mpm-accept: using_defaults
Mutex watchdog-callback: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33 not_used
Group: name="www-data" id=33 not_used

**Comment by zeknox** [comment]
Alright, now I want YOU to look over this list so you understand whats going on here.  Notice how the FQDN for `fromfoli.comxa.com ` is configured for both pf.conf and 9.conf?  Well Apache does not know which website to serve up once you hit this URL so it serves the one at the top of the list.

What you need to do to get the PF login page back is disable the website for 9.conf.  This can be done using some apache commands:
<pre>$ a2disite 9.conf</pre>

Restart Apache and your pf.conf site should be served up on that FQDN.

**Comment by foliwe** [comment]
Ok .in which directory should i be in before i use the command  a2disite 9.conf
because i get and error " command not found"
OR
can't i just delete it

**Comment by zeknox** [comment]
Yes you can just delete the .conf file if you'd like and restart the apache service.

**Comment by foliwe** [comment]
I deleted the file, restarted the apache2 server but still when i enter the url i still go to the live website
i can't understand
VirtualHost configuration:
*:80                   fromfoli.comxa.com/ (/etc/apache2/pf.conf:6)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex watchdog-callback: using_defaults
Mutex default: dir="/var/lock/apache2" mechanism=fcntl 
Mutex mpm-accept: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33 not_used
Group: name="www-data" id=33 not_used

**Comment by zeknox** [comment]
Looks from the results above only pf.conf is configured, so whatever you have defined in that file is what is going to be served up.  Ensure you restarted apache, ensure your not loading from browser cache.

**Comment by foliwe** [comment]
i even used a new private window. still no good

**Comment by foliwe** [comment]
## nslookup
> fromfoli.comxa.com
Server:		127.0.1.1
Address:	127.0.1.1#53

Non-authoritative answer:
Name:	fromfoli.comxa.com
Address: 31.170.160.209
> 

## Hosts File
127.0.0.1       http://fromfoli.comxa.com/ 
127.0.0.1	localhost
127.0.1.1	devlpm-X555LJ
localhost    http://fromfoli.comxa.com/

 The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
Really i don't what to do

**Comment by foliwe** [comment]
i cant get to the login page only with my internal IP

**Comment by foliwe** [comment]
Hi sorry for the time .
I change my host file to 12.0.0.1 formfoli.comax.com. so i can now reach the login page.
But another problem was when i blast a campaign, the clicks are redirected to my loopback address. which does not exit.

**Comment by zeknox** [comment]
Closing since we have gotten away from the originally solved issue, please create new ticket if you still have issues.
