### ISSUE TITLE
Website Cloning is not working properly

### ISSUE THREAD

**Issue by iHasanYK** [pentestgeek/phishing-frenzy#278]
Hi

i have checked the issues reported regarding website cloning, this error is generated when i try to clone a website:
ActiveRecord::StatementInvalid in ClonesController#create 

can it be solved by using such a solution ?!
http://stackoverflow.com/questions/21334092/activerecordstatementinvalid-in-userscontrollercreate-when-i-use-sorcery-gem

**Comment by iHasanYK** [comment]
Extracted source (around line #56):

54
55
56
57
58
59
          

	


    respond_to do |format|
      if @clone.save
        format.html { redirect_to clones_path, notice: 'Clone was successfully created.' }
        format.json { render json: @clone, status: :created, location: @clone }
      else

**Comment by iHasanYK** [comment]
Rails.root: /var/www/phishing-frenzy
Application Trace | Framework Trace | Full Trace

app/controllers/clones_controller.rb:56:in `block in create'
app/controllers/clones_controller.rb:55:in `create'

Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"tbCPR80BNvxeg9Cwpiy3rTsh9baV2R5HbCIvchoqUnY=",
 "clone"=>{"name"=>"HMG - FB Campaign",
 "url"=>"https://www.facebook.com"},
 "commit"=>"Clone Website"}

**Comment by zeknox** [comment]
Thanks for the bug report, we are actually looking to remove the site cloning functionality because it has a number of bugs which would require a big refactor to not store the cloned data within the db due to size restraints.

**Comment by xwareinnovations** [comment]
try this fix
https://github.com/pentestgeek/phishing-frenzy/issues/170#issuecomment-244424213

**Comment by zeknox** [comment]
We are going to be removing the website cloning functionality in future versions.
