### ISSUE TITLE
Ubuntu Installation doc

### ISSUE THREAD

**Issue by foliwe** [pentestgeek/phishing-frenzy#279]
Is the ubuntu Installation tutorial working or something have been change . How is this different from the kali installation
can i follow it to success?

**Comment by iHasanYK** [comment]
i have combined between the steps in phishing frenzy website and the steps here 
https://gorails.com/setup/ubuntu/14.04

after you finish installation, you just need to go to document root (/var/www/phishing-frenzy) and start rails by typing this command 'rails server'

dont forget also to run sidekiq too in a separate console by the typing the command 
rvmsudo bundle exec sidekiq -C config/sidekiq.yml

the only part that didnt work with me is website cloning :S

**Comment by foliwe** [comment]
did you add this in the pf.conf file
<IfModule mod_passenger.c>
    PassengerRoot %ROOT
    PassengerRuby %RUBY
  </IfModule>
beacuse the ubuntu installation did not mentioned it

**Comment by iHasanYK** [comment]
No, i didnt add them

**Comment by foliwe** [comment]
i have no issues installing rails app. the isssue is making them work with apache2

**Comment by iHasanYK** [comment]
i have followed the steps in gorails.com to install it, and then i did the same in phishingfrenzy.com

**Comment by foliwe** [comment]
@iHasanYK  i want to ask how did to resolve the FQDN to be your phising-frenzy login page. 
and how and were did you host the website files on the templates.

**Comment by iHasanYK** [comment]
i didnt start implementing it with FQDN, but i guess it's a linux and network thing

**Comment by zeknox** [comment]
Closing for now, please re-open if this did not solve your issue.
