### ISSUE TITLE
Just a little help with php files in rails application

### ISSUE THREAD

**Issue by foliwe** [pentestgeek/phishing-frenzy#280]
I used noip.com for my FQDN.  so my computer is my server
 My phising url is mynoipaddress.com/index.php. 
where  and how can i upload the index.php file for the phising url on my computer.

**Comment by magickangaroo** [comment]
You add the index.php (landing page presumably for a clickable link), to the template.  You then bind the template to a campaign.  Take a look at https://www.phishingfrenzy.com/resources/documentation.  The create a template section.

**Comment by zeknox** [comment]
You need to use the templates section of the application.  You can upload files to the application.  Files that are of the type "Website" will be deployed into the webroot of your phishing site when the campaign has been activated.
