### ISSUE TITLE
Email Test error

### ISSUE THREAD

**Issue by iHasanYK** [pentestgeek/phishing-frenzy#281]
hi,

i have faced this issue, what does it cause it ?!
The action 'test_email' could not be found for EmailController

many thanks in advance :)

**Comment by magickangaroo** [comment]
Lo, sounds like you may not have you included a test email within the campaign settings?

**Comment by zeknox** [comment]
Could you please update us if you're still having issues.  This error is stating that the test_email action does not exist within the Controller, however it does exist.
