### ISSUE TITLE
Phishing Frenzy don't tracking clicks

### ISSUE THREAD

**Issue by tempmoto8** [pentestgeek/phishing-frenzy#283]
Hi there,
I have correctly installed phishing frenzy suite, but when I lunch the campaign, the tool don't tracking clicks, even the user activity.
Click report is showed only when I manually visit the link http://[host]/reports/results/?uid=[validUID]. 

I have to set something up in the template code? How works the monitoring of clicks?
Can help me?

I followed the https://www.phishingfrenzy.com/resources/troubleshooting page but I don't find a solution.
Thanks in advantage.

Addition information:
- Template used: https://github.com/pentestgeek/phishing-frenzy-templates/tree/master/office365
- Back end address (PF console): $IP
- Front end (template deployed): $name.domain (domain resolved of $IP)
- The logs are correctly registered to /pf/log/www-campaign*.log

Best regards.

**Comment by zeknox** [comment]
If the click event shows up properly when you manually trigger it through the URL the API is functioning properly. This tells me that we most likely have an issue with the application URL that you have configured within the Global Settings.

Make sure that this application URL is in alignment with that of the PF interface URL to track clicks. This URL is what is used as a callback location to track each click once a phishing site is loaded.

**Comment by tempmoto8** [comment]
Thanks for quick response.
The application site URL is set to http://$IP (and not $name.domain), so I thinks it's corrected... Right?

**Comment by zeknox** [comment]
Could very well be the issue. A quick test is if you use the http://$IP does the PF login page appear?  If so, it might work, if not, you know thats your issue.

**Comment by tempmoto8** [comment]
Yes, if I visit the http://$IP, appears the PF login page.

**Comment by zeknox** [comment]
Then I would think it "can" work with the IP address.
