### ISSUE TITLE
Cannot run rails app after i installed PF

### ISSUE THREAD

**Issue by foliwe** [pentestgeek/phishing-frenzy#284]
Hi  have  issues running new rails app with the webrick server after i installed PF
When i run the rails s command., i have an error like this 
 _/home/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/socket.rb:206:in `bind': Cannot assign requested address - bind(2) for 92.xxx.xx.xx:3000 (Errno::EADDRNOTAVAIL.....
from /home/user/.rvm/gems/ruby-2.2.3/gems/spring-1.6.4/lib/spring/binstub.rb:11:in `<top (required)>'
	from /home/user/apps/user/bin/spring:13:in `require'
	from /home/user/apps/user/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'_

**Comment by zeknox** [comment]
First thing, webrick is not considered a production web server. Secondly, this is because you already have something binded to port 3000, likely another instance of webrick running.

**Comment by foliwe** [comment]
i used this  lsof -i :3000 command to list my ports. and there is nothing running on port 3000.

**Comment by zeknox** [comment]
Reboot the box and see if the issue persists.  Its a port > 1024 so it shouldn't need elevated privs to bind I would think.
