### ISSUE TITLE
smtp issue

### ISSUE THREAD

**Issue by hardrock1234** [pentestgeek/phishing-frenzy#285]
Hi

Thanks for brilliant tool - currently i have issue with sending email to target user - from and target all populated correctly google smtp setting is set correctly ect the issue is when i click test or launch i do not get the test email,  no target or smtp failure error or 0 & 0   
we are not behind any Firewall  with direct connection 

Any ideas what's going on ?

Regards,

**Comment by zeknox** [comment]
Make sure sidekiq is running and processing the jobs properly. If you don't have sidekiq running it won't send any emails by default.

Brandon

**Comment by hardrock1234** [comment]
Thanks for reply ,  Actually sidekiq is running but still not able to send emails - Any other ideas ? 

Regards,

**Comment by zeknox** [comment]
Monitor the sidekiq console when you launch a campaign.  You should see
that a job gets added to the queue?  Also make sure your sidekiq is
running in the proper environment (e.g. development, production) that is
defined within your pf.conf apache file.

**Comment by hardrock1234** [comment]
Brilliant, i will double check that and let you know, 

Regards

**Comment by hardrock1234** [comment]
Hi Brandon, 

Just checked the sidekiq console - when we clicked on test /launch campaign we did not see any changes & the pf.conf is set to production - we tried different mail services i.e  gmail, godaddy, outlook with no luck, any other suggestions ?
Regards,

**Comment by hardrock1234** [comment]
Quick update : Still not able to send emails, here is dump from sidekiq.log 

==


/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:75:in `execute_job'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/logging.rb:24:in `with_context'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:132:in `call'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:51:in `block in process'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:98:in `stats'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:50:in `process'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
root@kali:/var/www/phishing-frenzy/log# 

Any ideas? much appreciate it! 

Regards

**Comment by zeknox** [comment]
No ideas initially.  It looks like your running ruby 2.1.0?  Not that it probably matters, but I think that is a different version than what has been tested.

Also, are you sure that you started sidekiq with the proper env?  Example might look like this when inside `/var/www/phishing-frenzy`:
<pre>
$ RAILS_ENV=production rvmsudo bundle exec sidekiq -C config/sidekiq.yml
</pre>

**Comment by hardrock1234** [comment]
root@kali:/var/www/phishing-frenzy/log# rvm --version
rvm 1.26.11 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
===========
Ruby 
root@kali:/var/www/phishing-frenzy/log# ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-lin

Pretty sure the sidekiq started with proper env 

Regards, 
Regards,

**Comment by hardrock1234** [comment]
Sorry for bold previous comments , here is more logs on sidekiq 

/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:75:in `execute_job'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/logging.rb:24:in `with_context'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:132:in `call'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:51:in `block in process'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:98:in `stats'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:50:in `process'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
2016-03-23T22:32:42.832Z 7847 TID-14ksos INFO: Received USR1, no longer accepting new work
2016-03-23T22:32:42.833Z 7847 TID-14ksos INFO: Terminating 25 quiet workers
2016-03-23T22:32:47.834Z 7847 TID-14ksos INFO: Received USR1, no longer accepting new work
2016-03-23T22:32:47.835Z 7847 TID-14ksos INFO: Terminating 0 quiet workers

Regards,

**Comment by hardrock1234** [comment]
Any other ideas ? i actually reinstalled ph from scratch & all Apache dependencies and yet still having smtp failing to send emails?

Regards,

**Comment by zeknox** [comment]
Within the Global Settings, change the "Background Emails" to uncheck and save.  Then try to test an email to yourself and see if it is sending properly in the foreground.

**Comment by hardrock1234** [comment]
Aha Thanks it worked :+1:  what was the issue, still can't get my head around this

**Comment by zeknox** [comment]
Well we still haven't solved the root issue of sending emails with sidekiq.  What you have changed is sending emails in the foreground which does not leverage sidekiq.  This is fine, but the thing you need to know is that when you are sending email to large number of targets it will hang the app when sending, you just need to be mindful of this and not cancel out the sending.

**Comment by hardrock1234** [comment]
Ok well thanks very much for your continues help and clear instructions, i will keep that in mind :) 

Have great day!

Regards,
