### ISSUE TITLE
Question regarding System Status #258 (daveday2)

### ISSUE THREAD

**Issue by beanious** [pentestgeek/phishing-frenzy#286]
Hello, I am having similar issues to daveday2. Redis is the only item that shows green on the system status. I have SideKiq installed and when I click on the SideKiq Console it brings it up. It does say {DEVELOPMENT] Sidekig. I was wondering if daveday2 or anyone can comment as to what they did to fix the system status issue with sidekiq and apache, both actually load despite being grey. Thank you.

**Comment by zeknox** [comment]
This is simply a parsing bug.  Don't lose sleep over it as both services are probably running fine.
