### ISSUE TITLE
<?php echo $uid ? & none registered clicks and texts 

### ISSUE THREAD

**Issue by newdays** [pentestgeek/phishing-frenzy#287]
Hi There, 
We have recently installed and configured your phishing framework, 2 issues here 

Say when we use linkedin or Intel password checker template , when we click the sent link to victim we get some of html code output & second when we type a text into input box e.g password or any ticket we  this <?php echo $uid ?  and click doesn't get registered or input texts .

Is this a bug or something to do with our configurations ? any ideas or suggestions ?

Thank you 

Aland

**Comment by zeknox** [comment]
Sounds to me like the PHP code is not rendering properly.  Make sure you have PHP installed and working properly with apache.

**Comment by newdays** [comment]
Thanks for super quick reply, framework is installed on default kali installation, 
Any particulate version or library should we be installing ?

Regards,

Aland

**Comment by zeknox** [comment]
PHP5 should be the version you would want.

**Comment by newdays** [comment]
PHP5 is already installed on kali linux

**Comment by zeknox** [comment]
Have you validated that the module is enabled within apache?  Have you created a test php snippet to ensure that PHP is rendering properly within the OS?

**Comment by newdays** [comment]
Good point , i have not done any validations, but will do now :)  Cheers :+1:

**Comment by newdays** [comment]
Here is the list of module on my local apache 

Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php5_module (shared)
 setenvif_module (shared)
 status_module (shared)
 passenger_module (shared)
 
Actually it did render a test case correctly 

Regards, 
Aland

**Comment by newdays** [comment]
This is solid framework - it worked, actually the issue was with site_url :)  Thanks
