### ISSUE TITLE
Tracking Statistics from @image_url

### ISSUE THREAD

**Issue by kizzmyanthia** [pentestgeek/phishing-frenzy#290]
I have been able to successfully install, run, and collect analytics from emails sent and clicked on, but I am unable to get the @image_url string to properly render within the email application.

I also tried calling the $uid parameter as $uid.png, but I am not sure where the image file actually resides and when directing to something like "http://phishingfrenzy.local/reports/image/$uid.png" I receive a 404 error.

This, albeit, is not a HUGE breaking thing and I LOVE the PF UI and functionality, but it would be really sweet to get this one final function working properly.

Thanks ahead of time.

**Comment by zeknox** [comment]
$UID is not suppose to be literal, this is suppose to be the actual UID of the target / victim ID.  Test it out again with the actual UID (e.g. 123456.png) and report back.

**Comment by zeknox** [comment]
Closing for now, please re-open if this did not solve your issue.
