### ISSUE TITLE
HTA_powershell can't establish connection with msfconsole.

### ISSUE THREAD

**Issue by xcolacho** [pentestgeek/phishing-frenzy#291]
Hi, first of all my english isn't good enough, so sorry about that. I'm trying to do a hta powershell attack with Phishing-Frenzy and beEF. I run the HTA powershell in BeEF and the pop up in IE appears, but when I click on Open metasploit recieves nothing. I just set up the file /beef/extensions/social_engineering/config.yaml and modify this:

powershell:

#the default payload being used is windows/meterpreter/reverse_https
msf_reverse_handler_host: "192.168.1.35"
msf_reverse_handler_port: "443"
powershell_handler_url: "/ps" 

Should I modify something in this /beef/modules/social_engineering/hta_powershell/module.rb ?

ps_url = @configuration.get('beef.extension.social_engineering.powershell.powershell_handler_url')

return [
    {'name' => 'domain', 'ui_label' => 'Serving Domain (BeEF server)', 'value' => "#{base_host}" },
    {'name' => 'ps_url', 'ui_label' => 'Powershell/HTA handler', 'value' => "#{ps_url}"}
]

Or maybe in /usr/share/beef/extensions/social_engineering/powershell/bind_powershell.rb ?

This is what I see in BeEF:

![converted_file_092f0d36](https://cloud.githubusercontent.com/assets/18465597/14555660/b38f3f02-02eb-11e6-80dd-7138e3c92a38.jpg)

In Windows open a fast shell and then a blank screen like this:

![captura3](https://cloud.githubusercontent.com/assets/18465597/14555647/9faa36a4-02eb-11e6-8361-00a9289e8d25.jpeg)

I hope you understand and can help me. Thanks.

**Comment by Meatballs1** [comment]
The beef log says it will be retrieved from `/ps/ps.png` and your screenshot shows it at `/ps/hta`. I would investigate that first :o

**Comment by xcolacho** [comment]
Thanks for your quick reply. I also realized they don't have the same path.. buy I have no idea what I have to change. Im new with this. Thanks.

**Comment by Meatballs1** [comment]
Althought I think that it is just the powershell not the HTA that is served from `/ps/ps.png`.

**Comment by xcolacho** [comment]
it seems so... but I don't know where is hta served. I'm a little bit lost xD

**Comment by xcolacho** [comment]
SOLVED. I finally did it. I figured out that in the file: beef/extensions/social_engeniering/powershell/bind_powershell.rb was a line: "payload_url" I changed this and work perfect. Thanks.
