### ISSUE TITLE
vHost issues

### ISSUE THREAD

**Issue by Miketmclaughlin** [pentestgeek/phishing-frenzy#297]
Hi,

Again, thanks for creating such an awesome tool! I have the pf server up and running perfectly, however tyhe vHosts don't appear to be working. pf seems to set apache correctly but when browsing to the phishing site I just get a 404. I have the pf interface on https://phishing-mgmt.abc.com, and the phishing page on http://phishing.abc.com. This is my apachectl -S (anonymised):

VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server ip-192-168-100-11.eu-west-1.compute.internal (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost ip-192-168-100-11.eu-west-1.compute.internal (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost phishing.abc.com (/etc/apache2/sites-enabled/2.conf:2)
                 alias phishing.abc.com
*:443                  phishing-mgmt.abc.com (/etc/apache2/pf.conf:6)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex watchdog-callback: using_defaults
Mutex ssl-stapling: using_defaults
Mutex ssl-cache: using_defaults
Mutex default: dir="/var/lock/apache2" mechanism=fcntl 
Mutex mpm-accept: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33 not_used
Group: name="www-data" id=33 not_used

**Comment by zeknox** [comment]
Pass in a UID parameter in the URL and it will work. Read the troubleshooting docs off the website.

Brandon

**Comment by Miketmclaughlin** [comment]
Perfect, thanks!
