### ISSUE TITLE
Phishing site forced to run over HTTP

### ISSUE THREAD

**Issue by david-hacklabs** [pentestgeek/phishing-frenzy#301]
Hi.
In order to track results, the "/reports/results/" URL for the phishing site is running over HTTPS when the PF web app is running over HTTPS.

So if you set up a phishing site over HTTP, the tracking is lost. You get "/reports/results/" 404 in your campaign logs.

Is there a way to force the "/reports/results/" working over HTTP when your phishing site is over HTTP and PF over HTTPS?

I am suggesting that cause I am having issues to make PF app back to HTTP. It looks like do not care about Passenger anymore lol.

Thanks in advance

**Comment by zeknox** [comment]
I thought you could change the site url within admin > global settings to https://domain.com.

**Comment by david-hacklabs** [comment]
The SITE_URL within the application.rb is updated with the phishing site. Np with that.
When I visit http://<phishingSite>/reports/results I have the 404 but if I visit https://<phishingSite>/reports/results, I have the "start" response.

I guess that the quick solution will be to switch PF back to HTTP. However, it would be great to force the tracking portion to HTTP.

Any other ideas

Btw I don't see SITE URL in "Admin/Global Settings"

**Comment by zeknox** [comment]
Your running an older version. Site URL was moved into Global Settings.

Brandon

**Comment by david-hacklabs** [comment]
All is sorted out
You are a gun!
