### ISSUE TITLE
Application Site URL, Phishing URL, FQDN

### ISSUE THREAD

**Issue by William93** [pentestgeek/phishing-frenzy#305]
Hi. I know this issue has been discussed since long ago. But I am still very confused on the configuration. Can anyone show a working example with some explanation on the external ip and fqdn? Especially how to get the tracking result. Thanks!

**Comment by zeknox** [comment]
The Application Site URL is a fully qualitifed domain name of the PF web interface itself.  This is the FQDN which is used as a callback location for the tracking analytics to send data to the public API collector for stat collection.

Phishing URL is the FQDN of your phishing site itself.  This is typically a completely separate parent domain of the PF domain where the web interface is configured.  The Phishing URL is the full URL that will be used within the email template. So when a user clicks on the link they will be hitting your Phishing URL variable essentially.

FQDN within the campaign settings is what actually gets configured within the Apache VirtualHost so it knows what FQDN to be listening on for your phishing site.

**Comment by William93** [comment]
Thanks man! Among the 3 FQDN, which of them required to be accessed by public? Or which of them should be the public domain and which of them can be the local?

**Comment by zeknox** [comment]
all of the domains should be public facing.  You're targets that you phishing need to be able to resolve these domain addresses via public DNS servers.

Here are some sample values which may help you.

pf web interface:  phish.phishingfrenzy.com (Must have DNS A record to resolve this to an IP)
site url: https://phish.phishingfrenzy.com

for phishing sites you want a different domain you own and you can do this (each fqdn needs to have a DNS A record for targets to resolve and hit the phishing site:
<pre>
campaign1: fqdn: sub1.domain.com, phishing url: https://sub1.domain.com/
campaign2: fqdn: sub2.domain.com, phishing url: https://sub2.domain.com/
campaign3: fqdn: sub3.domain.com, phishing url: https://sub3.domain.com/
campaign4: fqdn: sub4.domain.com, phishing url: https://sub4.domain.com/
campaign5: fqdn: sub5.domain.com, phishing url: https://sub5.domain.com/
</pre>

**Comment by William93** [comment]
I see. Clearly understood!
Thank you for the explanation :100:  :)

**Comment by William93** [comment]
I managed to make email opened tracking work but not the clicked email tracking. For the FQDN within campaign, how does the configuration of virtual host Apache looks like? Do I need to buy another domain for this? Sorry I don't really catch this part.

**Comment by zeknox** [comment]
Are you able to hit the phishing site properly right now?  So if you click the link within the email does your phishing site load properly?

If you want to see how any of the campaigns are configured within apache you can run either `apachectl -S` or take a look within `/etc/apache2/sites-enabled/:id.conf` where :id is the campaign_id.

Your phishing sites will also need a domain which has public DNS resolving for all targets, this is required for them to actually hit the phishing site properly.

**Comment by William93** [comment]
I am able to hit the phishing site right now. I am not sure if it's correct, I used public domain e.g http://demo.testfire.net/ with FQDN: testfire.net. After clicking the phishing link, the url has uid attached on it. But my report doesn't show any update on clicked.

**Comment by zeknox** [comment]
If you have changed your site url since your campaign was activated you may need to deactivate it and reactivate it.

This is because when a campaign is activated and deploys the phishing site, it uses the site url within the php landing page to track the analytics.

Is your phishing page a .php extension?

**Comment by William93** [comment]
It's a html page. 
So that means after I activated and launched the campaign, I have to deactivate and activate back?

**Comment by zeknox** [comment]
Thats your problem.  The documentation states you must host your phishing pages using PHP.  There is server-side code that gets invoked each time a user clicks on a phishing page to track the clicks. That's your issue.

**Comment by William93** [comment]
Oh ya! It's my fault.
Thank you very much for the guidance! :)

**Comment by William93** [comment]
Hi zeknox. I have managed to get another domain to host my phishing site. 
When I tried on the intel template, after entering the password, the second page, which is the index2.php doesnt have the uid attached.
It showed "index2.php?uid=" where the 8 digit uid absent

**Comment by zeknox** [comment]
You need to ensure that the UID was passed in on the initial landing page of index.php.  The action on the PHP form is going to grab this parameter when it redirects to index2.php.
