### ISSUE TITLE
Page Not Found - When made the campaign active

### ISSUE THREAD

**Issue by tj94** [pentestgeek/phishing-frenzy#307]
Everything seemed to have been working alright until i clicked active and launched the campaign. 
Now when i go to that server - it just shows page not found.

**Comment by zeknox** [comment]
Please show the results of `apachectl -S` to see how your VirtualHosts are configured.

**Comment by tj94** [comment]
![1](https://cloud.githubusercontent.com/assets/15603835/15783113/d263f106-297a-11e6-9bde-bf032df47503.PNG)

Thanks for the really quick reply. Much appreciated.

**Comment by zeknox** [comment]
pfgoeasy.local should still be serving up your PF interface based on the looks of this.

You've put in an IP address for the FQDN of your phishing site.  This is typically a real domain name that is unique from any other defined FQDN.  However, the IP address should be serving up whatever website you have defined in 1.conf which was generated by making the campaign 1 active.

**Comment by tj94** [comment]
Hey, i am sorry but the word has lost on me.
what do you think should i do now ?
When i go to pfgoeasy.local/ - it doesn't work

**Comment by zeknox** [comment]
You can simply remove the file 1.conf since that was the file that was added when you activated the campaign. Then restart apache and everything should go back to normal before you activated that campaign.

**Comment by zeknox** [comment]
Also you need to make sure you have DNS or a HOSTs entry in place to route pfgoeasy.local to the proper IP address of PF.

**Comment by tj94** [comment]
Thanks will do that, and how can i make sure this doesn't happen again? when i make the campaign active

**Comment by zeknox** [comment]
I believe the root issue is that you used an IP address as your FQDN within the campaign settings when it should be an actual domain name that you want the phishing site hosted under.

**Comment by tj94** [comment]
thanks for the response, let me see if that fixes everything and get back to you!

**Comment by tj94** [comment]
Hey, that did it. 
However, i would like to know how can i fix the DNS or HOSTs entry to route server name to proper IP address ?
 also the FQDN in campaign would be a phishing website like intel.domain.com hostel by PF. Right? 
But how can i start to host that website in my linux box ? 
Also when i test a campaign email - it just says queued for test but doesn't really send an email, even with the active campaign no emails were sent out.

**Comment by tj94** [comment]
Thanks for all your help. It's really great.

**Comment by zeknox** [comment]
You need to edit your local /etc/hosts file or the other location its located if you are on windows.  This is essentially poor mans DNS to resolve any english address to an ip address.  For example pf.local > 192.168.1.120 or whatever.

Emails likely were not sent because your not running the sidekiq process which is required to send email by default.  This can be modified within the Global Settings to foreground sending.

**Comment by tj94** [comment]
Hey, 
![capture](https://cloud.githubusercontent.com/assets/15603835/15785166/d1997f08-2983-11e6-9ce9-1206fc79e732.PNG)
 this is how it is 

what should be changed here ?

**Comment by zeknox** [comment]
Nothing if you want to send emails using sidekiq just rung the sidekiq process as stated in the install guide.

If you want to send emails without sidekiq it will hand in the foreground but does not require sidekiq you would uncheck "Background Email"

**Comment by zeknox** [comment]
I can tell that your application site URL will need modification as well if you want to track user clicks, ensure your reading the docs to understand how everything is working.

**Comment by tj94** [comment]
Hey, 
As you can see in the above image that sideKiq is running, but the emails are not going through, even after unchecking the Background email in global setting, emails are not received on the other end. 

Also when you wrote intel.domain.com/index.php in your phishing URL - is there something to be loaded in the linux box to run that site. If yes, how could we do that. 
I have been trying to find all the documents related to this, couldn't find any - if you could guide or send a link to related information - would be great!
