### ISSUE TITLE
Gather Additional User Info?

### ISSUE THREAD

**Issue by alexmhoffman** [pentestgeek/phishing-frenzy#311]
In addition to username and password, is Phishing Frenzy capable of storing additional submitted data? Trying to run a campaign where the client wants to gather phone numbers, SSN, home address, etc, but not username or password. Is this possible out of the box, and if not, how difficult would that be to implement?

**Comment by zeknox** [comment]
It's not builtin by default and would require modification of the PHP tags which are inserted to your phishing site:
https://github.com/pentestgeek/phishing-frenzy/blob/master/app/views/reports/tags.txt.erb#L40

This is the line which aggregates the parameters from the phishing site and sends them to the API for tracking and stats.  You would need to modify for additional fields to get inserted into the 'extra' attribute.

**Comment by alexmhoffman** [comment]
Appreciate the help, I'll give it a try.
