### ISSUE TITLE
Is there a way to export a specific user information (browser, ip, time visited, etc) instead of general campaign report?

### ISSUE THREAD

**Issue by William93** [pentestgeek/phishing-frenzy#313]
I am trying to export specific user information to either csv or pdf format. If there is a way to do through scripting, can someone please guide me through? I am not familiar with ruby on rails. Thanks!

**Comment by zeknox** [comment]
There should be an option to export each user within excel. Click more options when viewing the campaign stats page

**Comment by William93** [comment]
There is an option to download excel spreadsheet from campaign. Isn't that download the campaign stat instead of a specific user?

**Comment by William93** [comment]
Or could you tell me which option will export specific user's information? thanks!

**Comment by zeknox** [comment]
currently no option to export only 1 specific user.
