### ISSUE TITLE
Campaign test email queued for test

### ISSUE THREAD

**Issue by JohnnyRad** [pentestgeek/phishing-frenzy#314]
I followed the [demo ](https://www.youtube.com/watch?v=UjUZtsvoF1Q),and created a campaign, when i click the test button, just saying "Campaign test email queued for test",  but i couldn't recieve the test mail,why?

**Comment by zeknox** [comment]
Sounds like your Sidekiq process is not running in production mode.

**Comment by JohnnyRad** [comment]
thank you @zeknox  , Here is my sidekiq configuration, is that right?

root@up:/var/www/phishing-frenzy# ll ./tmp/pids
total 4
-rw-r--r-- 1 www-data www-data 6 Jul  5 05:48 sidekiq.pid

root@up:/var/www/phishing-frenzy# cat config/sidekiq.yml 
# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency:  25
:queues:
  - [often, 7]
  - [default, 5]
  - [seldom, 3]

root@up:/var/www/phishing-frenzybundle exec sidekiq -C config/sidekiq.yml

         s
          ss
     sss  sss         ss
     s  sss s   ssss sss   ____  _     _      _    _
     s     sssss ssss     / ___|(_) __| | ___| | _(_) __ _
    s         sss         \___ \| |/ _` |/ _ \ |/ / |/ _` |
    s sssss  s             ___) | | (_| |  __/   <| | (_| |
    ss    s  s            |____/|_|\__,_|\___|_|\_\_|\__, |
    s     s s                                           |_|
          s s
         sss
         sss 


![phishing frenzy campaign details](https://cloud.githubusercontent.com/assets/8325079/16605229/c9e58324-435f-11e6-9dcf-164848ccc158.png)
![phishing frenzy gmail smtp details](https://cloud.githubusercontent.com/assets/8325079/16605237/d90519a0-435f-11e6-86f5-884927b46a06.png)

**Comment by zeknox** [comment]
Looks like you're not starting the sidekiq process in production mode.  Looks to be the issue here.
