### ISSUE TITLE
Test email returns error "Generic Template Issue: wrong number of arguments (0 for 1)"

### ISSUE THREAD

**Issue by RedLee3** [pentestgeek/phishing-frenzy#319]
When launching a test email for a campaign, the error `Generic Template Issue: wrong number of arguments (0 for 1)` is presented at the top of the page. Recent Blasts show no failures and that the sent email was a success. Not currently configured to send emails in the background as Sidekiq was failing to start, but I've sent emails from other campaigns without issue. Template has an email file configured.

What can I troubleshoot from here.

**Comment by zeknox** [comment]
You've likely got a syntax issue somewhere in your template > email.  Fix that email issue and you should be on your way.

**Comment by RedLee3** [comment]
My lame HTML has been cleaned up and the test email is sending.
