### ISSUE TITLE
UID replaces with <?php echo $uid ?>

### ISSUE THREAD

**Issue by bauldini** [pentestgeek/phishing-frenzy#321]
Hey guys, 

I have phishing frenzy set up and I have the campaign active. I am able to send emails but when I click the link I get http://helpdesk.XXXXX.com/index2.php?uid=<?php echo $uid ?>

Am I doing something wrong?

**Comment by zeknox** [comment]
Sounds like something in your Email template is adding the <?php echo $uid ?>.  PF does not add that php code within the HTML email itself.

**Comment by bauldini** [comment]
Thanks Ill check that out and update.

**Comment by bauldini** [comment]
Could it be that I have PHP 7 installed?

**Comment by zeknox** [comment]
Nah, I don't think that should cause the issue.  Do this for me, before you click on the link, hover of the link in the email. Is it the same exact url you posted above or a lil different?

**Comment by bauldini** [comment]
Its different it actually shows the UID. When I click on the link it shows the UID as well.  The change happens when I click on the grade my password from the intel password checker. 
http://helpdesk.XXXXX.com/index.php?uid=ITBWMXEV then after I click on grade password 
http://helpdesk.vertekvt.com/index2.php?uid=%3C?php%20echo%20$uid%20?%3E

**Comment by zeknox** [comment]
Gotya, so you need to actually look at the action parameter inside your HTML form for this phishing site.  Sounds like its not actually rendering the php code properly after you submit the form.

**Comment by bauldini** [comment]
That would be part of the template correct?

**Comment by zeknox** [comment]
Correct, it will be one of the website files within the template.  This is the HTML which is running your phishing site.

**Comment by bauldini** [comment]
<script type="text/javascript">$("#u1268-17").live("click", function(){
  var componentNameId='consumer-security1';
  wa_omniLink='wa_events=event70&wa_action=click&wa_eAction=click&wa_custom60='+componentNameId+'&wa_eCustom60='+componentNameId+'&wa_custom61=grademypassword&wa_eCustom61=grademypassword&wa_custom62='+componentNameId+':grademypassword&$
  trackGaEvent('Components', 'click: ' + componentNameId, 'grademypassword');
  if (wa_trackOmniture) {
        waTrackAsLink('intc:links', 'o', wa_omniLink);
Thats the function im not PHP expert does this look correct to you?

**Comment by zeknox** [comment]
Not that does not look like the proper PHP code.  Do a search for "action=" within your HTML phishing site and you should see the form which is redirecting to the URL you're having issues with.

**Comment by bauldini** [comment]
That is think is what you are talking about. I will look into this if everything seems correct here, and post back soon. Thanks for all of your help.

![8-3-2016 1-27-05 pm](https://cloud.githubusercontent.com/assets/20802417/17375367/a2852282-597e-11e6-981b-4754139cc473.png)

**Comment by zeknox** [comment]
Yes that is the correct part of HTML.  It looks like the PHP is not rendering properly because you should not see those server-side tags.  You should be seeing the result of those tags being rendered.

This makes me think that PHP is either disabled or not working, or you may have named the file with a non .php extension within the template itself.

**Comment by bauldini** [comment]
I resolved this by finding this link: http://askubuntu.com/questions/756181/installing-php-5-6-on-xenial-16-04 Once I downgraded to php 5.6 instead of 7 it is now working.

**Comment by zeknox** [comment]
Thanks for the update, so ultimately it seems PHP was not running properly on the OS.  HAVE FUN!
