### ISSUE TITLE
Link PF to website?

### ISSUE THREAD

**Issue by moeops** [pentestgeek/phishing-frenzy#325]
I have website code (php as well), I managed to get PF installed. How do I go about linking phishingfrenzy to a website people can click on? 

Can I host one from my computer? Does PF automatically host the template I created? I do not understand.

Also any suggestions as to where I purchase a domain name/website hosting service if I have to?

**Comment by moeops** [comment]
Also when I tick Active and click launch campaign, it says:

1 error prohibited this record from being saved
There were problems with the following fields:
Apache File Permission Issue: chmod -R 755 and chown www-data:www-data /etc/apache2/sites-enabled

I created a sites-enabled field as I am on MAC OS X and it didn't come by itself. Also full permissions are given to _www

**Comment by moeops** [comment]
Also what is Application Site URL?

What do I place there?

**Comment by moeops** [comment]
Managed to link it, I even see the UID at the end of the link.

The only problem now is that it does not track what's happening. I tried the manual track thing, and it worked, so I'm guessing I did something wrong.

**Comment by zeknox** [comment]
If the manual tracking is working then you likely have an issue with your Application SITE Url, this is the FQDN that is leveraged as callback API to send tracking analytics too.  Update your application site url to a proper value, disable any phishing sites and re-enable and all should work well.
