### ISSUE TITLE
Bundle failure

### ISSUE THREAD

**Issue by itgeekygirl007** [pentestgeek/phishing-frenzy#327]
can someone help me out with the following:
An error occurred while installing ruby_dep (1.4.0), and Bundler cannot
continue.
Make sure that `gem install ruby_dep -v '1.4.0'` succeeds before bundling.

**Comment by zeknox** [comment]
What version of ruby are you running?  When you run `gem install ruby_dep -v '1.4.0'` does the output yield anything to tell you about the issue more specifically?

**Comment by itgeekygirl007** [comment]
here is what I get:
ERROR:  Error installing ruby_dep:
	ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.

**Comment by itgeekygirl007** [comment]
my current version of ruby is:ruby -v
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

**Comment by zeknox** [comment]
Looks like thats the dependency problem. The ruby_dep gem requires that you have version 2.2 or greater installed.

**Comment by zeknox** [comment]
We are actively working to upgrade the application to work on the latest version of ruby and rails to address this issue.  Code needs a bit of refactor to fix the bugs after the upgrade.

**Comment by Kristinexo** [comment]
Will it be fix soon?

**Comment by zeknox** [comment]
No ETA on the fix, it will get updated when it gets updated.  In the meantime upgrade your ruby to latest stable version and leave rails like it is in the Gemfile and all should work.

**Comment by LarryGrim** [comment]
While likely not the correction that an updated package would support, I got by the error message with 
rvm all do gem install --no-rdoc --no-ri rails -v 4.2.2
