### ISSUE TITLE
Cannot start campaign

### ISSUE THREAD

**Issue by LarryGrim** [pentestgeek/phishing-frenzy#334]
I can test a campaign and that works.  However, after filling in targets, when attempting to save a campaign, it comes back with:
1 error prohibited this record from being saved

**There were problems with the following fields:
◾Apache File Permission Issue: chmod -R 755 and chown www-data:www-data /etc/apache2/sites-enabled**

Rathen than being created with www-data:www-data ownership, it was created with root:root.
Even manually changing the permissions/ownership does not fix the problem.

Any suggestions?

**Comment by zeknox** [comment]
Make sure you are using -R flag when you chown everything to ensure sub directories are included.  This looks like you were also trying to activate the campaign as well which requires you have write access to the sites-enabled directory to configure the Apache VirtualHost.

**Comment by LarryGrim** [comment]
I did that. However, went back and installed everything as www-data (was using an Amazon Web Services Ubuntu 16.04 and default account of ubuntu).  That provided the permissions throughout, and the file locations correctly.  For example, .rvm went under the home directory for www-data, which made that user access the appropriate files without a problem (even have the profile correct).   
This joined the challenge of doing it on the most recent version of Ubuntu in a small AWS t2.micro instance.
