### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by dan7ez** [pentestgeek/phishing-frenzy#336]
in the browser i get this error - saying "Web application could not be started - phusion passenger has listed more info about this error below

cannot load such file -- bundler/setup (LoadError)
  /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in`require'
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:430:in `activate_gem'
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:297:in`block in run_load_path_setup_code'
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:435:in `running_bundler'
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:296:in`run_load_path_setup_code'
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:100:in `preload_app'
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:156:in`module:App'
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:29:in`<main>'

Error ID
    91d88707
Application root
    /var/www/phishing-frenzy

**Comment by zeknox** [comment]
<pre>cannot load such file -- bundler/setup (LoadError)</pre>

Looks like the bundler gem is not installed for the system or your version of ruby.  Try something like:
<pre>$ gem install bundler</pre>

**Comment by zeknox** [comment]
closing due to lack of response
