### ISSUE TITLE
Install proc on lastest Ubuntu (or Debian?)

### ISSUE THREAD

**Issue by fraf0** [pentestgeek/phishing-frenzy#339]
Hi,

I try to build a fresh phishing Frenzy on the lastest Ubuntu docker image.
The proc : https://www.phishingfrenzy.com/resources/install_ubuntu_linux
don't work.

Does anyone have a working proc for lasted ubuntu or debian ?

For example about error :

No candidate for php5 -> php7

It's seem that rails is installed in 5 version and so not compatible.

```
root@3d68f5238861:/# rvm all do gem install --no-rdoc --no-ri rails
Fetching: concurrent-ruby-1.0.2.gem (100%)
Successfully installed concurrent-ruby-1.0.2
Fetching: minitest-5.9.1.gem (100%)
Successfully installed minitest-5.9.1
Fetching: thread_safe-0.3.5.gem (100%)
Successfully installed thread_safe-0.3.5
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: activesupport-5.0.0.1.gem (100%)
ERROR:  Error installing rails:
    activesupport requires Ruby version >= 2.2.2.
root@3d68f5238861:/# 
```

fraf.

**Comment by LarryGrim** [comment]
[Use PHP 5.6 with PHP 7.0]
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install php7.0 php5.6 php5.6-mysql php-gettext php5.6-mbstring php-xdebug libapache2-mod-php5.6 libapache2-mod-php7.0
sudo a2dismod proxy_fcgi proxy; sudo service apache2 restart
sudo a2dismod php7.0 ; sudo a2enmod php5.6 ; sudo service apache2 restart
sudo ln -sfn /usr/bin/php5.6 /etc/alternatives/php

[See: http://askubuntu.com/questions/761713/how-can-i-downgrade-from-php-7-to-php-5-6-on-ubuntu-16-04/762161#762161]

**Comment by zeknox** [comment]
I recommend that you're installing this on Ubuntu 14.04 as 16.04 is not documented or tested

**Comment by fraf0** [comment]
Thanks,

I have this error :

```
root@b855d7cf96aa:/# rvm all do gem install --no-rdoc --no-ri rails
Fetching: concurrent-ruby-1.0.2.gem (100%)
Successfully installed concurrent-ruby-1.0.2
Fetching: minitest-5.9.1.gem (100%)
Successfully installed minitest-5.9.1
Fetching: thread_safe-0.3.5.gem (100%)
Successfully installed thread_safe-0.3.5
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: activesupport-5.0.0.1.gem (100%)
ERROR:  Error installing rails:
	activesupport requires Ruby version >= 2.2.2.
root@b855d7cf96aa:/# rvm all do gem install --no-rdoc --no-ri passenger
Fetching: rack-2.0.1.gem (100%)
ERROR:  Error installing passenger:
	rack requires Ruby version >= 2.2.2.
root@b855d7cf96aa:/# 
```

I do no search on this error, I left my office for now :) It's week-end :) And after 2 weeks hollydays (it's not about you but it makes me happy :))

Ps @zeknox  : May be add to your article that it's only for Ubuntu Trusty.

**Comment by zeknox** [comment]
This error is self explanatory and requires no googling.
<pre>rack requires Ruby version >= 2.2.2</pre>

The master branch is in a rough spot right now, I am working towards core issues required to get the latest version of ruby and rails playing nicely together.

**Comment by fraf0** [comment]
Hi,
I'm agree on the error. The problem is the solution :)
Must I understand that the actual code is not usable in this configuration ?
If it's right, could you give me the actual fonctionnal conditions ?

**Comment by Sluisocelot** [comment]
Got it up and running on ubuntu 14.04 and ruby 2.2.5 by following the install documentation for ubuntu. Had to run `sudo apt-get install -y tcl ` though to get it running.

**Comment by zeknox** [comment]
Thanks for sharing all the details here so others can benefit.
