### ISSUE TITLE
Your bundle is locked to i18n (0.7.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of i18n (0.7.0) has removed it. You'll need to update your bundle to a different version of i18n (0.7.0) that hasn't been removed in order to install. (Bundler::GemNotFound) 

### ISSUE THREAD

**Issue by chengteck** [pentestgeek/phishing-frenzy#340]
Hi guys.

Did anyone of you encounter this error?

-------- The exception is as follows: -------
![error](https://cloud.githubusercontent.com/assets/8423798/19033623/e676acca-8991-11e6-9140-bd3b9ffa3acf.PNG)

Your bundle is locked to i18n (0.7.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of i18n (0.7.0) has removed it. You'll need to update your bundle to a different version of i18n (0.7.0) that hasn't been removed in order to install. (Bundler::GemNotFound) 

/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.13.2/lib/bundler/definition.rb:179:in `rescue in specs'
  /usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.13.2/lib/bundler/definition.rb:173:in `specs'
  /usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.13.2/lib/bundler/definition.rb:233:in `specs_for'
  /usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.13.2/lib/bundler/definition.rb:222:in `requested_specs'
  /usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.13.2/lib/bundler/runtime.rb:118:in `block in definition_method'
  /usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.13.2/lib/bundler/runtime.rb:19:in `setup'
  /usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.13.2/lib/bundler.rb:99:in `setup'
  /usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.13.2/lib/bundler/setup.rb:20:in `<top (required)>'
  /usr/local/rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /usr/local/rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /usr/local/rvm/gems/ruby-2.2.5/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:430:in `activate_gem'
  /usr/local/rvm/gems/ruby-2.2.5/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:297:in `block in run_load_path_setup_code'
  /usr/local/rvm/gems/ruby-2.2.5/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:435:in `running_bundler'
  /usr/local/rvm/gems/ruby-2.2.5/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:296:in `run_load_path_setup_code'
  /usr/local/rvm/gems/ruby-2.2.5/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:100:in `preload_app'
  /usr/local/rvm/gems/ruby-2.2.5/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/local/rvm/gems/ruby-2.2.5/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/local/rvm/gems/ruby-2.2.5/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:29:in `<main>'

I tried bundle install --deployment but it still not working.

Any ideas?

Thank you.

**Comment by zhangwei900808** [comment]
I have this problem

**Comment by yaitloutou** [comment]
I have run into this same error when trying to run the jekyll template [beautiful-jekyll](http://deanattali.com/beautiful-jekyll) locally, using `jekyll serve` and `bundle exec jekyll s`.
```
bundle install
``` 
seems to solve the issue
