### ISSUE TITLE
Click Tracking

### ISSUE THREAD

**Issue by Theodolus** [pentestgeek/phishing-frenzy#342]
Been working at getting this up and running for a while now and am stuck on the last bit needed before I can start using it for in house testing. Before I go any further, here is the output of apachectl -S.

VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server phish.company.local (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost phish.company.local (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost friendly.pf.com (/etc/apache2/sites-enabled/7.conf:1)
                 alias friendly.pf.com
*:443                  is a NameVirtualHost
         default server friendly.pf.com (/etc/apache2/sites-enabled/7.conf:8)
         port 443 namevhost friendly.pf.com (/etc/apache2/sites-enabled/7.conf:8)
                 alias friendly.pf.com
         port 443 namevhost pf.com (/etc/apache2/pf.conf:19)
                 alias phish.pf.com
                 alias friendly.pf.com
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex ssl-cache: using_defaults
Mutex default: dir="/var/lock/apache2" mechanism=fcntl
Mutex watchdog-callback: using_defaults
Mutex ssl-stapling-refresh: using_defaults
Mutex ssl-stapling: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33 not_used
Group: name="www-data" id=33 not_used

Application Site URL is https://friendly.pf.com

I can go to this URL and configure campaigns and whatnot and everything works fantastically until I activate the site. The campaign site then goes live and I am booted from the screen. I can then access PF via phish.pf.com and launch the campaign. E-mails are sent correctly and when I receive the e-mail and click on the link it takes me to https://friendly.pf.com/?uid=XXXXXXXX as expected. But it never registers a click. If I go to https://frienly.pf.com/reports/results/?uid=XXXXXXXX I get a 404. But if I go to https://phish.pf.com/reports/results/?uid=XXXXXXXX I get a page that says [start, uid check, length 1, over 1, ] and the reports on the phish.pf.com/reports/list page immediately registers the click. So obviously the click tracking is working and the e-mail link is incorrect. 

In the campaign I specified the Phishing URL as https://friendly.pf.com/index.php and the FQDN as friendly.pf.com. But if I switch both of those to phish.pf.com (and either change or leave the Application Site URL) and activate the campaign I immediately lose access to the phish.pf.com site and have to go to friendly.pf.com to access the dashboard and the results above are inverted. I feel like I'm just entering in the various URLs incorrectly and am probably bashing my head against this without seeing the obvious solution.

A final note to this is that I am using Ubuntu Server 16. I did see a reply about a week ago that there are issues with it and the recommended route is to go with 14 but since I'm so close to getting this working I really don't want to go all the way back to square one and start over. In fact at this point, other than the click tracking the only thing I'm struggling with is getting sidekiq to actually run under systemd as a service. The service runs, but PF never recognizes that it is running. And with it running I can execute the rvmsudo bundle command and get it running manually and it works fine. But I'm still bashing my head against that one and think I may be on track to getting it working. In any case I'll put up any information I come up with in case it will help anyone else trying to get this working.

Thanks for any help!

**Comment by zeknox** [comment]
<pre>port 443 namevhost pf.com (/etc/apache2/pf.conf:19)</pre>

This tells me that your PF UI is configured on pf.com which also means your Application SITE URL should be pf.com is this is accurate.

If you feel that you have everything setup but the 404 on the phishing site is the main issue, try manually doing a sudo restart of the apache service.  Maybe you have an issue with your sudoers file and www-data not able to properly restart the apache service load your VHOSTS.

You don't need to get redis-server of Sidekiq running to make PF function 100%.  You can goto global settings and uncheck the "Background Emails".  This will bypass Redis and Sidekiq and send emails in the foreground.  Note that this will hang the browser when sending emails since they are not handled in the background.

**Comment by Theodolus** [comment]
Okay, so I changed the Application Site URL in the Global Settings to pf.com. I'm fairly certain the sudoers file and www-data are working properly as when I de-activate a campaign I go back to being able to get to access the PF dashboard via any and all mapped DNS names. In addition when I look at /etc/apache2/sites-enabled I can see the campaign#.conf file appear and disappear. I assume that the combination of these means that apache is being restarted properly.

I had been trying to various things up to the point of my putting in this question so in my pf.conf file I had pf.com as the server name and phish.pf.com and friendly.pf.com as serveraliases. To make things as simple as possible I've returned back to what should be stock with phish.pf.com as the PF UI address (apachectl -S shows "port 443 namevhost phish.pf.com (/etc/apache2/pf.conf:19)") and have done a sudo systemctl restart apache2. I then set up a new campaign with the friendly.pf.com address and still have the issue where if I go to friendly.pf.com/reports/results... it shows page not available and if I go to phish.pf.com/etc... it comes up properly. I shouldn't be using the same URL for the campaign as I have in the application site url field should I? Thanks again for the help and quick response to my first question.

**Comment by zeknox** [comment]
No, you really should have 2 uniq FQDNs.  You need to have a uniq FQDN for the PF UI (pf.phish.local for example, and then you would put this within the Global Settings Application Site URL because this is how PF knows how to track clicks), then you need a separate FQDN that is different than the PF UI for your phishing sites.

**Comment by Theodolus** [comment]
Just to clarify, when you say a separate FQDN for the phishing sites you mean something like having pf.phish.local for the UI and site.phish.local for the phishing site, right? In other words, it gets hosted on the same server, but you hit the server using a different FQDN. The site FQDN doesn't need to be set up in pf.conf either, right? That's managed by the application when you set up the campaign?

**Comment by zeknox** [comment]
Yes, I believe using the same parent domain and changing just the subdomain is sufficient.  This really comes down to uniq names so Apache knows what website needs to be rendered.  You're running multiple websites on a single box and the uniq names is the only key to render proper requested website.  Hope this helps.

**Comment by Theodolus** [comment]
Sadly still no luck. I made sure that the only domain in the pf.conf file is phish.pf.com. Then I tried two more campaigns. The first one was unfriendly.pf.com and I got the same results as before. Then I tried unfriendly.phish.pf.com and got the same result except this time when I downloaded the picture (Outlook auto blocks the 1x1 pixel image) I did get a result in the report showing that the e-mail was opened. Still no click track though. Going to the unfriendly.phish.pf.com/reports/results page shows the error: The requested URL /reports/results/ was not found on this server.

I feel like there is supposed to be some sort of redirect that pushes the click over to the phish.pf.com domain for recording before pushing them to the requested site, but that never happens. I'm just using the default Intel Password template. Is it possible that the template is the issue? I double checked the mysql account as well, thinking that maybe for some strange reason the pf_dev password was wrong, but that's good as well.

**Comment by zeknox** [comment]
Is the underlying issue that your getting a 404 with your phishing site right now?  There is no redirect that happens for the phishing sites.  Every PHP page is added some tracking tags which are used to send the click tracking to the PF API which is defined within the Global Settings > Application Site Url

**Comment by Theodolus** [comment]
No, I'm able to get to the phishing site no problem. The only time I get that error is when trying to navigate to the wrong page (only the /reports/results page for manually triggering the click.) That works fine on the applicationURL/reports/results page. I think I'm expecting a result that should never happen in that case. If that is so, then it seems like what is happening is that the PF API isn't getting the tracking information on the clicks. Is it supposed to record the click on page load, or after they click an element on the page?

**Comment by zeknox** [comment]
Ok, so what I'm hearing is you only have issues with the tracking analytics are not working properly?

<pre>applicationURL/reports/results</pre>
This is the only URL that should work for /reports/results/, it is not suppose to work for your phishing sites FQDN.

What it sounds like is you have modified your Application Site URL while a campaign is active.  This means that the PHP tags on your phishing site are stale and pointing to an older Application Site URL which will never track your clicks.  Try to uncheck Active within the campaign, save the campaign. Then check Active within the campaign and Save again.

What this does is re-deploys the Phishing site with the updated PHP tags with the proper Application SITE Url so you can track clicks properly.  This is likely your issue if you can get the stats to track properly using the manual click method in the docs.

**Comment by Theodolus** [comment]
Ah, okay, I was expecting the wrong URL to resolve for the manual click. I actually just finished creating a brand new campaign with a different template (and have done this a few times now actually) and am still not getting the tracking analytics though. Looking at the index.php for the currently active campaign (unfriendly.pf.com) I show the following:

$url = "https://phish.pf.com" . '/reports/results/';
and a bit later
$result = file_get_contents($url, false, $context);
the $result variable isn't referenced anywhere though.

Again, thanks for your patience and help in trying to work through this issue. I appreciate the time and effort you put in to helping out!

**Comment by zeknox** [comment]
Is the phishing server able to resolve through DNS phish.pf.com?

the PHP tags are executing server side so we need to make sure pf server knows how to make the HTTP POST request to phish.pf.com.

**Comment by Theodolus** [comment]
Okay, so I was reading through another thread on here from earlier this year and someone mentioned using a completely different domain resolved the issue for them. So I set up a new domain on my DNS server (efax.us) and created an A record on there for download.efax.us. Verified that my computer can resolve the site and deleted the old campaign. Set up a new campaign pointing to http://download.efax.us with an FQDN of download.efax.us and activated it. The site resolves perfectly fine at this point. (Your response just came through and yes, phish.pf.com also resolves correctly. In addition the phish.pf.com site is hosted on 443 with SSL and the phishing site is on standard http.) I blasted the email out, downloaded the picture for opening stats, and clicked the link. I get info that the email was opened, but no click track. Not sure if it matters, but the php doesn't load quite right and at the top of the site I see this:
![efax](https://cloud.githubusercontent.com/assets/20192951/19205104/3b3df546-8c95-11e6-8f7b-e5593a8cc927.PNG)

**Comment by zeknox** [comment]
Yeah your not getting the tracked click because the PHP code above isn't rendering properly.  Thats the PHP code that is used for tracking and sending the HTTP POST request to the PF API.

You mentioned your PF UI is running on HTTPS, make sure you have https:// added to the Site URL in Global Settings.

What version of PHP is on the system?  I'm guessing 7?

**Comment by Theodolus** [comment]
Yes, looks like 7. I'm a bit of a newbie when it comes to linux but running php-v shows php7.0-cli and hhvm.

**Comment by Theodolus** [comment]
um... or not? I just ran sudo apt install php7.0-cli and it ran through installation. It's entirely possible that I just never got php installed on the server. I'll give things another round and let you know.

**Comment by zeknox** [comment]
<pre>$ php -v</pre>

Should tell you what version is running on the os.  I believe others in the past had issues with php 7, and had to downgrade to php 5.   Anyways the master branch is in a rough spot where I'm working on getting everything up to latest rails version.

**Comment by Theodolus** [comment]
okay, yeah, I don't think I had any version of php installed. php -v shows PHP 7.0.8-0ubuntu-0.16.04.3 now. I'll look in to downgrading to php 5.

**Comment by Theodolus** [comment]
Whoo! That did it! Moved to php5.6, and made sure that apache was using all php5.6 instead of 7.0. Re-Launched the campaign site and got a click from it! Set up a new campaign on intel.pf.com and got a click and the password. Looks like it's working now! Can't tell you how grateful I am for you helping me out with this. If there is any info you could use from this install on ubuntu 16 just let me know and I'll get it for you.

**Comment by zeknox** [comment]
Nice, cheers!
