### ISSUE TITLE
Question about SMTP

### ISSUE THREAD

**Issue by TheRapture** [pentestgeek/phishing-frenzy#344]
Hey there!
I was wondering if you had information about using an unauthenticated SMTP server, and how I might do that in the web panel of PF. Do I have to use a specific mailbox, per se? Is there a way to put in the SMTP info and have it create messages from mailboxes specified in the web panel?  Thank you in advance!

**Comment by TheRapture** [comment]
I ended up getting PF to send the emails through the SMTP server, but I am curious; has anyone sent >15,000 emails at one time before?  I am hoping that it isn't a problem, but wanted to see if anyone has done this before, and perhaps what challenges (or not) they had.

**Comment by zeknox** [comment]
Closing as I believe we spoke offline and addressed all these questions.
