### ISSUE TITLE
Redhat

### ISSUE THREAD

**Issue by alexmhoffman** [pentestgeek/phishing-frenzy#349]
Has anyone had any luck porting PF to Redhat? Boss wants it on Redhat (Someone assumes Redhat is more secure or something) and I just need to know if it's even worth the undertaking to get it operational.

**Comment by zeknox** [comment]
It's not supported by us, but I believe a number of folks have got it working.  I've spoken with a few teams over the past couple years that stated they were able to get it working.  Just required some modifications to the Global Settings once installed.

I'd investigate a good tutorial on getting ruby on rails working with with Red Hat Linux. Cheers.

**Comment by alexmhoffman** [comment]
Awesome, appreciate the quick answer. I'll give it a try.

**Comment by zeknox** [comment]
Yeah if I recall one of the biggest things that needed to be changed in Global Settings was the Apache restart command so that new VHOSTs could be added to the Apache config and restart the service properly to reload them into use.

**Comment by zeknox** [comment]
Closing ticket, please feel free to update this ticket with your feedback or experience.
