### ISSUE TITLE
sidekiq not started error in production log

### ISSUE THREAD

**Issue by wlbreen** [pentestgeek/phishing-frenzy#350]
Default AMI on AWS instance m.2
I changed 'nothing' from the instance.  edit the test skeletor, launch.  GREEN for launching but RED for scheduled task, but sidekiq is not running.

error in production log:
Sidekiq is not running, or pid file, '/var/www/phishing-frenzy/tmp/pids/sidekiq.pid' is invalid:
      Errno::ENOENT - No such file or directory @ rb_sysopen - /var/www/phishing-frenzy/tmp/pids/sidekiq.pid

is there something I am missing?  

Also.. if anyone has a phishlulz AMI that works I would be very happy to test.

Bill

**Comment by Indeserpen** [comment]
nano  /var/www/phishing-frenzy/tmp/pids/sidekiq.pid
touch  /var/www/phishing-frenzy/tmp/pids/sidekiq.pid
should help you out!!! Phishulz it not comparable with PF!!:)

**Comment by zeknox** [comment]
The command `RAILS_ENV=production bundle exec sidekiq -c config/sidekiq.yml` should create the sidekiq.pid file.  Let us know if it does not.
