### ISSUE TITLE
Development Mode Not Providing Stats

### ISSUE THREAD

**Issue by LarryGrim** [pentestgeek/phishing-frenzy#351]
Still in DEV Mode.   Admin panel working.  Phishing going out (both Google and GoDaddy).  Phishing link resolving and bringing up the phishing page.   However, aside from statistics on email sent, no tracking of open, clicked or password entered.
The setup (apachectl -S, contents of 5.conf phishing sites-enabled, and pf.conf
![pf-11-30-2016](https://cloud.githubusercontent.com/assets/14098032/20774159/1ac5f314-b723-11e6-822d-fbfb779318cd.png)
Global settings
![pf-11-30b-2016](https://cloud.githubusercontent.com/assets/14098032/20774165/26cc8678-b723-11e6-82d5-9cb070392ff4.png)
Settings for the campaign 5 email
![pf-11-30c-2016](https://cloud.githubusercontent.com/assets/14098032/20774172/306cf44c-b723-11e6-8e8a-95551e7da082.png)

**Comment by zeknox** [comment]
The Application SITE Url needs to be different than that used within the campaign.  I really need to build a validation to prevent this from happening...

**Comment by LarryGrim** [comment]
1. Changed the Application Site in the Global Settings to different FQDN.  
2. Made the campaign inactive.  
3. Verified that the phishing campaign conf file was not in the /sites-enabled folder.
4, Cleared out all the campaign statistics
5.  Made the campaign active
6. Checked the target LastName, FirstName, email_address
7. Launched the campaign
8.  Target got the email
9. Target clicked on the email
10. The phishing page (LinkedIn) showed up in the target's system.
11.  Aside from email opened, there were no stats registered in the Report screen for the target.
Anything particular that I should send across?

**Comment by zeknox** [comment]
Start here to manually invoke a click event to see if everything is working properly:  https://www.phishingfrenzy.com/resources/troubleshooting

If Emailed Clicked stat is not working, then Passwords Harvested for surely wont work.

**Comment by LarryGrim** [comment]
Understand.
This is the response
![image](https://cloud.githubusercontent.com/assets/14098032/20808879/4127f610-b7d2-11e6-8701-e34c1702be4a.png)

**Comment by zeknox** [comment]
Then that's your issue.  This FQDN must not be that of the PF interface. Until this responds with an HTTP 200 OK you're never going to track analytics.

**Comment by LarryGrim** [comment]
Confused in that there are two different FQDN's associated with this setup.
The PF interface is on www.provider-resource.com
The target interface is on www.linkedon.us
The apachectl -S shows
![image](https://cloud.githubusercontent.com/assets/14098032/20809056/d100d22a-b7d2-11e6-805b-c5d9cfcb66bb.png)

**Comment by zeknox** [comment]
If you're hitting the FQDN of `www.linkedon.us` and the PF interface shows up thats good.  If you then add in the path of `/reports/results/` you should receive something other than the 404 otherwise I'm not really sure whats going on.

**Comment by LarryGrim** [comment]
The link, http://www.linkedon.us/?uid=PZGMRDBQ comes up the the false 2004 LinkedIn page provided with the template.  However, as you see, the http://www.linkedon.us/reports/results/?uid=PZGMRDBQ comes up with the 404 page
Not Found
The requested URL /reports/results/ was not found on this server.
Something else to check?  My previous problem was no php apache module loaded.

**Comment by zeknox** [comment]
I missed it in your previous screenshot but look how `pf.conf` is configured on the FQDN of `provider-resource.com` however you're trying to test the PF API using a different domain?

This is why your getting the 404.  The API is not accessible on your phishing sites but only the VHOST where `pf.conf` is defined.  Try to manually invoke a click even using the proper FQDN.  The same FQDN that is defined within `pf.conf`.

**Comment by LarryGrim** [comment]
![image](https://cloud.githubusercontent.com/assets/14098032/20809842/51155ee8-b7d5-11e6-9dc8-48f7c29d6fb6.png)

The contents of pf.conf
![image](https://cloud.githubusercontent.com/assets/14098032/20809893/74c28802-b7d5-11e6-88c4-c65116b81f79.png)

**Comment by zeknox** [comment]
You're not hitting the proper path.  Slow down and focus.

**Comment by LarryGrim** [comment]
Yep.  Slow down is good.  URL should have been http://provider-resource.com/reports/results/?uid=PZGMRDBQ

![image](https://cloud.githubusercontent.com/assets/14098032/20810407/a717c590-b7d7-11e6-96c1-0e28656a5675.png)

**Comment by zeknox** [comment]
Ok, now you need to configure your Application Site URL to `provider-resource.com` make all active campaigns inactive, and test to see if you're able to track clicks and such.

The PF Tracking API is functioning properly. Now all you need is to ensure the phishing sites are properly forwarding all track analytics to this API.  I'm going to be AFK for the evening, so this is my final support response for a bit.

**Comment by LarryGrim** [comment]
pf.conf, I thought, was the setup for the PhishingFrenzy admin console.

Setup number one.
All campaigns inactive and stats cleared from report page.

PF Administration console 
Application Site URL = http://linkedon.us
Campaigns -> Email Settings -> Phishing URL = http://www.linkedon.us
Campaigns -> Email Settings -> FQDN	= www.linkedon.us

http://www.linkedon.us/reports/results/?uid=GLJBCJHW fails with 404 page not found
http://www.provider-resource.com/reports/results/?uid=GLJBCJHW does generate open/clicked.

============
same scenerio but in the PF Administration console
Application Site URL = http://provider-resource.com
Campaigns -> no change
inactive/active switch 

http://www.linkedon.us/reports/results/?uid=YOMETQMU fails with 404 page not found
http://www.provider-resource.com/reports/results/?uid=YOMETQMU does generate open/clicked

So, it seems that the pf.conf file is the  only place where the provider-resource.com stays in the setup and is part of the base URL that triggers a statistic.  This seems to be regardless of the Global Settings Application Site URL setting.

**Comment by LarryGrim** [comment]
Ok.  This seems to be difficult to use two different domain names for Phishing Frenzy.
There are four places to put a domain name.
1. In the pf.conf file, under /etc/apache2
2. In the Global Settings under the Application Site URL (http://....)
3. In the Campaign Settings, under Email Settings, as the Phishing URL (http://...)
4. In the Campaign Settings, under Email Settings, as the FQDN 
so, 
Given a domain of PF-Admin.com that will be used by the admin to setup the campaign
Given a domain of PF-Victim.com that will be presented to the phishing target.
Where should these two FQDN and/or associated URLs http:// be placed?

I seem to be continued to be challenged on where they are instantiated.

**Comment by LarryGrim** [comment]
Still stuck.  I think that there are at least four places to put domain names, and I have tried all the ways to do this and stats still do not post to the report page.  Some combinations do not even work to have the user go to the right target page.
Thanks, in advance.

**Comment by zeknox** [comment]
This is the best visual I can put together to display how Tracking within PF works and what FQDN should be configured where.  Hope this helps.

![phishing-frenzy-arch](https://cloud.githubusercontent.com/assets/2473269/21188517/46a489b4-c1e1-11e6-825a-7bf3a1e117ae.png)

**Comment by zeknox** [comment]
Going to close this ticket. I dont believe this is a bug, and this is the most support I can provide at this time.  Hope this helps.
