### ISSUE TITLE
Campaign not sending Emails

### ISSUE THREAD

**Issue by tj94** [pentestgeek/phishing-frenzy#356]
One of the campaigns is sending emails while the otherone isn't.
Even when checking the recent blast option, it says 0 for both target and SMTP failure, even though they is a test email present and a couple of targets. 
This is with the Background email option checked in global settings.
When background email options is unchecked it gives the following error: Generic Template Issue: undefined method `url' for nil:NilClass and none of the emails are sent from any of the four campaign; the templates used for these campaigns are the default ones.
![image](https://cloud.githubusercontent.com/assets/15603835/24062364/aca046d8-0b31-11e7-8a67-0cdf4ee2588f.png)

**Comment by zeknox** [comment]
Looks like your email has a syntax issue with the phishing url.  Can you show a snippet of what the phishing url looks like within the email template?

**Comment by tj94** [comment]
![image](https://cloud.githubusercontent.com/assets/15603835/24062556/6d93171c-0b32-11e7-962f-fd9503d98e08.png)

**Comment by zeknox** [comment]
Your image_tag attachments['Office365.png'].url is likely your issue.  Make sure this file really exists within the template.  Url would come back nil if it does not exist and throw the error.  Also it doesn't look like their is a space after .url and the closing %>

**Comment by tj94** [comment]
Thanks for the prompt reply!  Here is another image from the linkedin template 
![image](https://cloud.githubusercontent.com/assets/15603835/24062610/a1b5f69a-0b32-11e7-93bd-39d128dcaea1.png)

Both of these gives the same error when background email in unchecked. However, the email goes through in case of the linkedin but for office365 it does not.

I inserted the space like you said, the image is uploaded in the template and goes by the same name. 
And like i said, if the background email option is checked, it doesn't give this error.

**Comment by zeknox** [comment]
Yeah this really show trigger an error when sending emails in the background, I agree that isn't good user experience.

Try removing your image_tags within the template and I think it'll work.  My hunch tells me that the file has been removed or renamed within the template or something along those lines.

**Comment by tj94** [comment]
Hey, 
No, that didn't work. I commented both of those tags, When sending test email, it still shows 0.

**Comment by zeknox** [comment]
I think thats the problem tho.  Your comments are in HTML which actually are ignored when it comes to rendering ERB blocks within the <% %> tags.  Actually remove them from the email, save, and then test.

**Comment by tj94** [comment]
Hey, 
That did it!!

there is like an empty img tag at the bottom of the emails, should it be like this or something could be done about it ? i knwo it is to track emails click or something.
![image](https://cloud.githubusercontent.com/assets/15603835/24063644/00fa8900-0b37-11e7-86d3-4553b5d6da93.png)

**Comment by zeknox** [comment]
Yeah the missing image in the bottom left is the 1x1 pixel for tracking who opens.  Personally I remove it from my email templates as I don't care about this metric and I'd rather have it not hang me up on a SPAM filter and such.

**Comment by tj94** [comment]
Thanks Sounds good!, Let me know if something can be done about adding an image!

**Comment by zeknox** [comment]
Actually I'm going to leave this open as a reminder for myself to provide better feedback on the Error notice when sending emails in the background that didn't alert you when sending before.

**Comment by tj94** [comment]
Hey, 
i have a question what does this mean ?
![image](https://cloud.githubusercontent.com/assets/15603835/24114357/4864e506-0d76-11e7-94b7-1cdb5568901f.png)

the email is not sent; marked queued.

**Comment by zeknox** [comment]
That is an email that is properly sent.  The Queed message is the SMTP service saying it's actually queued up on their end and will send when it can.  Also you can see the 250 is an OK status for sent emails.

**Comment by tj94** [comment]
Oh yea, you are right! I didn't see them because they were going to junk like you said. Thanks for the help.
