### ISSUE TITLE
MYSQL 2

### ISSUE THREAD

**Issue by Indeserpen** [pentestgeek/phishing-frenzy#357]
Hello Zeknox!!!
So like i told you before PF one hell of good framework but hard to get working with all updates:
Trying it install on Kali Rolling 2016.2 64 AMD!! All fine until: rake db:migrate!
Here is output, there is sql error in:
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE UNIQUE INDEX `index_admins_on_email`  ON `admins` (`email`) 
/usr/local/rvm/gems/ruby-2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
/usr/local/rvm/gems/ruby-2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
/usr/local/rvm/gems/ruby-2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
/usr/local/rvm/gems/ruby-2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:541:in `add_index'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:654:in `method_missing'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:416:in `method_missing'
/var/www/html/phishing-frenzy/db/migrate/20131115173841_add_devise_to_admins.rb:38:in `up'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:571:in `up'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:590:in `migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:768:in `migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:1046:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:955:in `each'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:955:in `migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:801:in `migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
ActiveRecord::StatementInvalid: Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE UNIQUE INDEX `index_admins_on_email`  ON `admins` (`email`) 
/usr/local/rvm/gems/ruby-2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
/usr/local/rvm/gems/ruby-2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
/usr/local/rvm/gems/ruby-2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
/usr/local/rvm/gems/ruby-2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:541:in `add_index'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:654:in `method_missing'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:416:in `method_missing'
/var/www/html/phishing-frenzy/db/migrate/20131115173841_add_devise_to_admins.rb:38:in `up'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:571:in `up'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:590:in `migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:768:in `migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:1046:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:955:in `each'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:955:in `migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:801:in `migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Mysql2::Error: Specified key was too long; max key length is 767 bytes
/usr/local/rvm/gems/ruby-2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
/usr/local/rvm/gems/ruby-2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
/usr/local/rvm/gems/ruby-2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
/usr/local/rvm/gems/ruby-2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:541:in `add_index'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:654:in `method_missing'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:416:in `method_missing'
/var/www/html/phishing-frenzy/db/migrate/20131115173841_add_devise_to_admins.rb:38:in `up'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:571:in `up'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:590:in `migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:768:in `migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:1046:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:955:in `each'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:955:in `migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/migration.rb:801:in `migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by Indeserpen** [comment]
I thing you need to migrate mysql to mariadb!

**Comment by Indeserpen** [comment]
another issue with sprocket:
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /usr/local/rvm/gems/ruby-2.3.0/gems/less-rails-2.7.1/lib/less/rails/railtie.rb:15)
DEPRECATION WARNING: You are using the a deprecated processor interface Less::Rails::ImportProcessor.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /usr/local/rvm/gems/ruby-2.3.0/gems/less-rails-2.7.1/lib/less/rails/railtie.rb:20)

**Comment by Indeserpen** [comment]
Ubuntu 16 got frenzy up and running altough lot errors:
Generic Template Issue: Missing template /var/www/phishing-frenzy/public/uploads/attachment/file/20/office365.html.erb with "mailer". Searched in: * "/var/www/phishing-frenzy/public/uploads/attachment/file/20" 

Emails are failing when sending in sidekiq

**Comment by zeknox** [comment]
This is the first I've seen of `Mysql2::Error: Specified key was too long; max key length is 767 bytes`:

On a fresh copy of Ubuntu 16.04 this was not an issue on that version of MySQL so I believe you need to look into configuring your MySQL to support longer key values:
http://stackoverflow.com/questions/3489041/mysqlerror-specified-key-was-too-long-max-key-length-is-1000-bytes

In terms of the template issue, try creating / restoring a fresh new template.  It's throwing the error because it cannot find the office365.html.erb in the proper location.

**Comment by Indeserpen** [comment]
System on with SQL error was Kali Rolling 2016.2!! 
Now I have issue on ubuntu that PF cannot find mail attachments and sidekiq is giving errors!

**Comment by zeknox** [comment]
Like I said, try a fresh new template and test.  PF is unable to find the proper attachment file for whatever reason.

**Comment by Indeserpen** [comment]
So tried to make new template, uploaded all fine: Error continues: Generic Template Issue: Missing template /var/www/phishing-frenzy/public/uploads/attachment/file/24/email.html.erb with "mailer". Searched in: * "/var/www/phishing-frenzy/public/uploads/attachment/file/24"

**Comment by zeknox** [comment]
Does the file actually exist within that folder path?

**Comment by Indeserpen** [comment]
yes it exists

**Comment by zeknox** [comment]
Have you tested other templates with different emails and such?  Have you had any templates working basically is what I'm curious about.

**Comment by Indeserpen** [comment]
Just deleted all templates and restored travel agency and same error!

**Comment by zeknox** [comment]
You haven't answered my question.  Have you ever had a template working properly?

**Comment by Indeserpen** [comment]
Generic Template Issue: Missing template /var/www/phishing-frenzy/public/uploads/attachment/file/29/email.html.erb with "mailer". Searched in: * "/var/www/phishing-frenzy/public/uploads/attachment/file/29" 

![screenshot from 2017-03-21 18-57-42](https://cloud.githubusercontent.com/assets/13330266/24159656/4d6c6f4a-0e68-11e7-8036-f6241e150be3.png)

**Comment by Indeserpen** [comment]
On Ubuntu 16 its my first time! On previous machines all worked fine!

**Comment by zeknox** [comment]
Unfortunately I don't have PF installed on any Kali systems to test this out.  Might be something specific to the OS is what it sounds like.

**Comment by Indeserpen** [comment]
These are Ubuntu 16 errors!

**Comment by Indeserpen** [comment]
tired to migrate to production: 
![screenshot from 2017-03-21 19-01-38](https://cloud.githubusercontent.com/assets/13330266/24159830/e225e620-0e68-11e7-98f8-6b5b0c4f9b23.png)

**Comment by zeknox** [comment]
Likely because you have not configured your secrets.yml correctly:
http://stackoverflow.com/questions/29241053/incomplete-response-received-from-application-from-nginx-passenger

**Comment by Indeserpen** [comment]
All configured like said on your webpage:
![screenshot from 2017-03-21 19-06-35](https://cloud.githubusercontent.com/assets/13330266/24160073/9ccb1cb6-0e69-11e7-8c85-b23c7724b345.png)

**Comment by zeknox** [comment]
You need proper spacing in your YML file.  This is improper YAML style syntax, fix and try again.

**Comment by zeknox** [comment]
Also change your secret key now that you've shared with the world.

**Comment by Indeserpen** [comment]
Secret i generated to show you:)

**Comment by dsteadman** [comment]
@Indeserpen re-creating db with utf8 charset (default was utf8mb4) fixed key length errors for me:
```
CREATE SCHEMA pf_dev CHARSET utf8 COLLATE utf8_general_ci;
```
