### ISSUE TITLE
Issues with Statistics Collection 

### ISSUE THREAD

**Issue by deserteagle999** [pentestgeek/phishing-frenzy#359]
I would really appreciate any help I can get with this.  I was able to get most of the way through with the setup without issue but I have been stuck at the same spot for a few weeks now.  I am unable to get "email opened", "link clicked" etc statistics to report.  I have reviewed many of the similar issues posted here but none of the resolutions seem to apply.  I have now rebuilt the server several times with the same results.      

This is an internal only setup and I am aware of the issues with FQDN internally but I think I have done everything correctly.  I created static entries on my internal DNS server for both the Phishing Frenzy application site (s-phish) and the Phishing website (phishingtest).  I can resolve both sites via hostname on my test “victim” client and from the Phishing Frenzy server.  

I have my application site URL set to https://s-phish.***.int –which both my test “victim” client machine and the Phishing Frenzy box can resolve correctly to the Application URL.      

I am able to generate statistics using the method to manually visit the page entering in the UID.  

I am running this on Ubuntu 16.04 LTS and followed the online guide for that OS.  

Here are the results of my apachectl –S (I have replaced the domain with *** for security purposes.  

VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server S-PHISH.***.int (/etc/apache2/sites-enabled/000-d                                                                                                                                                             efault.conf:1)
         port 80 namevhost S-PHISH.***.int (/etc/apache2/sites-enabled/00                                                                                                                                                             0-default.conf:1)
         port 80 namevhost phishingtest (/etc/apache2/sites-enabled/1.conf:2)
                 alias phishingtest
*:443                  s-phish.***.int (/etc/apache2/sites-enabled/pf.con                                                                                                                                                             f:1)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex ssl-cache: using_defaults
Mutex default: dir="/var/lock/apache2" mechanism=fcntl
Mutex watchdog-callback: using_defaults
Mutex ssl-stapling-refresh: using_defaults
Mutex ssl-stapling: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33 not_used
Group: name="www-data" id=33 not_used

**Comment by deserteagle999** [comment]
I just tried another build using only 80 for the application site with the same results.  Everything works perfectly except statistics do not report back.  Can anyone out there assist at all?  Would love to get this up and running and feel like I am so close.

**Comment by mmjturner** [comment]
For what it's worth, I only see results in the individual UID sections. Might want to check there. Not sure whether a bug on my side or an error in my config, but "Password Seen" never says yes for me.

**Comment by zeknox** [comment]
@mmjturner I believe that is an issue with your HTML inputs not being named properly.  If you are collecting all other click stats but not passwords harvested, that makes me believe the HTML is not properly formatted with inputs with the name of UsernameForm and PasswordForm.  These are requirements for PF to know which parameters to store in to the DB.

@deserteagle999 first thing to test is seeing if you can manually invoke a click event following this guide here:   https://www.phishingfrenzy.com/resources/troubleshooting

**Comment by zeknox** [comment]
Closing due to lack of response, reopen if required.
