### ISSUE TITLE
Personalized emails?

### ISSUE THREAD

**Issue by mmjturner** [pentestgeek/phishing-frenzy#360]
I've been searching and experimenting, but I can't figure out how to personalize emails. i.e. Dear <Target FIrstname><Target Lastname>
I assumed using <%= victim.firstname %><%= victim.lastname %> in the html code was along the right lines but it actually prevents emails from sending.
Is there a correct way to accomplish this?

**Comment by icu814** [comment]
You are on the right track just off slightly.  Your code is accurate except you need to replace victim with @target.  Your code would be <%= @target.firstname %> and the same for last name just like you have it.  You could alternately use <%= @target.email_address %> to display the victim's email address.

**Comment by mmjturner** [comment]
I appreciate that! Thanks for the correction!
