### ISSUE TITLE
Create a simple user account?

### ISSUE THREAD

**Issue by RatedRR** [pentestgeek/phishing-frenzy#362]
Is it possible to create a simple user account (not admin account) and the admin fixes the privileges for that user? For example, he can only visualize reports for example ..
I tried to create a new account, but it seems that it has admin privileges as well.. I'm wondering if PF has this feature?

**Comment by zeknox** [comment]
Duplicate: https://github.com/pentestgeek/phishing-frenzy/issues/223#issuecomment-307057172
