### ISSUE TITLE
configuring phishing frenzy for public penetration testing 

### ISSUE THREAD

**Issue by quarkcanadian** [pentestgeek/phishing-frenzy#364]
Hey man, this is a great piece of software you created, id really like to donate for the effort you put into phishing frenzy, do you have some sort of fund online? 

As to the main question, im stumped on how to provision a domain name i purchased to my phishing frenzy box. My current configuration with phishing frenzy is that i have it completely working but only internally to the Linux station; not even private hosts can be initiated. On many different tutorials it says you need a FQDN but it never shows how to configure lets say a purchased godaddy Domain with phishing frenzy to allow externally collected  analytics on private and public networks. Right now im following this tutorial (https://sathisharthars.com/2014/07/02/installing-phishing-frenzy-in-kali-linux/) and it just looks like they inserted their domain into the pf.conf file. I did that, however, when i try to navigate to the url the "server DNS address could not be found." which leads me to believe more configuration has to happen on the godaddy side and i am not sure what to do. 

Thanks,

Jamie

**Comment by zeknox** [comment]
Sorry for the delay here with the holiday weekend I was out of town.  Yes, we do accept donations to the project. You can find the donate button on the bottom right of the main website.

So good question about the FQDN.  Once you obtain a public domain that you own and operate you can go into GoDaddy or wherever the Registrar is located and manage DNS.  Really the only record that you need to create is an A record to the public IP address of the phishing frenzy box.  This 1st FQDN can be leveraged to access the PF UI.

Then I would recommend a 2nd Domain or more for your phishing sites so they are completely isolated from the FQDN you use to access the PF Admin UI.  Same thing with this 2nd domain, create an A record to the public IP of the PF box.

Once you have the PF admin UI configured properly, along with a phishing site with an active campaign, Apache will know whether to serve up the PF Admin UI or the phishing site based on the FQDN that was used to access the site.

Hope this helps, cheers!
