### ISSUE TITLE
How to delete JS popup when viewing all passwords harvested?

### ISSUE THREAD

**Issue by RatedRR** [pentestgeek/phishing-frenzy#365]
I don't know why this JS pop-up is always showing up when viewing the passwords harvested like shown in the picture.
Is there any solution to block it and show the result without it?
I searched but can't find from where it appears and why..

Any help will be appreciated!

![2017-07-11_16-29-02](https://user-images.githubusercontent.com/26057862/28076370-cc861a80-665e-11e7-92e7-1551a73399ae.jpg)

**Comment by zeknox** [comment]
This is because you are running in development mode and the Bullet gem is detecting a way to optimize the db query on this page.

**Comment by RatedRR** [comment]
@zeknox  thanks for your quick answer, how to remove it please?

**Comment by zeknox** [comment]
I would recommend you convert your application to production mode.  BE WARNED.  This will setup a seperate db within mysql so all your data will be lost when migrating from dev > prod.

Instructions can be found here:
https://www.phishingfrenzy.com/resources/rails_production_mode

The other option if you want to stay running in dev mode (which is not recommended or ideal) is to remove Bullet from initializing by removing these lines here I believe:
https://github.com/pentestgeek/phishing-frenzy/blob/master/config/environments/development.rb#L46-L49

**Comment by RatedRR** [comment]
Thank you very much for your help and quick answers! 👍
