### ISSUE TITLE
Issues Configuring - Unable to Load Phishing Page

### ISSUE THREAD

**Issue by zjmc10** [pentestgeek/phishing-frenzy#371]
Hello, 

I just want to ensure I'm on the right track and if you could assist me with troubleshooting. I've followed the instructions in the Ubuntu guide and everything is installed. I can login and send an email successfully but I'm a bit lost when it comes to configuring the server to connect to. What I've done so far is purchase a domain, configure an A record to point to the IP address of the PF box. I've added this domain in Global Settings > Application Site URL. I did a test campaign and used the domain I purchased as the phish URL. When clicking the link http://domainIbought.info/?uid=SIFVSCCI it won't load. I'm a little confused regarding the VHOST and the actual domain purchased as well. I noticed the User and Group in the below file are listed as not used (I checked sudoers file, permissions etc and everything appears in order)

I've included a copy of apachectl -S below.

VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server intel.domain.com (/etc/apache2/sites-enabled/pf.conf:1)
         port 80 namevhost intel.domain.com (/etc/apache2/sites-enabled/pf.conf:1)
         port 80 namevhost phishing-frenzy.com (/etc/apache2/pf.conf:1)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex default: dir="/var/lock/apache2" mechanism=fcntl 
Mutex watchdog-callback: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33 not_used
Group: name="www-data" id=33 not_used

**Comment by zeknox** [comment]
You certainly on the right track.  A couple things that may assist is having a separate domain for the PF interface, and separate domain for your phishing sites.  In your Apache syntax above it looks like `intel.domain.com` is how you access the PF interface.

The FQDN that you configure for the PF interface is what you want to put inside Global Settings > Application Site URL.

Then your other domain for the phishing site can be placed within Campaign Settings > FQDN section.  Once you have an FQDN submitted for a Campaign you can make it go active which means that Apache should be serving up the phishing site.  You could navigate to it by appending `?uid=0` to the url.  Something like `http://phishingsite.info/?uid=0`.  If all goes well this should serve up your phishing site that is active and has an FQDN.

**Comment by zjmc10** [comment]
OK great thanks for the quick response - I'll try the above and come back to you.

**Comment by zjmc10** [comment]
Hmm I think I'm still doing something wrong - and based on some of the other issues I've seen googling it should be fairly simple (brain is fried from trying to get this going lol). My phishing link at least takes me to the PF box now but it's the login page for admin. Even when appending ?uid=0

I updated the Application Site URL to intel.domain.com (not the one purchased which I want to use as the external Phishing link) and entered the purchased domain.info into the campaign settings.

Phishing URL: http://domain.info
FQDN: domain.info

 I restarted Apache in between these steps.

**Comment by zeknox** [comment]
Make sure the campaign is active, and if it is active it should create a virtualhost configuration file within /etc/apache/sites-enabled/:id.conf.

`apachectl -S` should show you the configured domains for the PF interface (`pf.conf`) and any phishing sites (active campaigns).

Sometimes you have to manually refresh the browser a couple times for the phishing page actually gets renders.  Be careful of browser cache here.

**Comment by zjmc10** [comment]
Ok sure thank you. I just tried a new campaign and it's active. I tried in a different browser and still directed to the login page. I've included 5.conf and apachectl -S which throws up an error for ProxyPass. apachectl -S works successfully when 5.conf isn't there

/etc/apache2/sites-enabled$ cat 5.conf
#
<VirtualHost *:80>
    ServerName myexternaldomain.info
    ServerAlias myexternaldomain.info
    DocumentRoot /var/www/phishing-frenzy/public/deployed/campaigns/5
    DirectoryIndex index.php
    CustomLog     /var/www/phishing-frenzy/log/www-campaign-5-access.log combined
    ErrorLog      /var/www/phishing-frenzy/log/www-campaign-5-error.log



    ProxyPass /reports/image http://intel.domain.com/reports/image
    ProxyPassReverse /reports/image http://intel.domain.com/reports/image

</VirtualHost>
#



AH00526: Syntax error on line 12 of /etc/apache2/sites-enabled/5.conf:
Invalid command 'ProxyPass', perhaps misspelled or defined by a module not included in the server configuration
Action '-S' failed.
The Apache error log may have more information.

**Comment by zjmc10** [comment]
Ok fixed the proxypass issue, I can now access on mydomain.info/?uid=0 and displays the Intel template (all though in Chrome it just shows the code - FF and IE worked successfully).

Thanks a lot for your help! I should be able to play around from here and get a successful campaign going. Thanks again.

**Comment by zjmc10** [comment]
All working now - I had to install PHP mod for Apache2 as well to fix the above issue. Had some issues with the click and open stats not showing but the troubleshooting documentation helped out there (I had a silly mistake). Thanks again, closing this.

**Comment by zeknox** [comment]
Were the instructions lacking at all regarding the PHP mod and such?  If so let me know so I update the install guide on the website.

**Comment by zjmc10** [comment]
The Ubuntu instructions appear to be missing (unless it's covered elsewhere and I made a mistake) libapache2-mod which fixed it for me. The instructions just included 'php' as below:

Install required packages for Ubuntu OS
sudo apt-get install apache2 php mysql-server libmysqlclient-dev git curl

Once I get everything working again per the other issue I opened I can confirm if there were any other things missing from the instructions.

**Comment by dash-t** [comment]
Like zjmc10, I've gotten the emails to send, (and intel.domain to show locally on ubuntu vm) but when the emails get sent to test 0365 accounts I get the webpage showing the php source code and not the actual website. any ideas?

**Comment by zeknox** [comment]
@dash-t this sounds like the server which is hosting your phishing website is not rendering PHP properly.  Ensure that you have PHP installed, and the module is configured on the Apache web server (mod_php).

**Comment by dash-t** [comment]
@zeknox Thanks for your quick reply. I have php installed. 
secdemo@secdemo:/etc/apache2$ uname -a
Linux secdemo 4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

secdemo@secdemo:/etc/apache2$ php --version
PHP 7.0.33-0ubuntu0.16.04.2 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0ubuntu0.16.04.2, Copyright (c) 1999-2017, by Zend Technologies
secdemo@secdemo:/etc/apache2$ 

secdemo@secdemo:/etc/apache2$ which php       
/usr/bin/php.

Just to be clear are you saying in /etc/apache2/apache2.conf file is missing a necessary load-module?

LoadModule passenger_module /home/secdemo/.rvm/gems/ruby-2.3.0/gems/passenger-6.0.2/buildout/apache2/mod_passenger.so
   <IfModule mod_passenger.c>
     PassengerRoot /home/secdemo/.rvm/gems/ruby-2.3.0/gems/passenger-6.0.2
     PassengerDefaultRuby /home/secdemo/.rvm/gems/ruby-2.3.0/wrappers/ruby
   </IfModule>
secdemo@secdemo:/etc/apache2$ cat apache2.conf

**Comment by zeknox** [comment]
Ensure that mod_php is enabled within apache. This is a module which is required for Apache to know how to render the PHP code properly server side versus just displaying PHP ASCII text in the browser.

Additionally, ensure that the website file which is being rendered has a PHP extension.

**Comment by dash-t** [comment]
Thanks @zeknox .

secdemo@secdemo:/etc/apache2/sites-enabled$ apache2ctl -M
AH00526: Syntax error on line 23 of /etc/apache2/sites-enabled/1.conf:
Invalid command 'ProxyPass', perhaps misspelled or defined by a module not included in the server configuration
Action '-M' failed.

I think i'm just a bit lost with this apache and php fun. Very close to working though.

**Comment by zeknox** [comment]
Yeah that syntax error is because mod_proxy is not enabled within Apache as well.  Enable mod_proxy and give it a go.

**Comment by dash-t** [comment]
secdemo@secdemo:/etc/apache2/sites-enabled$ apache2ctl -M
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 lbmethod_byrequests_module (shared)
 mime_module (shared)
 mpm_event_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_balancer_module (shared)
 proxy_http_module (shared)
 setenvif_module (shared)
 slotmem_shm_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
 passenger_module (shared)
secdemo@secdemo:/etc/apache2/sites-enabled$ 

I believe I got mod_proxy working but site still shows up like this: (clipped version). 

 <?php
// Turn off all error reporting
error_reporting(0);


if (isset($_GET['uid'])) {
  $uid = $_GET['uid'];
} else {
  header('404 Not Found', true, 404);
  echo "404 Page Not Found";
  exit();
}


$password = htmlspecialchars($_POST['PasswordForm']);
$username = htmlspecialchars($_POST['UsernameForm']);

if ($password != '') {
  $creds = 'user:' . $username . ' password:' . $password;
}

**Comment by zeknox** [comment]
Have you tried leveraging the `a2enmod ` command?  It works great to enable modules within Apache.  You can also run `a2dismod` to disable modules.

Usually when you run a2enmod without any arguments it will tell you all of the available modules which can be enabled.  If PHP shows up in that list, the module is not enabled.

**Comment by dash-t** [comment]
I think you are on to something.
Not seeing php.. despite thinking it was installed. 

secdemo@secdemo:/etc/apache2/sites-enabled$ a2enmod
Your choices are: access_compat actions alias allowmethods asis auth_basic auth_digest auth_form authn_anon authn_core authn_dbd authn_dbm authn_file authn_socache authnz_fcgi authnz_ldap authz_core authz_dbd authz_dbm authz_groupfile authz_host authz_owner authz_user autoindex buffer cache cache_disk cache_socache cgi cgid charset_lite data dav dav_fs dav_lock dbd deflate dialup dir dump_io echo env expires ext_filter file_cache filter headers heartbeat heartmonitor ident include info lbmethod_bybusyness lbmethod_byrequests lbmethod_bytraffic lbmethod_heartbeat ldap log_debug log_forensic lua macro mime mime_magic mpm_event mpm_prefork mpm_worker negotiation proxy proxy_ajp proxy_balancer proxy_connect proxy_express proxy_fcgi proxy_fdpass proxy_ftp proxy_html proxy_http proxy_scgi proxy_wstunnel ratelimit reflector remoteip reqtimeout request rewrite sed session session_cookie session_crypto session_dbd setenvif slotmem_plain slotmem_shm socache_dbm socache_memcache socache_shmcb speling ssl status substitute suexec unique_id userdir usertrack vhost_alias xml2enc

**Comment by zeknox** [comment]
Based on the output above it looks like Apache is not aware of any PHP module even existing.  This makes me think that a package like `libapache2-mod-php` may be missing on the OS.  Try to install and see if that changes the situation and allows you to enable PHP in Apache.

**Comment by dash-t** [comment]
Typo -  meant it is enabled by not being in the list.

**Comment by zeknox** [comment]
I don't believe that mod_php is enabled because it doesn't show up in the list of `apachectl -M` in the output above.  You might be missing the package I mentioned above.

**Comment by dash-t** [comment]
@zeknox  You were spot on. It wasn't. I got it installed now.

secdemo@secdemo:/etc/apache2/sites-enabled$ sudo apt-get install libapache2-mod-php
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libapache2-mod-php7.0
Suggested packages:
  php-pear
The following NEW packages will be installed:
  libapache2-mod-php libapache2-mod-php7.0
0 upgraded, 2 newly installed, 0 to remove and 6 not upgraded.
Need to get 1,227 kB of archives.
After this operation, 4,295 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libapache2-mod-php7.0 amd64 7.0.33-0ubuntu0.16.04.2 [1,224 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libapache2-mod-php all 1:7.0+35ubuntu6.1 [2,990 B]
Fetched 1,227 kB in 0s (8,371 kB/s)            
Selecting previously unselected package libapache2-mod-php7.0.
(Reading database ... 222302 files and directories currently installed.)
Preparing to unpack .../libapache2-mod-php7.0_7.0.33-0ubuntu0.16.04.2_amd64.deb ...
Unpacking libapache2-mod-php7.0 (7.0.33-0ubuntu0.16.04.2) ...
Selecting previously unselected package libapache2-mod-php.
Preparing to unpack .../libapache2-mod-php_1%3a7.0+35ubuntu6.1_all.deb ...
Unpacking libapache2-mod-php (1:7.0+35ubuntu6.1) ...
Setting up libapache2-mod-php7.0 (7.0.33-0ubuntu0.16.04.2) ...

Creating config file /etc/php/7.0/apache2/php.ini with new version
php_invoke: Enable module exif for apache2 SAPI
php_invoke: Enable module gettext for apache2 SAPI
php_invoke: Enable module ftp for apache2 SAPI
php_invoke: Enable module readline for apache2 SAPI
php_invoke: Enable module opcache for apache2 SAPI
php_invoke: Enable module json for apache2 SAPI
php_invoke: Enable module ctype for apache2 SAPI
php_invoke: Enable module calendar for apache2 SAPI
php_invoke: Enable module sysvmsg for apache2 SAPI
php_invoke: Enable module posix for apache2 SAPI
php_invoke: Enable module pdo for apache2 SAPI
php_invoke: Enable module phar for apache2 SAPI
php_invoke: Enable module iconv for apache2 SAPI
php_invoke: Enable module shmop for apache2 SAPI
php_invoke: Enable module fileinfo for apache2 SAPI
php_invoke: Enable module sysvsem for apache2 SAPI
php_invoke: Enable module tokenizer for apache2 SAPI
php_invoke: Enable module sockets for apache2 SAPI
php_invoke: Enable module sysvshm for apache2 SAPI
Module mpm_event disabled.
Enabling module mpm_prefork.
apache2_switch_mpm Switch to prefork
apache2_invoke: Enable module php7.0
Setting up libapache2-mod-php (1:7.0+35ubuntu6.1) ...
secdemo@secdemo:/etc/apache2/sites-enabled$

**Comment by zeknox** [comment]
Good stuff, you should be in much better shape now.  Have fun!

**Comment by dash-t** [comment]
@zeknox  fantastic support & insight man!! Website loads.

**Comment by zeknox** [comment]
Happy to help, good work giving me the relevant data to go off of.  Cheers.
