### ISSUE TITLE
Phishing Frenzy shows the Apache default page :(

### ISSUE THREAD

**Issue by mantis-le-sin** [pentestgeek/phishing-frenzy#378]
Hi guys,
I was following this howto:
https://www.phishingfrenzy.com/resources/install_kali_linux

Right now the only page I can see is the Apache Default.

Let me give some more info:

******************************************************************
/etc/apache2/pf.conf

### <IfModule mod_passenger.c>
        PassengerRoot %ROOT
        PassengerRuby %RUBY
</IfModule>

<VirtualHost *:80>
        ServerName phishingfrenzy.local
        # !!! Be sure to point DocumentRoot to 'public'!
        DocumentRoot /var/www/phishing-frenzy/public
        RailsEnv development
        <Directory /var/www/phishing-frenzy/public>
                # This relaxes Apache security settings.
                AllowOverride all
                # MultiViews must be turned off.
                Options -MultiViews
        </Directory>
</VirtualHost>
******************************************************************

During the installation, I had an issue with 
"bundle exec sidekiq -C config/sidekiq.yml"

this was the error:

root@parzival:/var/www/phishing-frenzy# bundle exec sidekiq -C config/sidekiq.yml
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /var/www/phishing-frenzy/vendor/bundle/ruby/2.3.0/gems/less-rails-2.7.1/lib/less/rails/railtie.rb:15)
DEPRECATION WARNING: You are using the a deprecated processor interface Less::Rails::ImportProcessor.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /var/www/phishing-frenzy/vendor/bundle/ruby/2.3.0/gems/less-rails-2.7.1/lib/less/rails/railtie.rb:20)

         m,
         `$b
    .ss,  $$:         .,d$
    `$$P,d$P'    .,md$P"'
     ,$$$$$bmmd$$$P^'
   .d$$$$$$$$$$P'
   $$^' `"^$$$'       ____  _     _      _    _
   $:     ,$$:       / ___|(_) __| | ___| | _(_) __ _
   `b     :$$        \___ \| |/ _` |/ _ \ |/ / |/ _` |
          $$:         ___) | | (_| |  __/   <| | (_| |
          $$         |____/|_|\__,_|\___|_|\_\_|\__, |
        .d$$                                       |_|

... and stuck here.
******************************************************************

Any idea guys?

thanks
Mantis

**Comment by zeknox** [comment]
Those sidekiq messages are warnings, not errors and sidekiq is still running based on the looks here.

This appears to be an issue where your likely attempting to hit the PF interface via the IP address and not the FQDN defined within the VHOST (phishingfrenzy.local).  Edit your hosts file locally and points phishingfrenzy.local > IP address and try navigating to the PF interface using the FQDN (phishingfrenzy.local).

**Comment by mantis-le-sin** [comment]
Already linked 127.0.0.1 to phishingfrenzy.local on the hosts conf file. 
Same results with FQDN and ip address.

Regarding sidekiq actually the command was: bundle exec sidekiq -C config/sidekiq.yml
If i run service sidekiq start: Failed to start sidekiq.service: Unit sidekiq.service not found.

:(
****************************************************************
root@parzival:/var/www/phishing-frenzy# netstat -antp | grep LISTEN
tcp        0      0 127.0.0.1:25001         0.0.0.0:*               LISTEN      1664/nxclient.bin   
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      580/redis-server 12 
tcp        0      0 127.0.0.1:26002         0.0.0.0:*               LISTEN      1005/nxnode.bin     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      581/sshd            
tcp        0      0 127.0.0.1:7001          0.0.0.0:*               LISTEN      1650/nxnode.bin     
tcp        0      0 127.0.0.1:20063         0.0.0.0:*               LISTEN      585/nxserver.bin    
tcp        0      0 127.0.0.1:20000         0.0.0.0:*               LISTEN      984/nxserver.bin    
tcp        0      0 0.0.0.0:4000            0.0.0.0:*               LISTEN      682/nxd             
tcp        0      0 127.0.0.1:12001         0.0.0.0:*               LISTEN      1650/nxnode.bin     
tcp        0      0 127.0.0.1:12002         0.0.0.0:*               LISTEN      1005/nxnode.bin     
tcp6       0      0 :::80                   :::*                    LISTEN      4755/apache2        
tcp6       0      0 :::22                   :::*                    LISTEN      581/sshd            
tcp6       0      0 ::1:7001                :::*                    LISTEN      1650/nxnode.bin     
tcp6       0      0 :::4000                 :::*                    LISTEN      682/nxd 
****************************************************************

**Comment by zeknox** [comment]
Apache is serving up the default page instead of the PF interface for whatever reason.  `apachectl -S` will illustrate how you have Apache configured with all the VHOSTs in place.

**Comment by mantis-le-sin** [comment]
Thank dude, here the output:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using fe80::216:3eff:fedf:720f. Set the 'ServerName' directive globally to suppress this message
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server fe80::216:3eff:fedf:720f (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost fe80::216:3eff:fedf:720f (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost phishingfrenzy.local (/etc/apache2/pf.conf:6)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex watchdog-callback: using_defaults
Mutex default: dir="/var/run/apache2/" mechanism=default 
Mutex mpm-accept: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33
Group: name="www-data" id=33

**Comment by mantis-le-sin** [comment]
ok main document root seems not the right place I guess....

**Comment by zeknox** [comment]
<pre>port 80 namevhost phishingfrenzy.local (/etc/apache2/pf.conf:6)</pre>
Based on this line above, this says that Apache will serve up the website in pf.conf if you hit it with the FQDN of phishingfrenzy.local.

If it's not working, an alternative action could be to disable the default VHOST (/etc/apache2/sites-enabled/000-default.conf) while you're troubleshooting here.

**Comment by mantis-le-sin** [comment]
I commented every line on etc/apache2/sites-enabled/000-default.conf
Now 127.0.0.1 and the FQDN point at the same Apache default page and the public IP now instead of the same page han an: "We're sorry, but something went wrong." from Passenger.

Do I need an exorcist?? :D

**Comment by zeknox** [comment]
This sounds like Apache is now serving up the rails application.  It seems you have some sort of error that needs to be investigated.  Take a look at the application logs (/var/www/phishing-frenzy/logs/production.log)

**Comment by mantis-le-sin** [comment]
on /var/www/phishing-frenzy/log/ I have only:
development.log  sidekiq.log

**Comment by zeknox** [comment]
This sounds like you're running your rails application in development mode, therefor it would be the development.log file.

**Comment by mantis-le-sin** [comment]
totally empty :1st_place_medal:

**Comment by zeknox** [comment]
Sounds like a passenger or Apache error then.  Does the error page display any additional details?

**Comment by mantis-le-sin** [comment]
quite a lot actually:
http://parzival.9ine.technology/

**Comment by zeknox** [comment]
This is a passenger issue.  Follow the steps on the page to remediate the errors.

**Comment by mantis-le-sin** [comment]
Probably found the error:

root@parzival:/var/www/phishing-frenzy# rvm all do gem install --no-rdoc --no-ri passenger
Building native extensions. This could take a while...
Successfully installed passenger-5.2.0
1 gem installed
Building native extensions. This could take a while...
Successfully installed passenger-5.2.0
1 gem installed
Building native extensions. This could take a while...
Successfully installed passenger-5.2.0
1 gem installed
ERROR:  Error installing passenger:
	The last version of rack (>= 0) to support your Ruby & RubyGems was 1.6.8. Try installing it with `gem install rack -v 1.6.8` and then running the current command again
	rack requires Ruby version >= 2.2.2. The current ruby version is 2.1.0.
Building native extensions.  This could take a while...
Successfully installed passenger-5.2.0
1 gem installed

I think there is an issue checking my ruby version:
root@parzival:/var/www/phishing-frenzy# ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

**Comment by zeknox** [comment]
Have you tried running just `bundle install` from the application directory?

**Comment by mantis-le-sin** [comment]
ruby_dep-1.4.0 requires ruby version >= 2.2.5, which is incompatible with the current version, ruby 2.2.2p95

I am now installing 2.2.5
fingers crossed

**Comment by zeknox** [comment]
https://github.com/pentestgeek/phishing-frenzy/blob/master/.ruby-version
The application is designed for ruby 2.3.0 based on the .ruby-version file FYI. I understand that is contradictory to what the website install guide states.

**Comment by mantis-le-sin** [comment]
root@parzival:/var/www/phishing-frenzy# rvm all do gem install --no-rdoc --no-ri passenger
Building native extensions. This could take a while...
Successfully installed passenger-5.2.0
1 gem installed
Building native extensions. This could take a while...
Successfully installed passenger-5.2.0
1 gem installed
Building native extensions. This could take a while...
Successfully installed passenger-5.2.0
1 gem installed
ERROR:  Error installing passenger:
	The last version of rack (>= 0) to support your Ruby & RubyGems was 1.6.8. Try installing it with `gem install rack -v 1.6.8` and then running the current command again
	rack requires Ruby version >= 2.2.2. The current ruby version is 2.1.0.
Building native extensions.  This could take a while...
Successfully installed passenger-5.2.0
1 gem installed
Building native extensions. This could take a while...
Successfully installed passenger-5.2.0
1 gem installed
root@parzival:/var/www/phishing-frenzy# ruby -v
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]

**Comment by mantis-le-sin** [comment]
ok I will try 2.3.0

**Comment by zeknox** [comment]
I believe `rvm all` means install for all RVM versions.  You likely want something like `rvm 2.3.0 do gem install --no-rdoc --no-ri passenger` so that you only target a specific ruby version.

**Comment by mantis-le-sin** [comment]
good one!
root@parzival:/var/www/phishing-frenzy# rvm 2.3.0 do gem install --no-rdoc --no-ri passenger
Building native extensions. This could take a while...
Successfully installed passenger-5.2.0
1 gem installed

**Comment by mantis-le-sin** [comment]
ok, ok... something happened and look better.

Mysql2::Error
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")

Extracted source (around line #87):
      socket = socket.to_s unless socket.nil?

    connect user, pass, host, port, database, socket, flags
    end

    def parse_flags_array(flags, initial = 0)

**Comment by mantis-le-sin** [comment]
mysql service restarted.

Something different from the "how to".
When I connect I get:
MariaDB [(none)]> 

which is not what expected...

**Comment by mantis-le-sin** [comment]
and that's the issue:
http://parzival.9ine.technology/admins/sign_in

**Comment by mantis-le-sin** [comment]
@zeknox I decided to reset my VPS and restart again. :(

**Comment by zeknox** [comment]
We solved the root issue post here and got the PF interface to load.  The secondary issues you experiences are because the db was not migrated and seeded properly.
