### ISSUE TITLE
Indef of /  page instead of login page

### ISSUE THREAD

**Issue by mantis-le-sin** [pentestgeek/phishing-frenzy#380]
Hi guys,
after 2 days I can't still see the login page.
The installation went well but when I try to browse the login page I can see an index of page.
![parzlocal](https://user-images.githubusercontent.com/25244379/35974264-44208cb6-0cd0-11e8-8447-cf989132c1e2.png)

any idea on how to fix it?
thanks
mantis

**Comment by mantis-le-sin** [comment]
root@kali:/var/www/phishing-frenzy# apachectl -S
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server 127.0.1.1 (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost 127.0.1.1 (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost parzival.local (/etc/apache2/pf.conf:6)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex mpm-accept: using_defaults
Mutex watchdog-callback: using_defaults
Mutex default: dir="/var/run/apache2/" mechanism=default 
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33
Group: name="www-data" id=33


I see here a 127.0.1.1 where my hosts file point to 127.0.0.1  ... not sure if that's an issue

**Comment by mantis-le-sin** [comment]
I tried to # the passenger on pf.conf
![pfconf](https://user-images.githubusercontent.com/25244379/35975396-815bcfba-0cd4-11e8-8836-92d32dd014bd.png)
 and now I got this error:

![notags](https://user-images.githubusercontent.com/25244379/35975511-ec0b8152-0cd4-11e8-9041-3416477118c8.png)

**Comment by mantis-le-sin** [comment]
Now, the difference I see from my installation and the one on the HOWTO is mysql.
I think that kali "updated" the service with MariaDB

root@kali:/var/www/phishing-frenzy# mysql -u root -p 
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 38
Server version: 10.1.26-MariaDB-1 Debian unstable

Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>

**Comment by mantis-le-sin** [comment]
![dbseed](https://user-images.githubusercontent.com/25244379/35976278-89b598e6-0cd7-11e8-999f-b8c0bb32ad82.png)

![migrate](https://user-images.githubusercontent.com/25244379/35976347-ba7d33f8-0cd7-11e8-867e-7be06d8e909d.png)

**Comment by mantis-le-sin** [comment]
Dropped and recreated the database.
Now browsing the page: 
Mysql2::Error: Table 'pf_dev.global_settings' doesn't exist: SELECT `global_settings`.* FROM `global_settings` ORDER BY `global_settings`.`id` ASC LIMIT 1

guys I have no idea what to do now.

**Comment by mantis-le-sin** [comment]
![prod](https://user-images.githubusercontent.com/25244379/35977798-ef4ff58a-0cdb-11e8-8bd9-1112da41c585.png)

**Comment by mantis-le-sin** [comment]
nothing. After 48 hours I give up.
I need a framework ready for Monday and I can't see a solution here.
I really would be happy for the howto to be updated for the kali installation and retry with PF.
thanks anyway

**Comment by zeknox** [comment]
Slow down and read the error messages very carefully.  You can see in the last screenshot you provided it explicitly states: `Access denied for user pf_prod@localhost`

Lets think about that for a minute.  Access Denied for the user pf_prod...hmmm.  pf_prod was defined within the database.yml file right?  Well just maybe the database.yml file does not have the proper password defined, or perhaps the pf_prod account has not been created within MySQL to properly migrate and seed the db.

Access Denied is a very clear message of what the problem is.  Please ensure you are doing your own homework and legwork before you post for assistance.  The error messages usually tell you everything you need to know.  Good luck!

**Comment by mantis-le-sin** [comment]
I already checked the database.yml and everything was ok.

Now, I am giving another shot following the youtube video for the kali installation, which is again different from the howto.
Everything manageable until "bundle exec rake db:migrate"

now the error is:
== 20131115173841 AddDeviseToAdmins: migrating ================================
-- change_table(:admins)
   -> 0.3382s
-- add_index(:admins, :email, {:unique=>true})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE UNIQUE INDEX `index_admins_on_email`  ON `admins` (`email`)

**Comment by zeknox** [comment]
Read the last comment: https://github.com/pentestgeek/phishing-frenzy/issues/357
