### ISSUE TITLE
can not preview the email campaign 

### ISSUE THREAD

**Issue by kfr-ma** [pentestgeek/phishing-frenzy#382]
Hi I just installed phishing frenzy , when i create the campaign , and i wan to see the preview  i get the following error :

![preview-issue](https://user-images.githubusercontent.com/8555276/36242296-f5b9f9ca-1212-11e8-96b8-42bd857980b5.png)

the message is 

Generic Template Issue: Missing template /var/www/phishing-frenzy/public/uploads/attachment/file/6/efax.html.erb with "mailer". Searched in: * "/var/www/phishing-frenzy/public/uploads/attachment/file/6" 

Any suggestion , thx in advance

**Comment by zeknox** [comment]
You've got an error within the Email template that is making it unable to render.
