### ISSUE TITLE
can not import templates from web interface

### ISSUE THREAD

**Issue by kfr-ma** [pentestgeek/phishing-frenzy#383]
Hi when i try to import templates from the web interface as zip file , il have this error 

Not a backup archive: Missing template.yaml

Any suggestions

**Comment by zeknox** [comment]
You can only import templates which have been properly exported from Phishing Frenzy where the zip file contains a YAML file which defines what each file types role is when imported.

**Comment by zeknox** [comment]
Closing due to lack of response.
