### ISSUE TITLE
We're sorry, but something went wrong.  The issue has been logged for investigation. Please try again later.

### ISSUE THREAD

**Issue by ebakirmak** [pentestgeek/phishing-frenzy#384]
Hi,

phishing-frenzy isn't running in http://167.99.43.69/ address. (This adress is my droplet). I looked **https://github.com/pentestgeek/phishing-frenzy/issues/73** link. Please help me.

**Comment by zeknox** [comment]
Rails is running in production mode which is hiding the error messages.  You need to review the logs within /var/www/phishing-frenzy/logs/production.log to see what you're actual error is first.

**Comment by ebakirmak** [comment]
thanks for comeback and i installed gophish via docker so gophish ran. Also i am sending email using gmail. But i don't want using gmail. How to send from my localhost (via postfix) ?

**Comment by zeknox** [comment]
Were you able to resolve your issue here?

**Comment by ebakirmak** [comment]
Yes i resolved my issue. Thank you.
