### ISSUE TITLE
Connect PhishingFrenzy on Docker in DigitalOcean Server

### ISSUE THREAD

**Issue by ebakirmak** [pentestgeek/phishing-frenzy#385]
Hello 
I can't connected Phishing Frenzy installed on Docker in DigitalOcean Server. My IP address is xxx.xxx.xxx.xxx:80. I installed phishing frenzy image and port setting up as 80. But  when i connect that ip, i am seeing apache2 index.html installed on  docker image. Help me!

**Comment by ebakirmak** [comment]
Hello
I can connected but give me error? Picture is below. 

![screenshot from 2018-03-28 17-08-18](https://user-images.githubusercontent.com/11062124/38034519-252b7aae-32ab-11e8-8c87-f6b8f4392c97.png)

I created db and  edited config/database.yml with my username and password.

**Comment by zeknox** [comment]
This is not an error, this is the default rails page.  For some reason it is rendering the default page instead of the Phishing Frenzy login portal. I dont use the docker image much so I'm of a minimal help here.

**Comment by ebakirmak** [comment]
Thanks for comeback. Then What is Phishing Frenzy login portal?

**Comment by zeknox** [comment]
The Phishing Frenzy login portal is the default route that rails should be rendering.  Seems like there is a configuration issue where the web server is pointing to the /public/ directory instead of rendering the default rails routes.

**Comment by ebakirmak** [comment]
Yes i changed web server configuration but Now what do i do?
 i'm not understood. can you say step to step? Thank you

**Comment by zeknox** [comment]
Take a look at the installation guide here and make sure that your web server configurations are in alignment with what is documented.

https://www.phishingfrenzy.com/resources/install_ubuntu_linux

**Comment by ebakirmak** [comment]
three days along i didn't this. i try install ubuntu, install kali and install docker and i failed. But i will go on trying... Thanks for everything.

**Comment by zeknox** [comment]
Understood, rails is very challenging to deploy.
