### ISSUE TITLE
Phishing-Frenzy Reports Not Loading

### ISSUE THREAD

**Issue by mad0maxx** [pentestgeek/phishing-frenzy#387]
I am able to create a template and upload the necessary files.
I am able to create a campaign and configure the necessary settings.
I am able to send out test messages and launch campaigns.
I am able to view the raw apache logs and find entries with "?uid=".

I am unable to pull up previously completed Reports with user clicks.
I am unable to pull up currently running campaign statistics.
I am unable to track currently running campaign clicks.

The server was updated to resolve PCI issues on the server.
I am not sure what is broken or where to start.

![image](https://user-images.githubusercontent.com/23402017/39883929-36ba0f66-5456-11e8-8214-f23c64d756b4.png)

**Comment by zeknox** [comment]
For the stats issue, you'll likely want to view the browser console to see if there are any errors displayed when loading the reports page.

Based on the screenshot it looks like the data still exists because it's populating the datatable below. This looks to be an issue with D3 not pulling in the JSON data properly.

**Comment by mad0maxx** [comment]
Looking at the console logs, I am able to find these errors, but I am not sure what they really mean.


Mysql2::Error: Data too long for column 'browser' at row 1: INSERT INTO `visits` (`browser`, `created_at`, `extra`, `ip_address`, `updated_at`, `victim_id`) VALUES ('Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Win64; x64; Trident/7.0; .NET CLR 2.0.50727; SLCC2; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; Microsoft Outlook 16.0.4639; Microsoft Outlook 16.0.4639; ms-office; MSOffice 16)', '2018-05-10 18:09:32', 'SOURCE: EMAIL', '10.17.51.27', '2018-05-10 18:09:32', 170928)
[1m[36m (0.1ms)[0m [1mROLLBACK[0m
Completed 500 Internal Server Error in 758ms


ActiveRecord::StatementInvalid (Mysql2::Error: Data too long for column 'browser' at row 1: INSERT INTO `visits` (`browser`, `created_at`, `extra`, `ip_address`, `updated_at`, `victim_id`) VALUES ('Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Win64; x64; Trident/7.0; .NET CLR 2.0.50727; SLCC2; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; Microsoft Outlook 16.0.4639; Microsoft Outlook 16.0.4639; ms-office; MSOffice 16)', '2018-05-10 18:09:32', 'SOURCE: EMAIL', '10.17.51.27', '2018-05-10 18:09:32', 170928)):
app/controllers/reports_controller.rb:27:in `image'


ActionController::RoutingError (No route matches [GET] "/stylesheets/sessions.css"):


Rendered /usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.1.7/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (213.2ms)


Rendered /usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.1.7/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (138.1ms)


I also noticed that I am running out of disk space on / so I tried to delete an old campaign that is no longer in use but I am unable to delete the campaign.

**Comment by zeknox** [comment]
Those aren't quite the logs I was refering too.  Open your browser, navigate to the reports page and in chrome you can right click and chose "inspect". This will open up a console in the browser, refresh the page and see what errors show up.

You mentioned that you updated the server, but any context of what you actually changed here?  The errors in the rails console that you posted show that MySQL is throwing errors that I have not seen in this context. I've seen MySQL data too long when the site cloning functionality existed within the tool, but this seems different.

**Comment by mad0maxx** [comment]
Browser Inspect Console.

Reports page
```
Empty string passed to getElementById().
jquery.self.js:2799:12
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element.
list
```

Reports Campaign Stats Page
```
Empty string passed to getElementById().
jquery.self.js:2799:12
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element.
stats
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: 
var w = 395,
    h = 320,
    r =  Math....
stats:312
```

I am not 100% sure on what all was updated. I know that there was a third party ssl certificate installed, which should not be an issue. I think the apache installation was updated and the apache.conf file had http security headers added.

**Comment by zeknox** [comment]
Those logs look good and don't seem to be the root issue.  Something must have changed where MySQL will no longer store or function properly because of the data being to large.  Perhaps MySQL was upgraded?

https://stackoverflow.com/questions/16350132/mysql-mysql2error-data-too-long-for-column-description-at-row-1

**Comment by zeknox** [comment]
Any updates here?

**Comment by mad0maxx** [comment]
We decided to reinstall from scratch to resolve any issues, thank you for all your assistance.
