### ISSUE TITLE
API for scripting 

### ISSUE THREAD

**Issue by justaskingquestions** [pentestgeek/phishing-frenzy#390]
Does PF have an API so I can script things like the bulk import of of emails or retrieve the status of my campagins?

**Comment by zeknox** [comment]
No PF does not have an API to help with bulk importing of emails.

**Comment by justaskingquestions** [comment]
Sorry, maybe my question was too specific. I am interested in an API in general i.e. a documented interface that allows me to perform actions in PF from something other than the web UI in the browser.

**Comment by zeknox** [comment]
No, PF does not have an API for automating tasks like you're after.

**Comment by justaskingquestions** [comment]
Thanks for clarification.
