### ISSUE TITLE
Plugin Mechanism

### ISSUE THREAD

**Issue by justaskingquestions** [pentestgeek/phishing-frenzy#391]
Does PF have a means to add functionality (e.g. reporting feature) via extension/plugins?

**Comment by zeknox** [comment]
Not really sure what you're asking here, but PF is an open source project so you can certainly add any functionality you require.

**Comment by justaskingquestions** [comment]
Thanks for the clear reply. Sorry for bombarding you with questions. I am currently trying to get an overview of phishing frameworks out there and trying to compare so naturally some end up not having special features other's don't. Not necessarily a measure of quality, just part of the comparison. Keep up the good work!
