### ISSUE TITLE
Phishingfrenzy.com Documentation appears to be down

### ISSUE THREAD

**Issue by UnknownUserG** [pentestgeek/phishing-frenzy#393]
Hello,

The site phishingfrenzy.com appears to be offline. Do you have a link to the documentation/resources saved up somewhere?

Thanks!

**Comment by zeknox** [comment]
Thanks for the heads up here, website is back online.

**Comment by UnknownUserG** [comment]
The site appears to be down again

**Comment by zeknox** [comment]
Apologies here and thanks for the heads up.  My VPS provider is shutting down the VPS intermittently due to load on their side during maintenance windows and does not notify me at all. Long-term working on solution to migrate to a new VPS provider.
