### ISSUE TITLE
Generic Template Issue: Missing template

### ISSUE THREAD

**Issue by David1Hasselhoff** [pentestgeek/phishing-frenzy#394]
Getting the following error message when attempting to preview a Campaign:

Generic Template Issue: Missing template /var/www/phishing-frenzy/public/uploads/attachment/file/13/efax.html.erb with "mailer". Searched in: * "/var/www/phishing-frenzy/public/uploads/attachment/file/13"

I have attempted to copy existing templates as well as import templates from the GitHub site however any attempts to select them result in the same error with the exception of the path may differ a bit based on the location.  I have verified that the etb file does exist in the location specified each time however there seems to be some sort of disconnect with the mailer.  

Currently running Phishing Frenzy on Ubuntu 18.04.1 LTS Server version

Any help is appreciated.

**Comment by zeknox** [comment]
Does the problem only occur when you attempt to preview or does it also happen when clicking "test" or "launch" button within the campaign?

Make sure that the Template has an email file and you've selected "E-mail" as the dropdown option under the "Template Files" section.

**Comment by David1Hasselhoff** [comment]
Yes the problem does occur during all phases of the campaign.  Also I have verified the template files, however I would have assumed these to be correct as they were part of a standard template import from this site.   Wish there was more info I could provide.

**Comment by zeknox** [comment]
Does `/var/www/phishing-frenzy/public/uploads/attachment/file/13/efax.html.erb` exist on the file system?

**Comment by David1Hasselhoff** [comment]
yes it does

**Comment by David1Hasselhoff** [comment]
-rw-r--r-- 1 www-data www-data 873 Jul 31 20:35 /var/www/phishing-frenzy/public/uploads/attachment/file/13/efax.html.erb

**Comment by zeknox** [comment]
It looks like it is tripping this rescue statement here: https://github.com/pentestgeek/phishing-frenzy/blob/master/app/controllers/email_controller.rb#L26-L28

You're running a recent version of PF currently?  I've personally never tested PF on Ubuntu 18.04.1 either FYI.

**Comment by David1Hasselhoff** [comment]
I believe the issue is related to the fact that we are using the server version of Ubuntu rather than the desktop version that has a local GUI.  We are going back and attempting to use Ubuntu desktop version with a full GUI and use the <servername>:local web interface rather than a remote web interface.  Hopefully we will get more traction that way.  I'll come back and post my results next week when we complete the install.

**Comment by David1Hasselhoff** [comment]
We are going to reinstall on a desktop version of Ubuntu in hopes that being able to use the http://<servername>:local web interface may help us gain some traction.  I'll post our results next week.  Thanks for the help.

**Comment by David1Hasselhoff** [comment]
Trying to use the desktop interface did not solve the issue but the mail still works so we don't have the ability to preview but its all good.  Now on the next issue.
