### ISSUE TITLE
Harvested vs Passwords

### ISSUE THREAD

**Issue by David1Hasselhoff** [pentestgeek/phishing-frenzy#397]
After I have run my campaign and view the results I see that there are two fields listed: Harvested with a number and Passwords with a different number.  What is the difference?

**Comment by zeknox** [comment]
Great question. The Harvested metric is the number of unique targets which have entered passwords into the phishing site.

The Passwords metric is the number of password entries the phishing site has received. (e.g you phished 1 user, but they entered credentials 2 times. This would be harvested: 1, passwords: 2). Hope this helps.

**Comment by David1Hasselhoff** [comment]
Thank you!  What a great tool by the way!

**Comment by zeknox** [comment]
Appreciate it. Have fun!

**Comment by David1Hasselhoff** [comment]
Question answered, closing
