### ISSUE TITLE
Stats Tracking not Working

### ISSUE THREAD

**Issue by dickens88** [pentestgeek/phishing-frenzy#398]
Hi
I installed the latest version from docker hub. by
docker run --name phishingfrenzy -p 82:80 -d b00stfr3ak/ubuntu-phishingfrenzy

the instance started and most of functions are correct . After I create a new Campaign and launch it, everything seems ok, until I click the phishing link in email. I can see the phishing web page, but after i click i found nothing changed in report page which may means phishing-frenzy didn't tracking my click event.

blow is `apache2ctl -S` result:

root@1734c92e20c0:/# apache2ctl -S
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.7. Set the 'ServerName' directive globally to suppress this message
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server 172.17.0.7 (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost 172.17.0.7 (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost intel.domain.com (/etc/apache2/sites-enabled/1.conf:2)
                 alias intel.domain.com
         port 80 namevhost phishingfrenzy.local (/etc/apache2/pf.conf:1)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex default: dir="/var/lock/apache2" mechanism=fcntl 
Mutex mpm-accept: using_defaults
Mutex watchdog-callback: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33
Group: name="www-data" id=33

in addition, I can call this URL manually `http://phishingfrenzy.local:82/reports/results/?uid=WMMWPEPG`, it return the right answer and report page also show the change. but if i go back to click normal link like `http://intel.domain.com:82/index.php?UID=WMMWPEPG` nothing changed.

**Comment by dickens88** [comment]
i also move to log file `/var/www/phishing-frenzy/log/www-campaign-1-access.log` and i can find my visit log 

10.25.30.237 - - [07/Sep/2018:04:56:09 +0000] "GET /index.php?UID=WMMWPEPG HTTP/1.1" 200 23742 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
10.25.30.237 - - [07/Sep/2018:04:56:09 +0000] "GET /etc/designs/intel/us/en/js/predictive-search.js HTTP/1.1" 404 541 "http://intel.domain.com:82/index.php?UID=WMMWPEPG" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTM
L, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
10.25.30.237 - - [07/Sep/2018:04:56:09 +0000] "GET /content/data/globalelements/US/en/globalnav2.out.js HTTP/1.1" 404 546 "http://intel.domain.com:82/index.php?UID=WMMWPEPG" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (
KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
10.25.30.237 - - [07/Sep/2018:04:56:18 +0000] "GET /content/dam/www/global/wap/wap.js HTTP/1.1" 404 528 "http://intel.domain.com:82/index.php?UID=WMMWPEPG" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
 Chrome/68.0.3440.106 Safari/537.36"

**Comment by zeknox** [comment]
When you view the Reports page, can you monitor the JavaScript console within the browser to see if there are any D3 errors?  Trying to understand if this is an actual issue with tracking clicks or D3 crashing on load.

Also, make sure that `phishingfrenzy.local` is resolvable by the Phishing Frenzy server. If it is not, the PHP tags will not be able to resolve to 127.0.0.1 and therefor can never send the click event to the proper API endpoint.

**Comment by dickens88** [comment]
@zeknox thanks for the reply. I checked the browser console log, except for two 404 error nothing else.

![image](https://user-images.githubusercontent.com/8390209/45229498-89e63880-b2f8-11e8-89a5-db93fede8b36.png)

I have add host ip and `phishingfrenzy.local` to hosts, and I can visit 'http://phishingfrenzy.local:82/reports/stats' correctly. I have tried to install this docker images on my two different machines and get the same result. pls help if I miss something.

**Comment by zeknox** [comment]
When you click on the phishing website, can you monitor your `production.log` file which should be located at `/var/www/phishing-frenzy/logs/production.log`.  This may indicate an error being thrown or that the click event in never getting triggered.

**Comment by dickens88** [comment]
I checked the path you said, but I didn't find `/var/www/phishing-frenzy/logs/production.log` or `/var/www/phishing-frenzy/logs`. In my docker container, I can only find `development.log` in `/var/www/phishing-frenzy/log/development.log`. It seems I didn't use production mode. I don't know if this has any effect on this issue.
And I also observed  `development.log`,  When I click publish website, I can only find one error like this:

`ActionController::RoutingError (No route matches [GET] "/images/sort_asc.png"):
  actionpack (4.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.7) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.7) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.7) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.7) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.7) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.7) lib/rails/engine.rb:514:in `call'
  railties (4.1.7) lib/rails/application.rb:144:in `call'
  railties (4.1.7) lib/rails/railtie.rb:194:in `public_send'
  railties (4.1.7) lib/rails/railtie.rb:194:in `method_missing'
  passenger (5.0.6) lib/phusion_passenger/rack/thread_handler_extension.rb:85:in `process_request'
  passenger (5.0.6) lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
  passenger (5.0.6) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  passenger (5.0.6) lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
  passenger (5.0.6) lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
`

**Comment by zeknox** [comment]
The development.log file should work as well.  It's because your running rails in development mode vs production which is fine for troubleshooting.

This error is related to the icons within the datatables which isn't related to the tracking issues you're experiencing.

>ActionController::RoutingError (No route matches [GET] "/images/sort_asc.png")

You should see a POST request coming inbound within this log when you browse the phishing site as a visitor.  If you are not it sounds like the PHP code is unable to make the proper POST request to the Phishing Frenzy API.

**Comment by dickens88** [comment]
yes,  I think you're right. When I visit phishing website I never see any POST request. so do you have any idea how to solve it?

**Comment by zeknox** [comment]
Closing due to lack of response, please re-open if this is still an issue.
