### ISSUE TITLE
[URGENT] Upload a full website as a template

### ISSUE THREAD

**Issue by adityasriv22** [pentestgeek/phishing-frenzy#400]
How can I upload a full website as a template at once with segregated folders of css,js,images, In templates it has the option to put single file at a time, in that case it will take a lot of manual work to individually upload all files.

**Comment by adityasriv22** [comment]
This is urgent!!!!

**Comment by zeknox** [comment]
Upload a zip archive and PF will extract the sub folders when campaign is made active.

**Comment by adityasriv22** [comment]
it throws 404 error

![screenshot from 2018-11-13 22-02-05](https://user-images.githubusercontent.com/9220248/48427883-cbc7ab00-e78f-11e8-970c-ea6915e078ef.png)

**Comment by zeknox** [comment]
Folder structure within the zip or the defined index attribute within the template is the problem.

**Comment by adityasriv22** [comment]
I edited the 3.conf file to point to the directory , it works on my localhost by visiting the server name mentioned in conf file but I am not sure if , when the campaighn goes live will it be able to work properly

**Comment by adityasriv22** [comment]
if the website is extracted do i need to keep the email file and email image attachment in the same folder or the /deployed/campaigns/3 folder , the email doesn't seem to working if its keep out side the main website, also I uploaded the email files and images separately, and that does not show in the /deployed/campaigns/3/

**Comment by zeknox** [comment]
No, the email and email image attachment needs to be uploaded to the template separately outside of the zip archive. The zip archive is only used to extract website files and will not impact the email.

**Comment by adityasriv22** [comment]
Thanks so much zeknox , can I know one more thing on how to change my time zone?

**Comment by zeknox** [comment]
Pretty sure all Time is in UTC time zone so you’ll need to manually convert to whatever zone you are in.
