### ISSUE TITLE
PHP tags not getting inserted in Custom Template

### ISSUE THREAD

**Issue by adityasriv22** [pentestgeek/phishing-frenzy#401]
HI ,

I am trying a custom template , I have given the name of input field as UsernameForm and PasswordForm but the php tags is not getting inserted in the template
Php is also working
mannually opening the url for email open works by uid but not on live campaighn,
my application site url setting is http://phishing-frenzy.com
 Please help.

**Comment by zeknox** [comment]
What is the file extension of your website files? If the PHP tags are not getting inserted into the website files this would likely be an indication you’re not using PHP website files.

The PHP tags would be prepended to the website files regardless of the input field names.

PHP tags are added only when a campaign goes active.

**Comment by adityasriv22** [comment]
the extensions are .php only

**Comment by adityasriv22** [comment]
![screenshot from 2018-11-30 19-26-59](https://user-images.githubusercontent.com/9220248/49293371-fb87ea00-f4d5-11e8-976b-0c22adb48caf.png)

this is my campaigh file directory structure,also tell me the application site url needs a dns entry to the vps or only the phishing site domain to gather creds.

**Comment by zeknox** [comment]
You need to leverage the ansible branch of this repository. Since you are uploading a zip archive as the website files we have not merged in the latest code to the master branch which addresses adding the PHP tags to PHP files within a zip archive.

https://github.com/pentestgeek/phishing-frenzy/tree/ansible?files=1

https://github.com/pentestgeek/phishing-frenzy/commit/a692691935313cd0157debeb02c34a227ee4d41e

—
Brandon McCann

**Comment by adityasriv22** [comment]
How do i do that, do i need to use git pull in the phishing frenzy directory or is there any other command

**Comment by zeknox** [comment]
You likely just need to run “git checkout ansible” within the phishing frenzy repo.

If running in production mode you likely need to recompile your assets again and restart Apache.

—
Brandon McCann

**Comment by adityasriv22** [comment]
I executed the command
 and visited app url in browser , got this error.
![screenshot from 2018-11-30 19-45-12](https://user-images.githubusercontent.com/9220248/49294307-9d103b00-f4d8-11e8-938b-c3632c471f5f.png)

**Comment by zeknox** [comment]
Since you likely ran the git command as root you need to set file permissions back appropriately.

<pre>sudo chown -R www-data:www-data /var/www/phishing-frenzy/</pre>

Then restart apache again and test.

**Comment by zeknox** [comment]
Also you may need to purge some of your tmp and cache files which could be owned by root still if the commands above do not work.

You would run these from within the phishing-frenzy directory.
<pre>
# rake tmp:pids:clear
# rake tmp:sessions:clear
# rake tmp:sockets:clear
# rake tmp:cache:clear
</pre>

**Comment by adityasriv22** [comment]
Hi the app is running, 
And PHP is getting inserted , thanks for that,
 But I am geting php code on my website.

![screenshot from 2018-11-30 20-11-33](https://user-images.githubusercontent.com/9220248/49295983-17db5500-f4dd-11e8-9792-7e319132ecac.png)
![screenshot from 2018-11-30 20-11-33](https://user-images.githubusercontent.com/9220248/49295998-1f9af980-f4dd-11e8-8f11-cfd18eeb6fa7.png)

I just want to get the stats to work, I am getting email sent in the reports only , no link open or , credentials.

**Comment by zeknox** [comment]
PHP is not getting rendered properly on the server side.  Likely an issue with PHP not installed, or the PHP module not enabled within Apache.  This is why you're seeing the raw PHP code vs it being rendered.

Having PHP rendering properly is a dependency to functional stats at this time.

**Comment by adityasriv22** [comment]
Thanks brandon , apparently the issue was php not rendering only.
Everything seems to work fine

Regards

**Comment by zeknox** [comment]
Awesome, good luck and have fun!
