### ISSUE TITLE
Configured Display From setting ignored

### ISSUE THREAD

**Issue by BradBeacham** [pentestgeek/phishing-frenzy#402]
Hey There!

The latest version of PF appears as if it is ignoring the Display From: setting within the campaign configuration page.  All emails I send via the application, either with a value entered in the field or blank appear to be constructed "FROM: abc abc <abc@email.com>".

**Comment by BradBeacham** [comment]
Switched to an older version to validate the observed actions and the same activity was displayed.  I have a feeling this may be a recent change from office 365.  Closing the issue as it is likely nothing to do with PF :)

**Comment by zeknox** [comment]
Just so I have a better understanding here.  Were you leveraging Office365 as the SMTP relay, or was Office365 just the recipient?

**Comment by BradBeacham** [comment]
Office365 was the relay and mail server.  Confirmed its a Microsoft thing, it seems (or at least for me) to enforce the name configured for the user account as the FROM: header.
