### ISSUE TITLE
Statistics - new implementations 

### ISSUE THREAD

**Issue by vbaOne** [pentestgeek/phishing-frenzy#81]
Hello,

I have implemented some modifications on phishing-frenzy (on the OLD version). 

Broadly speaking, some statistics are generated when victims just open the phishing email (using a 1x1 pix. image). These information are retrieved using the logs of Apache.  

It is possible to generate an excel file with these statistics using the "axlsx" gem. 

Here is an example: the screenshot shows statistics generated by the application.

![phishing-frenzy](https://cloud.githubusercontent.com/assets/7385966/3470377/c75979aa-02b9-11e4-85a6-ccf62ed65bc8.png)

I would like to discuss the possibility to implement it in the new version of phishing frenzy. How may I contact Zeknox please?

Thank you in advance,

Regards,

Victor

**Comment by Miketmclaughlin** [comment]
Thanks guys! My fault again!

Cheers for the quick replies.
