### ISSUE TITLE
SITE_URL on arbitrary port causes Link Clicked and Password Seen To Not Work

### ISSUE THREAD

**Issue by fschauvinhold** [pentestgeek/phishing-frenzy#89]
Hey, I launched this against myself-opened email, clicked link and entered password.  In reporting, email opened show as YES, but Link clicked and password seen areas are still displaying as NO. Any idea what I might be doing wrong?

**Comment by zeknox** [comment]
This has been added to the Phishing Frenzy Troubleshooting webpage:
* http://www.phishingfrenzy.com/resources/troubleshooting
